// Code generated by docsync from the official WeChat documentation. DO NOT EDIT.
// The API surface (names, request/response shapes) is derived deterministically
// from the endpoints; regenerate with "make docs-sync". If this file changes
// under you, the upstream documentation changed.

package official

import (
	"context"
	"github.com/go-sphere/weixin-api/core"
)

var postCgiBinMediaVoiceAddvoicetorecofortextErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40010: {
		Desc:     "invalid voice size",
		Solution: "不合法的语音文件大小",
	},
}

// PostCgiBinMediaVoiceAddvoicetorecofortext 上传语音文件 (POST /cgi-bin/media/voice/addvoicetorecofortext)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/openpoc/ai/api_addvoicetorecofortext.html
// PostCgiBinMediaVoiceAddvoicetorecofortextRequest carries the documented parameters of one API call.
type PostCgiBinMediaVoiceAddvoicetorecofortextRequest struct {
	// 文件格式(只支持mp3,16k,单声道,最大1M)
	Format string `query:"format"`
	// 语音唯一标识
	VoiceID string `query:"voice_id"`
	// 语言,zh_CN 或 en_US,默认中文
	Lang string `query:"lang,omitempty"`
}

// PostCgiBinMediaVoiceAddvoicetorecofortextResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinMediaVoiceAddvoicetorecofortextResponse struct {
	// 错误码
	Errcode string `json:"errcode,omitempty"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostCgiBinMediaVoiceAddvoicetorecofortext(ctx context.Context, req *PostCgiBinMediaVoiceAddvoicetorecofortextRequest, file *core.Upload) (*PostCgiBinMediaVoiceAddvoicetorecofortextResponse, error) {
	data, err := core.CallUpload(c.EndpointClient, ctx, "/cgi-bin/media/voice/addvoicetorecofortext", req, file, postCgiBinMediaVoiceAddvoicetorecofortextErrCodes, true)
	return core.Decode[PostCgiBinMediaVoiceAddvoicetorecofortextResponse](ctx, "POST", "/cgi-bin/media/voice/addvoicetorecofortext", data, err)
}

var postCgiBinMediaVoiceQueryrecoresultfortextErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostCgiBinMediaVoiceQueryrecoresultfortext 获取语音识别结果 (POST /cgi-bin/media/voice/queryrecoresultfortext)
// Doc: https://developers.weixin.qq.com/doc/service/api/openpoc/ai/api_queryrecoresultfortext.html
// PostCgiBinMediaVoiceQueryrecoresultfortextRequest carries the documented parameters of one API call.
type PostCgiBinMediaVoiceQueryrecoresultfortextRequest struct {
	// 语音唯一标识
	VoiceID string `query:"voice_id"`
	// 语言,zh_CN 或 en_US,默认中文
	Lang string `query:"lang,omitempty"`
}

// PostCgiBinMediaVoiceQueryrecoresultfortextResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinMediaVoiceQueryrecoresultfortextResponse struct {
	// 识别结果
	Result string `json:"result,omitempty"`
}

func (c *Client) PostCgiBinMediaVoiceQueryrecoresultfortext(ctx context.Context, req *PostCgiBinMediaVoiceQueryrecoresultfortextRequest) (*PostCgiBinMediaVoiceQueryrecoresultfortextResponse, error) {
	return core.Call[PostCgiBinMediaVoiceQueryrecoresultfortextResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/media/voice/queryrecoresultfortext", req, postCgiBinMediaVoiceQueryrecoresultfortextErrCodes, true, core.SignNone)
}

var postCgiBinMediaVoiceTranslatecontentErrCodes = map[int]core.ErrDoc{
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40035: {
		Desc:     "invalid args size",
		Solution: "不合法的参数",
	},
}

// PostCgiBinMediaVoiceTranslatecontent 微信翻译 (POST /cgi-bin/media/voice/translatecontent)
// Doc: https://developers.weixin.qq.com/doc/service/api/openpoc/ai/api_translatecontent.html
// PostCgiBinMediaVoiceTranslatecontentRequest carries the documented parameters of one API call.
type PostCgiBinMediaVoiceTranslatecontentRequest struct {
	// 源语言,zh_CN 或 en_US
	Lfrom string `query:"lfrom"`
	// 目标语言,zh_CN 或 en_US
	Lto string `query:"lto"`
	// 源内容(utf8格式,最大600Byte)
	Content string `json:"content"`
}

// PostCgiBinMediaVoiceTranslatecontentResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinMediaVoiceTranslatecontentResponse struct {
	// 原文内容
	FromContent string `json:"from_content,omitempty"`
	// 译文内容
	ToContent string `json:"to_content,omitempty"`
}

func (c *Client) PostCgiBinMediaVoiceTranslatecontent(ctx context.Context, req *PostCgiBinMediaVoiceTranslatecontentRequest) (*PostCgiBinMediaVoiceTranslatecontentResponse, error) {
	return core.Call[PostCgiBinMediaVoiceTranslatecontentResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/media/voice/translatecontent", req, postCgiBinMediaVoiceTranslatecontentErrCodes, true, core.SignNone)
}

var postCvImgAicropErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	101000: {
		Desc:     "invalid image url",
		Solution: "图片URL错误",
	},
	101002: {
		Desc:     "invalid image data",
		Solution: "图片数据无效",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostCvImgAicrop 图片智能裁剪 (POST /cv/img/aicrop)
// Doc: https://developers.weixin.qq.com/doc/service/api/openpoc/image/api_imgaicrop.html
// PostCvImgAicropRequest carries the documented parameters of one API call.
type PostCvImgAicropRequest struct {
	// 要检测的图片 url,传这个则不用传 img 参数。
	ImgURL string `query:"img_url,omitempty"`
	// 宽高比;如果提供多个宽高比,请以英文逗号","分隔,最多支持5个宽高比
	Ratios string `json:"ratios,omitempty"`
}

// PostCvImgAicropResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCvImgAicropResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 智能裁剪结果
	Results []*PostCvImgAicropResponseResultsObject `json:"results,omitempty"`
	// 图片大小
	ImgSize *PostCvImgAicropResponseImgSizeObject `json:"img_size,omitempty"`
}

// PostCvImgAicropResponseResultsObject is a documented nested object.
type PostCvImgAicropResponseResultsObject struct {
	// 左上角x
	CropLeft int64 `json:"crop_left,omitzero"`
	// 左上角y
	CropTop int64 `json:"crop_top,omitzero"`
	// 右下角x
	CropRight int64 `json:"crop_right,omitzero"`
	// 右下角y
	CropBottom int64 `json:"crop_bottom,omitzero"`
}

// PostCvImgAicropResponseImgSizeObject is a documented nested object.
type PostCvImgAicropResponseImgSizeObject struct {
	// 宽度
	W int64 `json:"w,omitzero"`
	// 高度
	H int64 `json:"h,omitzero"`
}

func (c *Client) PostCvImgAicrop(ctx context.Context, req *PostCvImgAicropRequest, file *core.Upload) (*PostCvImgAicropResponse, error) {
	data, err := core.CallUpload(c.EndpointClient, ctx, "/cv/img/aicrop", req, file, postCvImgAicropErrCodes, true)
	return core.Decode[PostCvImgAicropResponse](ctx, "POST", "/cv/img/aicrop", data, err)
}

var postCvImgQrcodeErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	101000: {
		Desc:     "invalid image url",
		Solution: "图片URL错误",
	},
	101002: {
		Desc:     "invalid image data",
		Solution: "图片数据无效",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostCvImgQrcode 二维码/条码识别 (POST /cv/img/qrcode)
// Doc: https://developers.weixin.qq.com/doc/service/api/openpoc/image/api_imgqrcode.html
// PostCvImgQrcodeRequest carries the documented parameters of one API call.
type PostCvImgQrcodeRequest struct {
	// 图片URL地址
	ImgURL string `query:"img_url,omitempty"`
}

// PostCvImgQrcodeResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCvImgQrcodeResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 处理结果
	CodeResults []*PostCvImgQrcodeResponseCodeResultsObject `json:"code_results,omitempty"`
	// 图片大小
	ImgSize *PostCvImgQrcodeResponseImgSizeObject `json:"img_size,omitempty"`
}

// PostCvImgQrcodeResponseCodeResultsObject is a documented nested object.
type PostCvImgQrcodeResponseCodeResultsObject struct {
	// 码的类型
	TypeName string `json:"type_name,omitempty"`
	// 码的信息
	Data string `json:"data,omitempty"`
	// 码的坐标
	Pos map[string]any `json:"pos,omitempty"`
}

// PostCvImgQrcodeResponseImgSizeObject is a documented nested object.
type PostCvImgQrcodeResponseImgSizeObject struct {
	// 宽度
	W int64 `json:"w,omitzero"`
	// 高度
	H int64 `json:"h,omitzero"`
}

func (c *Client) PostCvImgQrcode(ctx context.Context, req *PostCvImgQrcodeRequest, file *core.Upload) (*PostCvImgQrcodeResponse, error) {
	data, err := core.CallUpload(c.EndpointClient, ctx, "/cv/img/qrcode", req, file, postCvImgQrcodeErrCodes, true)
	return core.Decode[PostCvImgQrcodeResponse](ctx, "POST", "/cv/img/qrcode", data, err)
}

var postCvOcrBankcardErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	101000: {
		Desc:     "invalid image url",
		Solution: "",
	},
	101001: {
		Desc:     "certificate not found",
		Solution: "",
	},
	101003: {
		Desc:     "not enough market quota",
		Solution: "",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostCvOcrBankcard 银行卡识别 (POST /cv/ocr/bankcard)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/openpoc/ocr/api_bankcardocr.html
// PostCvOcrBankcardRequest carries the documented parameters of one API call.
type PostCvOcrBankcardRequest struct {
	// 要检测的图片 url,传这个则不用传 img 参数。
	ImgURL string `query:"img_url,omitempty"`
}

// PostCvOcrBankcardResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCvOcrBankcardResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 银行卡号
	Number string `json:"number,omitempty"`
}

func (c *Client) PostCvOcrBankcard(ctx context.Context, req *PostCvOcrBankcardRequest, file *core.Upload) (*PostCvOcrBankcardResponse, error) {
	data, err := core.CallUpload(c.EndpointClient, ctx, "/cv/ocr/bankcard", req, file, postCvOcrBankcardErrCodes, true)
	return core.Decode[PostCvOcrBankcardResponse](ctx, "POST", "/cv/ocr/bankcard", data, err)
}

var postCvOcrBizlicenseErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	101000: {
		Desc:     "invalid image url",
		Solution: "",
	},
	101001: {
		Desc:     "certificate not found",
		Solution: "",
	},
	101002: {
		Desc:     "decode image failed",
		Solution: "图片大小超过限制,resp_type = 0: 2MB,resp_type = 1: 10MB",
	},
	101003: {
		Desc:     "not enough market quota",
		Solution: "",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostCvOcrBizlicense 营业执照识别 (POST /cv/ocr/bizlicense)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/openpoc/ocr/api_bizlicenseocr.html
// PostCvOcrBizlicenseRequest carries the documented parameters of one API call.
type PostCvOcrBizlicenseRequest struct {
	// 要检测的图片 url,传这个则不用传 img 参数。
	ImgURL string `query:"img_url,omitempty"`
}

// PostCvOcrBizlicenseResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCvOcrBizlicenseResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 注册号
	RegNum string `json:"reg_num,omitempty"`
	// 编号
	Serial string `json:"serial,omitempty"`
	// 法定代表人姓名
	LegalRepresentative string `json:"legal_representative,omitempty"`
	// 企业名称
	EnterpriseName string `json:"enterprise_name,omitempty"`
	// 组成形式
	TypeOfOrganization string `json:"type_of_organization,omitempty"`
	// 经营场所/企业住所
	Address string `json:"address,omitempty"`
	// 公司类型
	TypeOfEnterprise string `json:"type_of_enterprise,omitempty"`
	// 经营范围
	BusinessScope string `json:"business_scope,omitempty"`
	// 注册资本
	RegisteredCapital string `json:"registered_capital,omitempty"`
	// 实收资本
	PaidInCapital string `json:"paid_in_capital,omitempty"`
	// 营业期限
	ValidPeriod string `json:"valid_period,omitempty"`
	// 注册日期/成立日期
	RegisteredDate string `json:"registered_date,omitempty"`
	// 营业执照位置
	CertPosition *PostCvOcrBizlicenseResponseCertPositionObject `json:"cert_position,omitempty"`
	// 图片大小
	ImgSize *PostCvOcrBizlicenseResponseImgSizeObject `json:"img_size,omitempty"`
}

// PostCvOcrBizlicenseResponseCertPositionObject is a documented nested object.
type PostCvOcrBizlicenseResponseCertPositionObject struct {
	// 位置信息
	Pos *PostCvOcrBizlicenseResponsePosObject `json:"pos,omitempty"`
}

// PostCvOcrBizlicenseResponsePosObject is a documented nested object.
type PostCvOcrBizlicenseResponsePosObject struct {
	// 左上角位置
	LeftTop *PostCvOcrBizlicenseResponseLeftTopObject `json:"left_top,omitempty"`
	// 右上角位置
	RightTop *PostCvOcrBizlicenseResponseRightTopObject `json:"right_top,omitempty"`
	// 右下角位置
	RightBottom *PostCvOcrBizlicenseResponseRightBottomObject `json:"right_bottom,omitempty"`
	// 左下角位置
	LeftBottom *PostCvOcrBizlicenseResponseLeftBottomObject `json:"left_bottom,omitempty"`
}

// PostCvOcrBizlicenseResponseLeftTopObject is a documented nested object.
type PostCvOcrBizlicenseResponseLeftTopObject struct {
	// x坐标
	X float64 `json:"x,omitzero"`
	// y坐标
	Y float64 `json:"y,omitzero"`
}

// PostCvOcrBizlicenseResponseRightTopObject is a documented nested object.
type PostCvOcrBizlicenseResponseRightTopObject struct {
	// x坐标
	X float64 `json:"x,omitzero"`
	// y坐标
	Y float64 `json:"y,omitzero"`
}

// PostCvOcrBizlicenseResponseRightBottomObject is a documented nested object.
type PostCvOcrBizlicenseResponseRightBottomObject struct {
	// x坐标
	X float64 `json:"x,omitzero"`
	// y坐标
	Y float64 `json:"y,omitzero"`
}

// PostCvOcrBizlicenseResponseLeftBottomObject is a documented nested object.
type PostCvOcrBizlicenseResponseLeftBottomObject struct {
	// x坐标
	X float64 `json:"x,omitzero"`
	// y坐标
	Y float64 `json:"y,omitzero"`
}

// PostCvOcrBizlicenseResponseImgSizeObject is a documented nested object.
type PostCvOcrBizlicenseResponseImgSizeObject struct {
	// 宽度
	W int64 `json:"w,omitzero"`
	// 高度
	H int64 `json:"h,omitzero"`
}

func (c *Client) PostCvOcrBizlicense(ctx context.Context, req *PostCvOcrBizlicenseRequest, file *core.Upload) (*PostCvOcrBizlicenseResponse, error) {
	data, err := core.CallUpload(c.EndpointClient, ctx, "/cv/ocr/bizlicense", req, file, postCvOcrBizlicenseErrCodes, true)
	return core.Decode[PostCvOcrBizlicenseResponse](ctx, "POST", "/cv/ocr/bizlicense", data, err)
}

var postCvOcrCommErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	101000: {
		Desc:     "invalid image url",
		Solution: "",
	},
	101002: {
		Desc:     "decode image failed",
		Solution: "图片大小超过限制,resp_type = 0: 2MB,resp_type = 1: 10MB",
	},
	101003: {
		Desc:     "not enough market quota",
		Solution: "",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostCvOcrComm 通用印刷体识别 (POST /cv/ocr/comm)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/openpoc/ocr/api_commocr.html
// PostCvOcrCommRequest carries the documented parameters of one API call.
type PostCvOcrCommRequest struct {
	// 要检测的图片 url,传这个则不用传 img 参数。
	ImgURL string `query:"img_url,omitempty"`
}

// PostCvOcrCommResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCvOcrCommResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误描述
	Errmsg string `json:"errmsg,omitempty"`
	// 识别结果
	Items []*PostCvOcrCommResponseItemsObject `json:"items,omitempty"`
	// 图片大小
	ImgSize *PostCvOcrCommResponseImgSizeObject `json:"img_size,omitempty"`
}

// PostCvOcrCommResponseItemsObject is a documented nested object.
type PostCvOcrCommResponseItemsObject struct {
	// 位置信息
	Pos map[string]any `json:"pos,omitempty"`
}

// PostCvOcrCommResponseImgSizeObject is a documented nested object.
type PostCvOcrCommResponseImgSizeObject struct {
	// 宽度
	W int64 `json:"w,omitzero"`
	// 高度
	H int64 `json:"h,omitzero"`
}

func (c *Client) PostCvOcrComm(ctx context.Context, req *PostCvOcrCommRequest, file *core.Upload) (*PostCvOcrCommResponse, error) {
	data, err := core.CallUpload(c.EndpointClient, ctx, "/cv/ocr/comm", req, file, postCvOcrCommErrCodes, true)
	return core.Decode[PostCvOcrCommResponse](ctx, "POST", "/cv/ocr/comm", data, err)
}

var postCvOcrDrivingErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	101000: {
		Desc:     "invalid image url",
		Solution: "",
	},
	101003: {
		Desc:     "not enough market quota",
		Solution: "",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostCvOcrDriving 行驶证识别 (POST /cv/ocr/driving)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/openpoc/ocr/api_drivingocr.html
// PostCvOcrDrivingRequest carries the documented parameters of one API call.
type PostCvOcrDrivingRequest struct {
	// 要检测的图片 url,传这个则不用传 img 参数。
	ImgURL string `query:"img_url,omitempty"`
}

// PostCvOcrDrivingResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCvOcrDrivingResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 车牌号码
	PlateNum string `json:"plate_num,omitempty"`
	// 车辆类型
	VehicleType string `json:"vehicle_type,omitempty"`
	// 所有人
	Owner string `json:"owner,omitempty"`
	// 住址
	Addr string `json:"addr,omitempty"`
	// 使用性质
	UseCharacter string `json:"use_character,omitempty"`
	// 品牌型号
	Model string `json:"model,omitempty"`
	// 车辆识别代号
	Vin string `json:"vin,omitempty"`
	// 发动机号码
	EngineNum string `json:"engine_num,omitempty"`
	// 注册日期
	RegisterDate string `json:"register_date,omitempty"`
	// 发证日期
	IssueDate string `json:"issue_date,omitempty"`
	// 车牌号码
	PlateNumB string `json:"plate_num_b,omitempty"`
	// 号牌
	Record string `json:"record,omitempty"`
	// 核定载人数
	PassengersNum string `json:"passengers_num,omitempty"`
	// 总质量
	TotalQuality string `json:"total_quality,omitempty"`
	// 整备质量
	PrepareQuality string `json:"prepare_quality,omitempty"`
}

func (c *Client) PostCvOcrDriving(ctx context.Context, req *PostCvOcrDrivingRequest, file *core.Upload) (*PostCvOcrDrivingResponse, error) {
	data, err := core.CallUpload(c.EndpointClient, ctx, "/cv/ocr/driving", req, file, postCvOcrDrivingErrCodes, true)
	return core.Decode[PostCvOcrDrivingResponse](ctx, "POST", "/cv/ocr/driving", data, err)
}

var postCvOcrDrivinglicenseErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	101000: {
		Desc:     "invalid image url",
		Solution: "",
	},
	101003: {
		Desc:     "not enough market quota",
		Solution: "",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostCvOcrDrivinglicense 驾驶证识别 (POST /cv/ocr/drivinglicense)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/openpoc/ocr/api_drivinglicenseocr.html
// PostCvOcrDrivinglicenseRequest carries the documented parameters of one API call.
type PostCvOcrDrivinglicenseRequest struct {
	// 要检测的图片 url,传这个则不用传 img 参数。
	ImgURL string `query:"img_url,omitempty"`
}

// PostCvOcrDrivinglicenseResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCvOcrDrivinglicenseResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 证号
	IDNum string `json:"id_num,omitempty"`
	// 姓名
	Name string `json:"name,omitempty"`
	// 性别
	Sex string `json:"sex,omitempty"`
	// 地址
	Address string `json:"address,omitempty"`
	// 出生日期
	BirthDate string `json:"birth_date,omitempty"`
	// 初次领证日期
	IssueDate string `json:"issue_date,omitempty"`
	// 准驾车型
	CarClass string `json:"car_class,omitempty"`
	// 有效期限起始日
	ValidFrom string `json:"valid_from,omitempty"`
	// 有效期限终止日
	ValidTo string `json:"valid_to,omitempty"`
	// 印章文构
	OfficialSeal string `json:"official_seal,omitempty"`
}

func (c *Client) PostCvOcrDrivinglicense(ctx context.Context, req *PostCvOcrDrivinglicenseRequest, file *core.Upload) (*PostCvOcrDrivinglicenseResponse, error) {
	data, err := core.CallUpload(c.EndpointClient, ctx, "/cv/ocr/drivinglicense", req, file, postCvOcrDrivinglicenseErrCodes, true)
	return core.Decode[PostCvOcrDrivinglicenseResponse](ctx, "POST", "/cv/ocr/drivinglicense", data, err)
}

var postCvOcrIdcardErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	101000: {
		Desc:     "invalid image url",
		Solution: "图片URL错误",
	},
	101001: {
		Desc:     "certificate not found",
		Solution: "未检测到证件",
	},
	101002: {
		Desc:     "decode image failed",
		Solution: "图片大小超过限制,resp_type = 0: 2MB,resp_type = 1: 10MB",
	},
	101003: {
		Desc:     "not enough market quota",
		Solution: "",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostCvOcrIdcard 身份证识别 (POST /cv/ocr/idcard)
// Doc: https://developers.weixin.qq.com/doc/service/api/openpoc/ocr/api_idcardocr.html
// PostCvOcrIdcardRequest carries the documented parameters of one API call.
type PostCvOcrIdcardRequest struct {
	// 要检测的图片 url,传这个则不用传 img 参数。
	ImgURL string `query:"img_url,omitempty"`
}

// PostCvOcrIdcardResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCvOcrIdcardResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 正面或背面,Front / Back
	Type string `json:"type,omitempty"`
	// 正面返回,姓名
	Name string `json:"name,omitempty"`
	// 正面返回,身份证号
	ID string `json:"id,omitempty"`
	// 背面返回,有效期
	ValidDate string `json:"valid_date,omitempty"`
	// 正面返回,地址
	Addr string `json:"addr,omitempty"`
	// 正面返回,性别
	Gender string `json:"gender,omitempty"`
	// 正面返回,民族
	Nationality string `json:"nationality,omitempty"`
}

func (c *Client) PostCvOcrIdcard(ctx context.Context, req *PostCvOcrIdcardRequest, file *core.Upload) (*PostCvOcrIdcardResponse, error) {
	data, err := core.CallUpload(c.EndpointClient, ctx, "/cv/ocr/idcard", req, file, postCvOcrIdcardErrCodes, true)
	return core.Decode[PostCvOcrIdcardResponse](ctx, "POST", "/cv/ocr/idcard", data, err)
}

var postCvOcrMenuErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	101000: {
		Desc:     "invalid image url",
		Solution: "",
	},
	101001: {
		Desc:     "certificate not found",
		Solution: "",
	},
	101002: {
		Desc:     "decode image failed",
		Solution: "图片大小超过限制,resp_type = 0: 2MB,resp_type = 1: 10MB",
	},
}

// PostCvOcrMenu 菜单识别 (POST /cv/ocr/menu)
// Doc: https://developers.weixin.qq.com/doc/service/api/openpoc/ocr/api_menuocr.html
// PostCvOcrMenuRequest carries the documented parameters of one API call.
type PostCvOcrMenuRequest struct {
	// 要检测的图片 url,传这个则不用传 img 参数。
	ImgURL string `query:"img_url,omitempty"`
}

// PostCvOcrMenuResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCvOcrMenuResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 识别的信息
	Content *PostCvOcrMenuResponseContentObject `json:"content,omitempty"`
}

// PostCvOcrMenuResponseContentObject is a documented nested object.
type PostCvOcrMenuResponseContentObject struct {
	// 菜单内容列表
	MenuItems []*PostCvOcrMenuResponseMenuItemsObject `json:"menu_items,omitempty"`
}

// PostCvOcrMenuResponseMenuItemsObject is a documented nested object.
type PostCvOcrMenuResponseMenuItemsObject struct {
	// 菜单名
	Name string `json:"name,omitempty"`
	// 价格
	Price int64 `json:"price,omitzero"`
}

func (c *Client) PostCvOcrMenu(ctx context.Context, req *PostCvOcrMenuRequest, file *core.Upload) (*PostCvOcrMenuResponse, error) {
	data, err := core.CallUpload(c.EndpointClient, ctx, "/cv/ocr/menu", req, file, postCvOcrMenuErrCodes, true)
	return core.Decode[PostCvOcrMenuResponse](ctx, "POST", "/cv/ocr/menu", data, err)
}
