// Code generated by docsync from the official WeChat documentation. DO NOT EDIT.
// The API surface (names, request/response shapes) is derived deterministically
// from the endpoints; regenerate with "make docs-sync". If this file changes
// under you, the upstream documentation changed.

package official

import (
	"context"
	"github.com/go-sphere/weixin-api/core"
)

var getSnsAuthErrCodes = map[int]core.ErrDoc{40003: {
	Desc:     "invalid openid",
	Solution: "不合法的 OpenID ,请开发者确认 OpenID (该用户)是否已关注公众号,或是否是其他公众号的 OpenID",
}}

// GetSnsAuth 检验用户授权凭证 (GET /sns/auth)
// Doc: https://developers.weixin.qq.com/doc/service/api/webdev/access/api_snsauth.html
// GetSnsAuthRequest carries the documented parameters of one API call.
type GetSnsAuthRequest struct {
	// 接口调用凭证,可使用 access_token
	AccessToken string `query:"access_token"`
	// 用户的唯一标识
	OpenID string `query:"openid"`
}

// GetSnsAuthResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type GetSnsAuthResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误描述
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) GetSnsAuth(ctx context.Context, req *GetSnsAuthRequest) (*GetSnsAuthResponse, error) {
	return core.Call[GetSnsAuthResponse](c.EndpointClient, ctx, "GET", "/sns/auth", req, getSnsAuthErrCodes, false, core.SignNone)
}

var getSnsOauth2AccessTokenErrCodes = map[int]core.ErrDoc{40029: {
	Desc:     "invalid code",
	Solution: "无效的code参数",
}}

// GetSnsOauth2AccessToken 换取用户授权凭证 (GET /sns/oauth2/access_token)
// Doc: https://developers.weixin.qq.com/doc/service/api/webdev/access/api_snsaccesstoken.html
// GetSnsOauth2AccessTokenRequest carries the documented parameters of one API call.
type GetSnsOauth2AccessTokenRequest struct {
	// 公众号的唯一标识
	AppID string `query:"appid"`
	// 公众号的 appsecret
	Secret string `query:"secret"`
	// 填写第一步获取的 code 参数
	Code string `query:"code"`
	// 填写为 authorization_code
	GrantType string `query:"grant_type"`
}

// GetSnsOauth2AccessTokenResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type GetSnsOauth2AccessTokenResponse struct {
	// 网页授权接口调用凭证,注意:此access_token与基础支持的access_token不同
	AccessToken string `json:"access_token,omitempty"`
	// access_token接口调用凭证超时时间,单位(秒)
	ExpiresIn int64 `json:"expires_in,omitzero"`
	// 用户刷新access_token
	RefreshToken string `json:"refresh_token,omitempty"`
	// 用户唯一标识,请注意,在未关注公众号时,用户访问公众号的网页,也会产生一个用户和公众号唯一的OpenID
	OpenID string `json:"openid,omitempty"`
	// 用户统一标识(针对一个微信开放平台账号下的应用,同一用户的 unionid 是唯一的),只有当scope为"snsapi_userinfo"时返回
	UnionID string `json:"unionid,omitempty"`
	// 是否为快照页模式虚拟账号,只有当用户是快照页模式虚拟账号时返回,值为1
	IsSnapshotuser int64 `json:"is_snapshotuser,omitzero"`
}

func (c *Client) GetSnsOauth2AccessToken(ctx context.Context, req *GetSnsOauth2AccessTokenRequest) (*GetSnsOauth2AccessTokenResponse, error) {
	return core.Call[GetSnsOauth2AccessTokenResponse](c.EndpointClient, ctx, "GET", "/sns/oauth2/access_token", req, getSnsOauth2AccessTokenErrCodes, false, core.SignNone)
}

var getSnsOauth2RefreshTokenErrCodes = map[int]core.ErrDoc{40029: {
	Desc:     "code 无效",
	Solution: "js_code无效",
}}

// GetSnsOauth2RefreshToken 刷新用户授权凭证 (GET /sns/oauth2/refresh_token)
// Doc: https://developers.weixin.qq.com/doc/service/api/webdev/access/api_snsrefreshtoken.html
// GetSnsOauth2RefreshTokenRequest carries the documented parameters of one API call.
type GetSnsOauth2RefreshTokenRequest struct {
	// 公众号的唯一标识
	AppID string `query:"appid"`
	// 填写为refresh_token
	GrantType string `query:"grant_type"`
	// 填写通过access_token获取到的refresh_token参数
	RefreshToken string `query:"refresh_token"`
}

// GetSnsOauth2RefreshTokenResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type GetSnsOauth2RefreshTokenResponse struct {
	// 网页授权接口调用凭证,注意:此access_token与基础支持的access_token不同
	AccessToken string `json:"access_token,omitempty"`
	// access_token接口调用凭证超时时间,单位(秒)
	ExpiresIn int64 `json:"expires_in,omitzero"`
	// 用户刷新access_token
	RefreshToken string `json:"refresh_token,omitempty"`
	// 用户唯一标识
	OpenID string `json:"openid,omitempty"`
	// 用户授权的作用域,使用逗号(,)分隔
	Scope string `json:"scope,omitempty"`
}

func (c *Client) GetSnsOauth2RefreshToken(ctx context.Context, req *GetSnsOauth2RefreshTokenRequest) (*GetSnsOauth2RefreshTokenResponse, error) {
	return core.Call[GetSnsOauth2RefreshTokenResponse](c.EndpointClient, ctx, "GET", "/sns/oauth2/refresh_token", req, getSnsOauth2RefreshTokenErrCodes, false, core.SignNone)
}

var getSnsUserinfoErrCodes = map[int]core.ErrDoc{40003: {
	Desc:     "invalid openid",
	Solution: "不合法的 OpenID ,请开发者确认 OpenID (该用户)是否已关注公众号,或是否是其他公众号的 OpenID",
}}

// GetSnsUserinfo 获取授权用户信息 (GET /sns/userinfo)
// Doc: https://developers.weixin.qq.com/doc/service/api/webdev/access/api_snsuserinfo.html
// GetSnsUserinfoRequest carries the documented parameters of one API call.
type GetSnsUserinfoRequest struct {
	// 接口调用凭证,可使用 access_token
	AccessToken string `query:"access_token"`
	// 用户的唯一标识
	OpenID string `query:"openid"`
	// 返回国家地区语言版本,zh_CN 简体,zh_TW 繁体,en 英语
	Lang string `query:"lang,omitempty"`
}

// GetSnsUserinfoResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type GetSnsUserinfoResponse struct {
	// 用户的唯一标识
	OpenID string `json:"openid,omitempty"`
	// 用户昵称
	Nickname string `json:"nickname,omitempty"`
	// 用户的性别,值为1时是男性,值为2时是女性,值为0时是未知
	Sex int64 `json:"sex,omitzero"`
	// 用户头像,最后一个数值代表正方形头像大小(有0、46、64、96、132数值可选,0代表640*640正方形头像),用户没有头像时该项为空。若用户更换头像,原有头像URL将失效。
	Headimgurl string `json:"headimgurl,omitempty"`
	// 只有在管理员将公众号绑定到微信开放平台账号后,才会出现该字段。
	UnionID string `json:"unionid,omitempty"`
	// 用户个人资料填写的省份
	Province string `json:"province,omitempty"`
	// 普通用户个人资料填写的城市
	City string `json:"city,omitempty"`
	// 国家,如中国为CN
	Country string `json:"country,omitempty"`
	// 用户特权信息,json 数组,如微信沃卡用户为(chinaunicom)
	Privilege []string `json:"privilege,omitempty"`
}

func (c *Client) GetSnsUserinfo(ctx context.Context, req *GetSnsUserinfoRequest) (*GetSnsUserinfoResponse, error) {
	return core.Call[GetSnsUserinfoResponse](c.EndpointClient, ctx, "GET", "/sns/userinfo", req, getSnsUserinfoErrCodes, false, core.SignNone)
}
