// Code generated by docsync from the official WeChat documentation. DO NOT EDIT.
// The API surface (names, request/response shapes) is derived deterministically
// from the endpoints; regenerate with "make docs-sync". If this file changes
// under you, the upstream documentation changed.

package official

import (
	"context"
	"github.com/go-sphere/weixin-api/core"
)

var postDatacubeGetarticlereadErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	0: {
		Desc:     "ok",
		Solution: "成功",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "日期范围超过接口限制",
	},
}

// PostDatacubeGetarticleread 获取发表内容每日阅读数据 (POST /datacube/getarticleread)
// Doc: https://developers.weixin.qq.com/doc/service/api/wedata/news/api_getarticleread.html
// PostDatacubeGetarticlereadRequest carries the documented parameters of one API call.
type PostDatacubeGetarticlereadRequest struct {
	// 起始日期(YYYY-MM-DD)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大值为昨日)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetarticlereadResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetarticlereadResponse struct {
	// 日期内文章数据列表
	List []*PostDatacubeGetarticlereadResponseListObject `json:"list,omitempty"`
	// 数据是否有延迟,is_delay=false表示数据是最新的
	IsDelay bool `json:"is_delay,omitzero"`
}

// PostDatacubeGetarticlereadResponseListObject is a documented nested object.
type PostDatacubeGetarticlereadResponseListObject struct {
	// 统计日期
	RefDate string `json:"ref_date,omitempty"`
	// 请注意:这里的msgid实际上是由msgid(图文消息id,这也就是群发/发布接口调用后返回的msg_data_id)和index(消息次序索引)组成, 例如12003_3, 其中12003是msgid,即一次群发/发布的消息的id; 3为index,假设该次群发/发布的图文消息共5个文章(因为可能为多图文),3表示5个中的第3个
	Msgid string `json:"msgid,omitempty"`
	// 每篇文章的详细数据
	Detail map[string]any `json:"detail,omitempty"`
}

func (c *Client) PostDatacubeGetarticleread(ctx context.Context, req *PostDatacubeGetarticlereadRequest) (*PostDatacubeGetarticlereadResponse, error) {
	return core.Call[PostDatacubeGetarticlereadResponse](c.EndpointClient, ctx, "POST", "/datacube/getarticleread", req, postDatacubeGetarticlereadErrCodes, true, core.SignNone)
}

var postDatacubeGetarticleshareErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	0: {
		Desc:     "ok",
		Solution: "成功",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "日期范围超过接口限制",
	},
}

// PostDatacubeGetarticleshare 获取发表内容每日分享数据 (POST /datacube/getarticleshare)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/wedata/news/api_getarticleshare.html
// PostDatacubeGetarticleshareRequest carries the documented parameters of one API call.
type PostDatacubeGetarticleshareRequest struct {
	// 起始日期(YYYY-MM-DD)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大值为昨日)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetarticleshareResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetarticleshareResponse struct {
	// 日期内文章数据列表
	List []*PostDatacubeGetarticleshareResponseListObject `json:"list,omitempty"`
	// 数据是否有延迟,is_delay=false表示数据是最新的
	IsDelay bool `json:"is_delay,omitzero"`
}

// PostDatacubeGetarticleshareResponseListObject is a documented nested object.
type PostDatacubeGetarticleshareResponseListObject struct {
	// 统计日期
	RefDate string `json:"ref_date,omitempty"`
	// 请注意:这里的msgid实际上是由msgid(图文消息id,这也就是群发/发布接口调用后返回的msg_data_id)和index(消息次序索引)组成, 例如12003_3, 其中12003是msgid,即一次群发/发布的消息的id; 3为index,假设该次群发/发布的图文消息共5个文章(因为可能为多图文),3表示5个中的第3个
	Msgid string `json:"msgid,omitempty"`
	// 每篇文章的详细数据
	Detail map[string]any `json:"detail,omitempty"`
}

func (c *Client) PostDatacubeGetarticleshare(ctx context.Context, req *PostDatacubeGetarticleshareRequest) (*PostDatacubeGetarticleshareResponse, error) {
	return core.Call[PostDatacubeGetarticleshareResponse](c.EndpointClient, ctx, "POST", "/datacube/getarticleshare", req, postDatacubeGetarticleshareErrCodes, true, core.SignNone)
}

var postDatacubeGetarticlesummaryErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	0: {
		Desc:     "ok",
		Solution: "成功",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date range error",
		Solution: "日期范围超过接口限制",
	},
}

// PostDatacubeGetarticlesummary 获取图文群发每日数据 (POST /datacube/getarticlesummary)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/wedata/news/api_getarticlesummary.html
// PostDatacubeGetarticlesummaryRequest carries the documented parameters of one API call.
type PostDatacubeGetarticlesummaryRequest struct {
	// 起始日期(YYYY-MM-DD)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大值为昨日)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetarticlesummaryResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetarticlesummaryResponse struct {
	// 该日期内所有被阅读过的文章(仅包括群发的文章)数据
	List []*PostDatacubeGetarticlesummaryResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetarticlesummaryResponseListObject is a documented nested object.
type PostDatacubeGetarticlesummaryResponseListObject struct {
	// 数据的日期,需在begin_date和end_date之间
	RefDate string `json:"ref_date,omitempty"`
	// 请注意:这里的msgid实际上是由msgid(图文消息id,这也就是群发接口调用后返回的msg_data_id)和index(消息次序索引)组成, 例如12003_3, 其中12003是msgid,即一次群发的消息的id; 3为index,假设该次群发的图文消息共5个文章(因为可能为多图文),3表示5个中的第3个
	Msgid string `json:"msgid,omitempty"`
	// 图文消息的标题
	Title string `json:"title,omitempty"`
	// 图文页(点击群发图文卡片进入的页面)的阅读人数
	IntPageReadUser int64 `json:"int_page_read_user,omitzero"`
	// 图文页的阅读次数
	IntPageReadCount int64 `json:"int_page_read_count,omitzero"`
	// 原文页(点击图文页"阅读原文"进入的页面)的阅读人数,无原文页时此处数据为0
	OriPageReadUser int64 `json:"ori_page_read_user,omitzero"`
	// 原文页的阅读次数
	OriPageReadCount int64 `json:"ori_page_read_count,omitzero"`
	// 分享的人数
	ShareUser int64 `json:"share_user,omitzero"`
	// 分享的次数
	ShareCount int64 `json:"share_count,omitzero"`
	// 收藏的人数
	AddToFavUser int64 `json:"add_to_fav_user,omitzero"`
	// 收藏的次数
	AddToFavCount int64 `json:"add_to_fav_count,omitzero"`
}

func (c *Client) PostDatacubeGetarticlesummary(ctx context.Context, req *PostDatacubeGetarticlesummaryRequest) (*PostDatacubeGetarticlesummaryResponse, error) {
	return core.Call[PostDatacubeGetarticlesummaryResponse](c.EndpointClient, ctx, "POST", "/datacube/getarticlesummary", req, postDatacubeGetarticlesummaryErrCodes, true, core.SignNone)
}

var postDatacubeGetarticletotalErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostDatacubeGetarticletotal 获取图文群发总数据 (POST /datacube/getarticletotal)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/wedata/news/api_getarticletotal.html
// PostDatacubeGetarticletotalRequest carries the documented parameters of one API call.
type PostDatacubeGetarticletotalRequest struct {
	// 起始日期(YYYY-MM-DD)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大值为昨日)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetarticletotalResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetarticletotalResponse struct {
	// 数据列表
	List []*PostDatacubeGetarticletotalResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetarticletotalResponseListObject is a documented nested object.
type PostDatacubeGetarticletotalResponseListObject struct {
	// 统计的日期,在getarticletotal接口中,ref_date指的是文章群发出日期, 而stat_date是数据统计日期
	StatDate string `json:"stat_date,omitempty"`
	// 送达人数,一般约等于总粉丝数(需排除黑名单或其他异常情况下无法收到消息的粉丝)
	TargetUser int64 `json:"target_user,omitzero"`
	// 图文页(点击群发图文卡片进入的页面)的阅读人数
	IntPageReadUser int64 `json:"int_page_read_user,omitzero"`
	// 图文页的阅读次数
	IntPageReadCount int64 `json:"int_page_read_count,omitzero"`
	// 原文页(点击图文页"阅读原文"进入的页面)的阅读人数,无原文页时此处数据为0
	OriPageReadUser int64 `json:"ori_page_read_user,omitzero"`
	// 原文页的阅读次数
	OriPageReadCount int64 `json:"ori_page_read_count,omitzero"`
	// 分享的人数
	ShareUser int64 `json:"share_user,omitzero"`
	// 分享的次数
	ShareCount int64 `json:"share_count,omitzero"`
	// 收藏的人数
	AddToFavUser int64 `json:"add_to_fav_user,omitzero"`
	// 收藏的次数
	AddToFavCount int64 `json:"add_to_fav_count,omitzero"`
	// 公众号会话阅读人数
	IntPageFromSessionReadUser int64 `json:"int_page_from_session_read_user,omitzero"`
	// 公众号会话阅读次数
	IntPageFromSessionReadCount int64 `json:"int_page_from_session_read_count,omitzero"`
	// 历史消息页阅读人数
	IntPageFromHistMsgReadUser int64 `json:"int_page_from_hist_msg_read_user,omitzero"`
	// 历史消息页阅读次数
	IntPageFromHistMsgReadCount int64 `json:"int_page_from_hist_msg_read_count,omitzero"`
	// 朋友圈阅读人数
	IntPageFromFeedReadUser int64 `json:"int_page_from_feed_read_user,omitzero"`
	// 朋友圈阅读次数;
	IntPageFromFeedReadCount int64 `json:"int_page_from_feed_read_count,omitzero"`
	// 好友转发阅读人数
	IntPageFromFriendsReadUser int64 `json:"int_page_from_friends_read_user,omitzero"`
	// 好友转发阅读次数
	IntPageFromFriendsReadCount int64 `json:"int_page_from_friends_read_count,omitzero"`
	// 其他场景阅读人数
	IntPageFromOtherReadUser int64 `json:"int_page_from_other_read_user,omitzero"`
	// 其他场景阅读次数
	IntPageFromOtherReadCount int64 `json:"int_page_from_other_read_count,omitzero"`
	// 公众号会话转发朋友圈人数
	FeedShareFromSessionUser int64 `json:"feed_share_from_session_user,omitzero"`
	// 公众号会话转发朋友圈次数
	FeedShareFromSessionCnt int64 `json:"feed_share_from_session_cnt,omitzero"`
	// 朋友圈转发朋友圈人数
	FeedShareFromFeedUser int64 `json:"feed_share_from_feed_user,omitzero"`
	// 朋友圈转发朋友圈次数
	FeedShareFromFeedCnt int64 `json:"feed_share_from_feed_cnt,omitzero"`
	// 其他场景转发朋友圈人数
	FeedShareFromOtherUser int64 `json:"feed_share_from_other_user,omitzero"`
	// 其他场景转发朋友圈次数
	FeedShareFromOtherCnt int64 `json:"feed_share_from_other_cnt,omitzero"`
	// 看一看来源阅读人数
	IntPageFromKanyikanReadUser int64 `json:"int_page_from_kanyikan_read_user,omitzero"`
	// 看一看来源阅读次数
	IntPageFromKanyikanReadCount int64 `json:"int_page_from_kanyikan_read_count,omitzero"`
	// 搜一搜来源阅读人数
	IntPageFromSouyisouReadUser int64 `json:"int_page_from_souyisou_read_user,omitzero"`
	// 搜一搜来源阅读次数
	IntPageFromSouyisouReadCount int64 `json:"int_page_from_souyisou_read_count,omitzero"`
}

func (c *Client) PostDatacubeGetarticletotal(ctx context.Context, req *PostDatacubeGetarticletotalRequest) (*PostDatacubeGetarticletotalResponse, error) {
	return core.Call[PostDatacubeGetarticletotalResponse](c.EndpointClient, ctx, "POST", "/datacube/getarticletotal", req, postDatacubeGetarticletotalErrCodes, true, core.SignNone)
}

var postDatacubeGetarticletotaldetailErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	0: {
		Desc:     "ok",
		Solution: "成功",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "日期范围超过接口限制",
	},
}

// PostDatacubeGetarticletotaldetail 获取发表内容发表详细数据 (POST /datacube/getarticletotaldetail)
// Doc: https://developers.weixin.qq.com/doc/service/api/wedata/news/api_getarticletotaldetail.html
// PostDatacubeGetarticletotaldetailRequest carries the documented parameters of one API call.
type PostDatacubeGetarticletotaldetailRequest struct {
	// 起始日期(YYYY-MM-DD)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大值为昨日)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetarticletotaldetailResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetarticletotaldetailResponse struct {
	// 日期内文章数据列表
	List []*PostDatacubeGetarticletotaldetailResponseListObject `json:"list,omitempty"`
	// 数据是否有延迟,is_delay=false表示数据是最新的
	IsDelay bool `json:"is_delay,omitzero"`
}

// PostDatacubeGetarticletotaldetailResponseListObject is a documented nested object.
type PostDatacubeGetarticletotaldetailResponseListObject struct {
	// 文章发表日期
	RefDate string `json:"ref_date,omitempty"`
	// 请注意:这里的msgid实际上是由msg_data_id(消息数据id,这也就是群发/发布接口调用后返回的msg_data_id)和index(消息次序索引)组成, 例如12003_3, 其中12003是msg_data_id,即一次群发/发布的消息数据的id; 3为index,假设该次群发/发布的图文消息共5个文章(因为可能为多图文),3表示5个中的第3个
	Msgid string `json:"msgid,omitempty"`
	// 发表类型,0.已通知; 1.未开启通知;
	PublishType int64 `json:"publish_type,omitzero"`
	// 每篇文章的详细数据
	DetailList []map[string]any `json:"detail_list,omitempty"`
	// 文章标题
	Title string `json:"title,omitempty"`
	// 文章链接
	ContentURL string `json:"content_url,omitempty"`
}

func (c *Client) PostDatacubeGetarticletotaldetail(ctx context.Context, req *PostDatacubeGetarticletotaldetailRequest) (*PostDatacubeGetarticletotaldetailResponse, error) {
	return core.Call[PostDatacubeGetarticletotaldetailResponse](c.EndpointClient, ctx, "POST", "/datacube/getarticletotaldetail", req, postDatacubeGetarticletotaldetailErrCodes, true, core.SignNone)
}

var postDatacubeGetbizsummaryErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	0: {
		Desc:     "ok",
		Solution: "成功",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "日期范围超过接口限制",
	},
}

// PostDatacubeGetbizsummary 获取发表内容概况总数据 (POST /datacube/getbizsummary)
// Doc: https://developers.weixin.qq.com/doc/service/api/wedata/news/api_getbizsummary.html
// PostDatacubeGetbizsummaryRequest carries the documented parameters of one API call.
type PostDatacubeGetbizsummaryRequest struct {
	// 起始日期(YYYY-MM-DD)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大值为昨日)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetbizsummaryResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetbizsummaryResponse struct {
	// 日期内文章数据列表
	List []*PostDatacubeGetbizsummaryResponseListObject `json:"list,omitempty"`
	// 数据是否有延迟,is_delay=false表示数据是最新的
	IsDelay bool `json:"is_delay,omitzero"`
}

// PostDatacubeGetbizsummaryResponseListObject is a documented nested object.
type PostDatacubeGetbizsummaryResponseListObject struct {
	// 统计日期
	RefDate string `json:"ref_date,omitempty"`
	// 每篇文章的详细数据
	Detail map[string]any `json:"detail,omitempty"`
}

func (c *Client) PostDatacubeGetbizsummary(ctx context.Context, req *PostDatacubeGetbizsummaryRequest) (*PostDatacubeGetbizsummaryResponse, error) {
	return core.Call[PostDatacubeGetbizsummaryResponse](c.EndpointClient, ctx, "POST", "/datacube/getbizsummary", req, postDatacubeGetbizsummaryErrCodes, true, core.SignNone)
}

var postDatacubeGetinterfacesummaryErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "begin_date和end_date差值超过最大跨度",
	},
	61503: {
		Desc:     "data not ready please try later",
		Solution: "数据尚未生成",
	},
}

// PostDatacubeGetinterfacesummary 获取被动回复概要数据 (POST /datacube/getinterfacesummary)
// Doc: https://developers.weixin.qq.com/doc/service/api/wedata/api/api_getinterfacesummary.html
// PostDatacubeGetinterfacesummaryRequest carries the documented parameters of one API call.
type PostDatacubeGetinterfacesummaryRequest struct {
	// 起始日期(YYYY-MM-DD格式)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大时间跨度30天)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetinterfacesummaryResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetinterfacesummaryResponse struct {
	// 数据列表
	List *PostDatacubeGetinterfacesummaryResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetinterfacesummaryResponseListObject is a documented nested object.
type PostDatacubeGetinterfacesummaryResponseListObject struct {
	// 数据的日期
	RefDate string `json:"ref_date,omitempty"`
	// 通过服务器配置地址获得消息后,被动回复用户消息的次数
	CallbackCount int64 `json:"callback_count,omitzero"`
	// 上述动作的失败次数
	FailCount int64 `json:"fail_count,omitzero"`
	// 总耗时,除以callback_count即为平均耗时
	TotalTimeCost int64 `json:"total_time_cost,omitzero"`
	// 最大耗时
	MaxTimeCost int64 `json:"max_time_cost,omitzero"`
}

func (c *Client) PostDatacubeGetinterfacesummary(ctx context.Context, req *PostDatacubeGetinterfacesummaryRequest) (*PostDatacubeGetinterfacesummaryResponse, error) {
	return core.Call[PostDatacubeGetinterfacesummaryResponse](c.EndpointClient, ctx, "POST", "/datacube/getinterfacesummary", req, postDatacubeGetinterfacesummaryErrCodes, true, core.SignNone)
}

var postDatacubeGetinterfacesummaryhourErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "begin_date和end_date差值超过最大跨度",
	},
	61503: {
		Desc:     "data not ready please try later",
		Solution: "数据尚未生成",
	},
}

// PostDatacubeGetinterfacesummaryhour 获取被动回复分布数据 (POST /datacube/getinterfacesummaryhour)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/wedata/api/api_getinterfacesummaryhour.html
// PostDatacubeGetinterfacesummaryhourRequest carries the documented parameters of one API call.
type PostDatacubeGetinterfacesummaryhourRequest struct{}

// PostDatacubeGetinterfacesummaryhourResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetinterfacesummaryhourResponse struct {
	// 数据列表
	List *PostDatacubeGetinterfacesummaryhourResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetinterfacesummaryhourResponseListObject is a documented nested object.
type PostDatacubeGetinterfacesummaryhourResponseListObject struct {
	// 数据的日期
	RefDate string `json:"ref_date,omitempty"`
	// 数据的小时
	RefHour int64 `json:"ref_hour,omitzero"`
	// 通过服务器配置地址获得消息后,被动回复用户消息的次数
	CallbackCount int64 `json:"callback_count,omitzero"`
	// 上述动作的失败次数
	FailCount int64 `json:"fail_count,omitzero"`
	// 总耗时,除以callback_count即为平均耗时
	TotalTimeCost int64 `json:"total_time_cost,omitzero"`
	// 最大耗时
	MaxTimeCost int64 `json:"max_time_cost,omitzero"`
}

func (c *Client) PostDatacubeGetinterfacesummaryhour(ctx context.Context, req *PostDatacubeGetinterfacesummaryhourRequest) (*PostDatacubeGetinterfacesummaryhourResponse, error) {
	return core.Call[PostDatacubeGetinterfacesummaryhourResponse](c.EndpointClient, ctx, "POST", "/datacube/getinterfacesummaryhour", req, postDatacubeGetinterfacesummaryhourErrCodes, true, core.SignNone)
}

var postDatacubeGetupstreammsgErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "时间跨度超过最大限制",
	},
	61503: {
		Desc:     "data not ready please try later",
		Solution: "未完成数据统计处理",
	},
}

// PostDatacubeGetupstreammsg 获取消息发送概况数据 (POST /datacube/getupstreammsg)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/wedata/mess/api_getupstreammsg.html
// PostDatacubeGetupstreammsgRequest carries the documented parameters of one API call.
type PostDatacubeGetupstreammsgRequest struct {
	// 起始日期(格式: yyyy-MM-dd),与end_date差值小于7天
	BeginDate string `json:"begin_date"`
	// 结束日期(最大值为昨日)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetupstreammsgResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetupstreammsgResponse struct {
	// 数据列表
	List []*PostDatacubeGetupstreammsgResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetupstreammsgResponseListObject is a documented nested object.
type PostDatacubeGetupstreammsgResponseListObject struct {
	// 数据的日期,需在begin_date和end_date之间
	RefDate string `json:"ref_date,omitempty"`
	// 消息类型,代表含义如下: 1代表文字 2代表图片 3代表语音 4代表视频 6代表第三方应用消息(链接消息)
	MsgType int64 `json:"msg_type,omitzero"`
	// 上行发送了(向公众号发送了)消息的用户数
	MsgUser int64 `json:"msg_user,omitzero"`
	// 上行发送了消息的消息总数
	MsgCount int64 `json:"msg_count,omitzero"`
}

func (c *Client) PostDatacubeGetupstreammsg(ctx context.Context, req *PostDatacubeGetupstreammsgRequest) (*PostDatacubeGetupstreammsgResponse, error) {
	return core.Call[PostDatacubeGetupstreammsgResponse](c.EndpointClient, ctx, "POST", "/datacube/getupstreammsg", req, postDatacubeGetupstreammsgErrCodes, true, core.SignNone)
}

var postDatacubeGetupstreammsgdistErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "时间跨度超过最大限制",
	},
	61503: {
		Desc:     "data not ready please try later",
		Solution: "未完成数据统计处理",
	},
}

// PostDatacubeGetupstreammsgdist 获取消息发送分布数据 (POST /datacube/getupstreammsgdist)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/wedata/mess/api_getupstreammsgdist.html
// PostDatacubeGetupstreammsgdistRequest carries the documented parameters of one API call.
type PostDatacubeGetupstreammsgdistRequest struct {
	// 起始日期(格式: yyyy-MM-dd),跨度不超过15天
	BeginDate string `json:"begin_date"`
	// 结束日期
	EndDate string `json:"end_date"`
}

// PostDatacubeGetupstreammsgdistResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetupstreammsgdistResponse struct {
	// 数据列表
	List *PostDatacubeGetupstreammsgdistResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetupstreammsgdistResponseListObject is a documented nested object.
type PostDatacubeGetupstreammsgdistResponseListObject struct {
	// 数据的日期,需在begin_date和end_date之间
	RefDate string `json:"ref_date,omitempty"`
	// 当日发送消息量分布的区间,0代表 "0",1代表"1-5",2代表"6-10",3代表"10次以上"
	CountInterval int64 `json:"count_interval,omitzero"`
	// 上行发送了(向公众号发送了)消息的用户数
	MsgUser int64 `json:"msg_user,omitzero"`
}

func (c *Client) PostDatacubeGetupstreammsgdist(ctx context.Context, req *PostDatacubeGetupstreammsgdistRequest) (*PostDatacubeGetupstreammsgdistResponse, error) {
	return core.Call[PostDatacubeGetupstreammsgdistResponse](c.EndpointClient, ctx, "POST", "/datacube/getupstreammsgdist", req, postDatacubeGetupstreammsgdistErrCodes, true, core.SignNone)
}

var postDatacubeGetupstreammsgdistmonthErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "时间跨度超过最大限制",
	},
	61503: {
		Desc:     "data not ready please try later",
		Solution: "未完成数据统计处理",
	},
}

// PostDatacubeGetupstreammsgdistmonth 获取消息发送分布月数据 (POST /datacube/getupstreammsgdistmonth)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/wedata/mess/api_getupstreammsgdistmonth.html
// PostDatacubeGetupstreammsgdistmonthRequest carries the documented parameters of one API call.
type PostDatacubeGetupstreammsgdistmonthRequest struct {
	// 起始日期(格式: yyyy-MM-dd),跨度不超过15天
	BeginDate string `json:"begin_date"`
	// 结束日期
	EndDate string `json:"end_date"`
}

// PostDatacubeGetupstreammsgdistmonthResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetupstreammsgdistmonthResponse struct {
	// 数据列表
	List *PostDatacubeGetupstreammsgdistmonthResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetupstreammsgdistmonthResponseListObject is a documented nested object.
type PostDatacubeGetupstreammsgdistmonthResponseListObject struct {
	// 数据的日期,需在begin_date和end_date之间
	RefDate string `json:"ref_date,omitempty"`
	// 当日发送消息量分布的区间,0代表 "0",1代表"1-5",2代表"6-10",3代表"10次以上"
	CountInterval int64 `json:"count_interval,omitzero"`
	// 上行发送了(向公众号发送了)消息的用户数
	MsgUser int64 `json:"msg_user,omitzero"`
}

func (c *Client) PostDatacubeGetupstreammsgdistmonth(ctx context.Context, req *PostDatacubeGetupstreammsgdistmonthRequest) (*PostDatacubeGetupstreammsgdistmonthResponse, error) {
	return core.Call[PostDatacubeGetupstreammsgdistmonthResponse](c.EndpointClient, ctx, "POST", "/datacube/getupstreammsgdistmonth", req, postDatacubeGetupstreammsgdistmonthErrCodes, true, core.SignNone)
}

var postDatacubeGetupstreammsgdistweekErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "时间跨度超过最大限制",
	},
	61503: {
		Desc:     "data not ready please try later",
		Solution: "未完成数据统计处理",
	},
}

// PostDatacubeGetupstreammsgdistweek 获取消息发送分布周数据 (POST /datacube/getupstreammsgdistweek)
// Doc: https://developers.weixin.qq.com/doc/service/api/wedata/mess/api_getupstreammsgdistweek.html
// PostDatacubeGetupstreammsgdistweekRequest carries the documented parameters of one API call.
type PostDatacubeGetupstreammsgdistweekRequest struct {
	// 起始日期(格式: yyyy-MM-dd),跨度不超过15天
	BeginDate string `json:"begin_date"`
	// 结束日期
	EndDate string `json:"end_date"`
}

// PostDatacubeGetupstreammsgdistweekResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetupstreammsgdistweekResponse struct {
	// 数据列表
	List *PostDatacubeGetupstreammsgdistweekResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetupstreammsgdistweekResponseListObject is a documented nested object.
type PostDatacubeGetupstreammsgdistweekResponseListObject struct {
	// 数据的日期,需在begin_date和end_date之间
	RefDate string `json:"ref_date,omitempty"`
	// 当日发送消息量分布的区间,0代表 "0",1代表"1-5",2代表"6-10",3代表"10次以上"
	CountInterval int64 `json:"count_interval,omitzero"`
	// 上行发送了(向公众号发送了)消息的用户数
	MsgUser int64 `json:"msg_user,omitzero"`
}

func (c *Client) PostDatacubeGetupstreammsgdistweek(ctx context.Context, req *PostDatacubeGetupstreammsgdistweekRequest) (*PostDatacubeGetupstreammsgdistweekResponse, error) {
	return core.Call[PostDatacubeGetupstreammsgdistweekResponse](c.EndpointClient, ctx, "POST", "/datacube/getupstreammsgdistweek", req, postDatacubeGetupstreammsgdistweekErrCodes, true, core.SignNone)
}

var postDatacubeGetupstreammsghourErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "时间跨度超过最大限制",
	},
	61503: {
		Desc:     "data not ready please try later",
		Solution: "未完成数据统计处理",
	},
}

// PostDatacubeGetupstreammsghour 获取消息发送分时数据 (POST /datacube/getupstreammsghour)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/wedata/mess/api_getupstreammsghour.html
// PostDatacubeGetupstreammsghourRequest carries the documented parameters of one API call.
type PostDatacubeGetupstreammsghourRequest struct {
	// 起始日期(格式: yyyy-MM-dd)
	BeginDate string `json:"begin_date"`
	// 结束日期(必须为同一天)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetupstreammsghourResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetupstreammsghourResponse struct {
	// 数据列表
	List []*PostDatacubeGetupstreammsghourResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetupstreammsghourResponseListObject is a documented nested object.
type PostDatacubeGetupstreammsghourResponseListObject struct {
	// 数据的日期,需在begin_date和end_date之间
	RefDate string `json:"ref_date,omitempty"`
	// 消息类型,代表含义如下: 1代表文字 2代表图片 3代表语音 4代表视频 6代表第三方应用消息(链接消息)
	MsgType int64 `json:"msg_type,omitzero"`
	// 上行发送了(向公众号发送了)消息的用户数
	MsgUser int64 `json:"msg_user,omitzero"`
	// 上行发送了消息的消息总数
	MsgCount int64 `json:"msg_count,omitzero"`
}

func (c *Client) PostDatacubeGetupstreammsghour(ctx context.Context, req *PostDatacubeGetupstreammsghourRequest) (*PostDatacubeGetupstreammsghourResponse, error) {
	return core.Call[PostDatacubeGetupstreammsghourResponse](c.EndpointClient, ctx, "POST", "/datacube/getupstreammsghour", req, postDatacubeGetupstreammsghourErrCodes, true, core.SignNone)
}

var postDatacubeGetupstreammsgmonthErrCodes = map[int]core.ErrDoc{40001: {
	Desc:     "invalid credential access_token isinvalid or not latest",
	Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
}}

// PostDatacubeGetupstreammsgmonth 获取消息发送月数据 (POST /datacube/getupstreammsgmonth)
// Doc: https://developers.weixin.qq.com/doc/subscription/api/wedata/mess/api_getupstreammsgmonth.html
// PostDatacubeGetupstreammsgmonthRequest carries the documented parameters of one API call.
type PostDatacubeGetupstreammsgmonthRequest struct {
	// 起始日期(格式: yyyy-MM-dd)
	BeginDate string `json:"begin_date"`
	// 结束日期(必须为同一天)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetupstreammsgmonthResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetupstreammsgmonthResponse struct {
	// 数据列表
	List []*PostDatacubeGetupstreammsgmonthResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetupstreammsgmonthResponseListObject is a documented nested object.
type PostDatacubeGetupstreammsgmonthResponseListObject struct {
	// 数据的日期,需在begin_date和end_date之间
	RefDate string `json:"ref_date,omitempty"`
	// 消息类型,代表含义如下: 1代表文字 2代表图片 3代表语音 4代表视频 6代表第三方应用消息(链接消息)
	MsgType int64 `json:"msg_type,omitzero"`
	// 上行发送了(向公众号发送了)消息的用户数
	MsgUser int64 `json:"msg_user,omitzero"`
	// 上行发送了消息的消息总数
	MsgCount int64 `json:"msg_count,omitzero"`
}

func (c *Client) PostDatacubeGetupstreammsgmonth(ctx context.Context, req *PostDatacubeGetupstreammsgmonthRequest) (*PostDatacubeGetupstreammsgmonthResponse, error) {
	return core.Call[PostDatacubeGetupstreammsgmonthResponse](c.EndpointClient, ctx, "POST", "/datacube/getupstreammsgmonth", req, postDatacubeGetupstreammsgmonthErrCodes, true, core.SignNone)
}

var postDatacubeGetupstreammsgweekErrCodes = map[int]core.ErrDoc{40001: {
	Desc:     "invalid credential access_token isinvalid or not latest",
	Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
}}

// PostDatacubeGetupstreammsgweek 获取消息发送周数据 (POST /datacube/getupstreammsgweek)
// Doc: https://developers.weixin.qq.com/doc/service/api/wedata/mess/api_getupstreammsgweek.html
// PostDatacubeGetupstreammsgweekRequest carries the documented parameters of one API call.
type PostDatacubeGetupstreammsgweekRequest struct {
	// 起始日期(格式: yyyy-MM-dd)
	BeginDate string `json:"begin_date"`
	// 结束日期(必须为同一天)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetupstreammsgweekResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetupstreammsgweekResponse struct {
	// 数据列表
	List []*PostDatacubeGetupstreammsgweekResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetupstreammsgweekResponseListObject is a documented nested object.
type PostDatacubeGetupstreammsgweekResponseListObject struct {
	// 数据的日期,需在begin_date和end_date之间
	RefDate string `json:"ref_date,omitempty"`
	// 消息类型,代表含义如下: 1代表文字 2代表图片 3代表语音 4代表视频 6代表第三方应用消息(链接消息)
	MsgType int64 `json:"msg_type,omitzero"`
	// 上行发送了(向公众号发送了)消息的用户数
	MsgUser int64 `json:"msg_user,omitzero"`
	// 上行发送了消息的消息总数
	MsgCount int64 `json:"msg_count,omitzero"`
}

func (c *Client) PostDatacubeGetupstreammsgweek(ctx context.Context, req *PostDatacubeGetupstreammsgweekRequest) (*PostDatacubeGetupstreammsgweekResponse, error) {
	return core.Call[PostDatacubeGetupstreammsgweekResponse](c.EndpointClient, ctx, "POST", "/datacube/getupstreammsgweek", req, postDatacubeGetupstreammsgweekErrCodes, true, core.SignNone)
}

var postDatacubeGetusercumulateErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "日期跨度超过限制",
	},
	61503: {
		Desc:     "data not ready please try later",
		Solution: "指定日期数据尚未生成",
	},
}

// PostDatacubeGetusercumulate 获取累计用户数据 (POST /datacube/getusercumulate)
// Doc: https://developers.weixin.qq.com/doc/service/api/wedata/user/api_getusercumulate.html
// PostDatacubeGetusercumulateRequest carries the documented parameters of one API call.
type PostDatacubeGetusercumulateRequest struct {
	// 起始日期(格式yyyy-MM-dd)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大跨度7天)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetusercumulateResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetusercumulateResponse struct {
	// 数据列表
	List *PostDatacubeGetusercumulateResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetusercumulateResponseListObject is a documented nested object.
type PostDatacubeGetusercumulateResponseListObject struct {
	// 数据的日期
	RefDate string `json:"ref_date,omitempty"`
	// 总用户量
	CumulateUser int64 `json:"cumulate_user,omitzero"`
}

func (c *Client) PostDatacubeGetusercumulate(ctx context.Context, req *PostDatacubeGetusercumulateRequest) (*PostDatacubeGetusercumulateResponse, error) {
	return core.Call[PostDatacubeGetusercumulateResponse](c.EndpointClient, ctx, "POST", "/datacube/getusercumulate", req, postDatacubeGetusercumulateErrCodes, true, core.SignNone)
}

var postDatacubeGetuserreadErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostDatacubeGetuserread 获取图文阅读概况数据 (POST /datacube/getuserread)
// Doc: https://developers.weixin.qq.com/doc/service/api/wedata/news/api_getuserread.html
// PostDatacubeGetuserreadRequest carries the documented parameters of one API call.
type PostDatacubeGetuserreadRequest struct {
	// 起始日期(YYYY-MM-DD)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大值为昨日)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetuserreadResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetuserreadResponse struct {
	// 数据列表
	List []*PostDatacubeGetuserreadResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetuserreadResponseListObject is a documented nested object.
type PostDatacubeGetuserreadResponseListObject struct {
	// 数据的日期,需在begin_date和end_date之间
	RefDate string `json:"ref_date,omitempty"`
	// 用户从哪里进入来阅读该图文。99999999.全部;0:会话;1.好友;2.朋友圈;4.历史消息页;5.其他;6.看一看;7.搜一搜;
	UserSource int64 `json:"user_source,omitzero"`
	// 图文页(点击群发图文卡片进入的页面)的阅读人数
	IntPageReadUser int64 `json:"int_page_read_user,omitzero"`
	// 图文页的阅读次数
	IntPageReadCount int64 `json:"int_page_read_count,omitzero"`
	// 原文页(点击图文页"阅读原文"进入的页面)的阅读人数,无原文页时此处数据为0
	OriPageReadUser int64 `json:"ori_page_read_user,omitzero"`
	// 原文页的阅读次数
	OriPageReadCount int64 `json:"ori_page_read_count,omitzero"`
	// 分享的人数
	ShareUser int64 `json:"share_user,omitzero"`
	// 分享的次数
	ShareCount int64 `json:"share_count,omitzero"`
	// 收藏的人数
	AddToFavUser int64 `json:"add_to_fav_user,omitzero"`
	// 收藏的次数
	AddToFavCount int64 `json:"add_to_fav_count,omitzero"`
}

func (c *Client) PostDatacubeGetuserread(ctx context.Context, req *PostDatacubeGetuserreadRequest) (*PostDatacubeGetuserreadResponse, error) {
	return core.Call[PostDatacubeGetuserreadResponse](c.EndpointClient, ctx, "POST", "/datacube/getuserread", req, postDatacubeGetuserreadErrCodes, true, core.SignNone)
}

var postDatacubeGetuserreadhourErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostDatacubeGetuserreadhour 获取图文阅读分时数据 (POST /datacube/getuserreadhour)
// Doc: https://developers.weixin.qq.com/doc/service/api/wedata/news/api_getuserreadhour.html
// PostDatacubeGetuserreadhourRequest carries the documented parameters of one API call.
type PostDatacubeGetuserreadhourRequest struct {
	// 起始日期(YYYY-MM-DD)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大值为昨日)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetuserreadhourResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetuserreadhourResponse struct {
	// 数据列表
	List []*PostDatacubeGetuserreadhourResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetuserreadhourResponseListObject is a documented nested object.
type PostDatacubeGetuserreadhourResponseListObject struct {
	// 数据的日期,需在begin_date和end_date之间
	RefDate string `json:"ref_date,omitempty"`
	// 数据小时
	RefHour int64 `json:"ref_hour,omitzero"`
	// 用户从哪里进入来阅读该图文。99999999.全部;0:会话;1.好友;2.朋友圈;4.历史消息页;5.其他;6.看一看;7.搜一搜;
	UserSource int64 `json:"user_source,omitzero"`
	// 图文页(点击群发图文卡片进入的页面)的阅读人数
	IntPageReadUser int64 `json:"int_page_read_user,omitzero"`
	// 图文页的阅读次数
	IntPageReadCount int64 `json:"int_page_read_count,omitzero"`
	// 原文页(点击图文页"阅读原文"进入的页面)的阅读人数,无原文页时此处数据为0
	OriPageReadUser int64 `json:"ori_page_read_user,omitzero"`
	// 原文页的阅读次数
	OriPageReadCount int64 `json:"ori_page_read_count,omitzero"`
	// 分享的人数
	ShareUser int64 `json:"share_user,omitzero"`
	// 分享的次数
	ShareCount int64 `json:"share_count,omitzero"`
	// 收藏的人数
	AddToFavUser int64 `json:"add_to_fav_user,omitzero"`
	// 收藏的次数
	AddToFavCount int64 `json:"add_to_fav_count,omitzero"`
}

func (c *Client) PostDatacubeGetuserreadhour(ctx context.Context, req *PostDatacubeGetuserreadhourRequest) (*PostDatacubeGetuserreadhourResponse, error) {
	return core.Call[PostDatacubeGetuserreadhourResponse](c.EndpointClient, ctx, "POST", "/datacube/getuserreadhour", req, postDatacubeGetuserreadhourErrCodes, true, core.SignNone)
}

var postDatacubeGetusershareErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "日期范围错误",
	},
	61503: {
		Desc:     "data not ready please try later",
		Solution: "该日期数据还未就绪",
	},
}

// PostDatacubeGetusershare 获取图文转发概况数据 (POST /datacube/getusershare)
// Doc: https://developers.weixin.qq.com/doc/service/api/wedata/news/api_getusershare.html
// PostDatacubeGetusershareRequest carries the documented parameters of one API call.
type PostDatacubeGetusershareRequest struct {
	// 起始日期(YYYY-MM-DD)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大值为昨日)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetusershareResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetusershareResponse struct {
	// 数据列表
	List []*PostDatacubeGetusershareResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetusershareResponseListObject is a documented nested object.
type PostDatacubeGetusershareResponseListObject struct {
	// 数据的日期,需在begin_date和end_date之间
	RefDate string `json:"ref_date,omitempty"`
	// 分享的人数
	ShareUser int64 `json:"share_user,omitzero"`
	// 分享的次数
	ShareCount int64 `json:"share_count,omitzero"`
	// 分享的场景 1代表好友转发 2代表朋友圈 255代表其他
	ShareScene int64 `json:"share_scene,omitzero"`
}

func (c *Client) PostDatacubeGetusershare(ctx context.Context, req *PostDatacubeGetusershareRequest) (*PostDatacubeGetusershareResponse, error) {
	return core.Call[PostDatacubeGetusershareResponse](c.EndpointClient, ctx, "POST", "/datacube/getusershare", req, postDatacubeGetusershareErrCodes, true, core.SignNone)
}

var postDatacubeGetusersharehourErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
}

// PostDatacubeGetusersharehour 获取图文转发分时数据 (POST /datacube/getusersharehour)
// Doc: https://developers.weixin.qq.com/doc/service/api/wedata/news/api_getusersharehour.html
// PostDatacubeGetusersharehourRequest carries the documented parameters of one API call.
type PostDatacubeGetusersharehourRequest struct {
	// 起始日期(YYYY-MM-DD)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大值为昨日)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetusersharehourResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetusersharehourResponse struct {
	// 数据列表
	List []*PostDatacubeGetusersharehourResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetusersharehourResponseListObject is a documented nested object.
type PostDatacubeGetusersharehourResponseListObject struct {
	// 数据的日期,需在begin_date和end_date之间
	RefDate string `json:"ref_date,omitempty"`
	// 数据小时
	RefHour int64 `json:"ref_hour,omitzero"`
	// 分享的人数
	ShareUser int64 `json:"share_user,omitzero"`
	// 分享的次数
	ShareCount int64 `json:"share_count,omitzero"`
	// 分享的场景 1代表好友转发 2代表朋友圈 255代表其他
	ShareScene int64 `json:"share_scene,omitzero"`
}

func (c *Client) PostDatacubeGetusersharehour(ctx context.Context, req *PostDatacubeGetusersharehourRequest) (*PostDatacubeGetusersharehourResponse, error) {
	return core.Call[PostDatacubeGetusersharehourResponse](c.EndpointClient, ctx, "POST", "/datacube/getusersharehour", req, postDatacubeGetusersharehourErrCodes, true, core.SignNone)
}

var postDatacubeGetusersummaryErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	61500: {
		Desc:     "date format error",
		Solution: "日期格式错误",
	},
	61501: {
		Desc:     "date range error",
		Solution: "日期跨度超过限制",
	},
	61503: {
		Desc:     "data not ready please try later",
		Solution: "指定日期数据尚未生成",
	},
}

// PostDatacubeGetusersummary 获取用户增减数据 (POST /datacube/getusersummary)
// Doc: https://developers.weixin.qq.com/doc/service/api/wedata/user/api_getusersummary.html
// PostDatacubeGetusersummaryRequest carries the documented parameters of one API call.
type PostDatacubeGetusersummaryRequest struct {
	// 起始日期(格式yyyy-MM-dd)
	BeginDate string `json:"begin_date"`
	// 结束日期(最大跨度7天)
	EndDate string `json:"end_date"`
}

// PostDatacubeGetusersummaryResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostDatacubeGetusersummaryResponse struct {
	// 数据列表
	List []*PostDatacubeGetusersummaryResponseListObject `json:"list,omitempty"`
}

// PostDatacubeGetusersummaryResponseListObject is a documented nested object.
type PostDatacubeGetusersummaryResponseListObject struct {
	// 数据的日期
	RefDate string `json:"ref_date,omitempty"`
	// 用户的渠道,数值代表的含义如下:0代表其他合计、1代表公众号搜索、17代表名片分享、30代表扫描二维码、57代表文章内账号名称、100代表微信广告、161代表他人转载、149代表小程序关注、200代表视频号、201代表直播
	UserSource int64 `json:"user_source,omitzero"`
	// 新增的用户数量
	NewUser int64 `json:"new_user,omitzero"`
	// 取消关注的用户数量,new_user减去cancel_user即为净增用户数量
	CancelUser int64 `json:"cancel_user,omitzero"`
}

func (c *Client) PostDatacubeGetusersummary(ctx context.Context, req *PostDatacubeGetusersummaryRequest) (*PostDatacubeGetusersummaryResponse, error) {
	return core.Call[PostDatacubeGetusersummaryResponse](c.EndpointClient, ctx, "POST", "/datacube/getusersummary", req, postDatacubeGetusersummaryErrCodes, true, core.SignNone)
}
