// Code generated by docsync from the official WeChat documentation. DO NOT EDIT.
// The API surface (names, request/response shapes) is derived deterministically
// from the endpoints; regenerate with "make docs-sync". If this file changes
// under you, the upstream documentation changed.

package miniprogram

import (
	"context"
	"github.com/go-sphere/weixin-api/core"
)

var postTcbAdddelayedfunctiontaskErrCodes = map[int]core.ErrDoc{
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	-501000: {
		Desc:     "Param Invalid: env check invalid be filterd",
		Solution: "",
	},
}

// PostTcbAdddelayedfunctiontask 延时调用云函数 (POST /tcb/adddelayedfunctiontask)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/functions/api_adddelayedfunctiontask.html
// PostTcbAdddelayedfunctiontaskRequest carries the documented parameters of one API call.
type PostTcbAdddelayedfunctiontaskRequest struct {
	// 环境ID
	Env string `json:"env"`
	// 函数名称
	FunctionName string `json:"function_name"`
	// 发送的数据包,格式必须为JSONString
	Data string `json:"data"`
	// 延迟时间,单位:秒,合法范围:6秒-30天
	DelayTime int64 `json:"delay_time"`
}

// PostTcbAdddelayedfunctiontaskResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbAdddelayedfunctiontaskResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostTcbAdddelayedfunctiontask(ctx context.Context, req *PostTcbAdddelayedfunctiontaskRequest) (*PostTcbAdddelayedfunctiontaskResponse, error) {
	return core.Call[PostTcbAdddelayedfunctiontaskResponse](c.EndpointClient, ctx, "POST", "/tcb/adddelayedfunctiontask", req, postTcbAdddelayedfunctiontaskErrCodes, true, core.SignNone)
}

var postTcbBatchdeletefileErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	-501002: {
		Desc:     "云资源通用错误:云端响应超时",
		Solution: "",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbBatchdeletefile 删除文件 (POST /tcb/batchdeletefile)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/storage/api_deletetcbcloudfile.html
// PostTcbBatchdeletefileRequest carries the documented parameters of one API call.
type PostTcbBatchdeletefileRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 文件 ID 列表
	FileidList []string `json:"fileid_list"`
}

// PostTcbBatchdeletefileResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbBatchdeletefileResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 文件列表
	DeleteList []*PostTcbBatchdeletefileResponseDeleteListObject `json:"delete_list,omitempty"`
}

// PostTcbBatchdeletefileResponseDeleteListObject is a documented nested object.
type PostTcbBatchdeletefileResponseDeleteListObject struct {
	// 文件id
	Fileid string `json:"fileid,omitempty"`
	// 状态
	Status int64 `json:"status,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostTcbBatchdeletefile(ctx context.Context, req *PostTcbBatchdeletefileRequest) (*PostTcbBatchdeletefileResponse, error) {
	return core.Call[PostTcbBatchdeletefileResponse](c.EndpointClient, ctx, "POST", "/tcb/batchdeletefile", req, postTcbBatchdeletefileErrCodes, true, core.SignNone)
}

var postTcbBatchdownloadfileErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	-501000: {
		Desc:     "未知错误",
		Solution: "请提工单反馈",
	},
	-501002: {
		Desc:     "云资源通用错误:云端响应超时",
		Solution: "",
	},
	-501007: {
		Desc:     "参数有误,具体原因参考 errmsg",
		Solution: "",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbBatchdownloadfile 获取文件下载链接 (POST /tcb/batchdownloadfile)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/storage/api_getdownloadtcbfilelink.html
// PostTcbBatchdownloadfileRequest carries the documented parameters of one API call.
type PostTcbBatchdownloadfileRequest struct {
	// 环境id
	Env string `json:"env"`
	// 文件列表
	FileList []*PostTcbBatchdownloadfileRequestFileListObject `json:"file_list"`
}

// PostTcbBatchdownloadfileRequestFileListObject is a documented nested object.
type PostTcbBatchdownloadfileRequestFileListObject struct {
	// 文件id
	Fileid string `json:"fileid"`
	// 下载链接有效期
	MaxAge int64 `json:"max_age"`
}

// PostTcbBatchdownloadfileResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbBatchdownloadfileResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 文件列表
	FileList []*PostTcbBatchdownloadfileResponseFileListObject `json:"file_list,omitempty"`
}

// PostTcbBatchdownloadfileResponseFileListObject is a documented nested object.
type PostTcbBatchdownloadfileResponseFileListObject struct {
	// 文件ID
	Fileid string `json:"fileid,omitempty"`
	// 下载链接
	DownloadURL string `json:"download_url,omitempty"`
	// 状态码
	Status int64 `json:"status,omitzero"`
	// 该文件错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostTcbBatchdownloadfile(ctx context.Context, req *PostTcbBatchdownloadfileRequest) (*PostTcbBatchdownloadfileResponse, error) {
	return core.Call[PostTcbBatchdownloadfileResponse](c.EndpointClient, ctx, "POST", "/tcb/batchdownloadfile", req, postTcbBatchdownloadfileErrCodes, true, core.SignNone)
}

var postTcbCloudbasereportErrCodes = map[int]core.ErrDoc{-1: {
	Desc:     "system error",
	Solution: "系统繁忙,此时请开发者稍候再试",
}}

// PostTcbCloudbasereport 云开发上报接口 (POST /tcb/cloudbasereport)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/others/api_cloudbasereportapi.html
// PostTcbCloudbasereportRequest carries the documented parameters of one API call.
type PostTcbCloudbasereportRequest struct {
	// 上报动作,目前支持(sendSmsTask:发送短信;openH5:H5 打开)
	ReportAction string `json:"report_action"`
	// 环境 ID
	EnvID string `json:"env_id"`
	// 活动 ID
	ActivityID string `json:"activity_id"`
	// 任务 ID【report_action 取 sendSmsTask 时必填】
	TaskID string `json:"task_id"`
	// 下发手机号数量【report_action 取 sendSmsTask 时必填】
	PhoneCount string `json:"phone_count"`
	// 渠道 ID(云开发 CMS 使用 _cms_sms_)【report_action 取 openH5 时必填】
	ChannelID string `json:"channel_id"`
	// 会话 ID【report_action 取 openH5 时必填】
	SessionID string `json:"session_id"`
}

// PostTcbCloudbasereportResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbCloudbasereportResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostTcbCloudbasereport(ctx context.Context, req *PostTcbCloudbasereportRequest) (*PostTcbCloudbasereportResponse, error) {
	return core.Call[PostTcbCloudbasereportResponse](c.EndpointClient, ctx, "POST", "/tcb/cloudbasereport", req, postTcbCloudbasereportErrCodes, true, core.SignNone)
}

var postTcbCreatesendsmstaskErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	-501007: {
		Desc:     "参数有误,具体原因参考 errmsg",
		Solution: "",
	},
	-601027: {
		Desc:     "无效的环境",
		Solution: "",
	},
	-601028: {
		Desc:     "该环境没有开通静态网站",
		Solution: "",
	},
	-601032: {
		Desc:     "小程序昵称不能为空",
		Solution: "",
	},
	-601033: {
		Desc:     "仅支持非个人主体小程序",
		Solution: "",
	},
}

// PostTcbCreatesendsmstask 创建发短信任务 (POST /tcb/createsendsmstask)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/others/api_createsendsmstask.html
// PostTcbCreatesendsmstaskRequest carries the documented parameters of one API call.
type PostTcbCreatesendsmstaskRequest struct {
	// 环境 ID
	Env string `json:"env"`
	// 短信 CSV 文件地址CodeUri
	FileURL string `json:"file_url"`
	// 短信模版 ID 默认值:844110(销类短信模版 ID)
	TemplateID string `json:"template_id"`
}

// PostTcbCreatesendsmstaskResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbCreatesendsmstaskResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 查询 ID
	QueryID string `json:"query_id,omitempty"`
}

func (c *Client) PostTcbCreatesendsmstask(ctx context.Context, req *PostTcbCreatesendsmstaskRequest) (*PostTcbCreatesendsmstaskResponse, error) {
	return core.Call[PostTcbCreatesendsmstaskResponse](c.EndpointClient, ctx, "POST", "/tcb/createsendsmstask", req, postTcbCreatesendsmstaskErrCodes, true, core.SignNone)
}

var postTcbDatabaseaddErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDatabaseadd 数据库插入记录 (POST /tcb/databaseadd)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_adddatabaseitem.html
// PostTcbDatabaseaddRequest carries the documented parameters of one API call.
type PostTcbDatabaseaddRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 数据库操作语句
	Query string `json:"query"`
}

// PostTcbDatabaseaddResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDatabaseaddResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 插入成功的数据集合主键_id
	IDList []string `json:"id_list,omitempty"`
}

func (c *Client) PostTcbDatabaseadd(ctx context.Context, req *PostTcbDatabaseaddRequest) (*PostTcbDatabaseaddResponse, error) {
	return core.Call[PostTcbDatabaseaddResponse](c.EndpointClient, ctx, "POST", "/tcb/databaseadd", req, postTcbDatabaseaddErrCodes, true, core.SignNone)
}

var postTcbDatabaseaggregateErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	-501000: {
		Desc:     "未知错误",
		Solution: "请提工单反馈",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDatabaseaggregate 数据库聚合 (POST /tcb/databaseaggregate)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_aggregatedatabase.html
// PostTcbDatabaseaggregateRequest carries the documented parameters of one API call.
type PostTcbDatabaseaggregateRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 数据库操作语句
	Query string `json:"query"`
}

// PostTcbDatabaseaggregateResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDatabaseaggregateResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 记录数组
	Data []string `json:"data,omitempty"`
}

func (c *Client) PostTcbDatabaseaggregate(ctx context.Context, req *PostTcbDatabaseaggregateRequest) (*PostTcbDatabaseaggregateResponse, error) {
	return core.Call[PostTcbDatabaseaggregateResponse](c.EndpointClient, ctx, "POST", "/tcb/databaseaggregate", req, postTcbDatabaseaggregateErrCodes, true, core.SignNone)
}

var postTcbDatabasecollectionaddErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	-501000: {
		Desc:     "未知错误",
		Solution: "请提工单联系我们",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDatabasecollectionadd 新增集合 (POST /tcb/databasecollectionadd)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_adddatabasecollection.html
// PostTcbDatabasecollectionaddRequest carries the documented parameters of one API call.
type PostTcbDatabasecollectionaddRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 集合名称
	CollectionName string `json:"collection_name"`
}

// PostTcbDatabasecollectionaddResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDatabasecollectionaddResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostTcbDatabasecollectionadd(ctx context.Context, req *PostTcbDatabasecollectionaddRequest) (*PostTcbDatabasecollectionaddResponse, error) {
	return core.Call[PostTcbDatabasecollectionaddResponse](c.EndpointClient, ctx, "POST", "/tcb/databasecollectionadd", req, postTcbDatabasecollectionaddErrCodes, true, core.SignNone)
}

var postTcbDatabasecollectiondeleteErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDatabasecollectiondelete 删除集合 (POST /tcb/databasecollectiondelete)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_deletedatabasecollection.html
// PostTcbDatabasecollectiondeleteRequest carries the documented parameters of one API call.
type PostTcbDatabasecollectiondeleteRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 集合名称
	CollectionName string `json:"collection_name"`
}

// PostTcbDatabasecollectiondeleteResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDatabasecollectiondeleteResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostTcbDatabasecollectiondelete(ctx context.Context, req *PostTcbDatabasecollectiondeleteRequest) (*PostTcbDatabasecollectiondeleteResponse, error) {
	return core.Call[PostTcbDatabasecollectiondeleteResponse](c.EndpointClient, ctx, "POST", "/tcb/databasecollectiondelete", req, postTcbDatabasecollectiondeleteErrCodes, true, core.SignNone)
}

var postTcbDatabasecollectiongetErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDatabasecollectionget 获取集合信息 (POST /tcb/databasecollectionget)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_getdatabasecollection.html
// PostTcbDatabasecollectiongetRequest carries the documented parameters of one API call.
type PostTcbDatabasecollectiongetRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 获取数量限制
	Limit int64 `json:"limit,omitzero"`
	// 偏移量
	Offset int64 `json:"offset,omitzero"`
}

// PostTcbDatabasecollectiongetResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDatabasecollectiongetResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 集合信息
	Collections []*PostTcbDatabasecollectiongetResponseCollectionsObject `json:"collections,omitempty"`
	// 分页信息
	Pager *PostTcbDatabasecollectiongetResponsePagerObject `json:"pager,omitempty"`
}

// PostTcbDatabasecollectiongetResponseCollectionsObject is a documented nested object.
type PostTcbDatabasecollectiongetResponseCollectionsObject struct {
	// 集合名
	Name string `json:"name,omitempty"`
	// 表中文档数量
	Count int64 `json:"count,omitzero"`
	// 表的大小(即表中文档总大小),单位:字节
	Size int64 `json:"size,omitzero"`
	// 索引数量
	IndexCount int64 `json:"index_count,omitzero"`
	// 索引占用大小,单位:字节
	IndexSize int64 `json:"index_size,omitzero"`
}

// PostTcbDatabasecollectiongetResponsePagerObject is a documented nested object.
type PostTcbDatabasecollectiongetResponsePagerObject struct {
	// 偏移
	Offset int64 `json:"Offset,omitzero"`
	// 单次查询限制
	Limit int64 `json:"Limit,omitzero"`
	// 符合查询条件的记录总数
	Total int64 `json:"Total,omitzero"`
}

func (c *Client) PostTcbDatabasecollectionget(ctx context.Context, req *PostTcbDatabasecollectiongetRequest) (*PostTcbDatabasecollectiongetResponse, error) {
	return core.Call[PostTcbDatabasecollectiongetResponse](c.EndpointClient, ctx, "POST", "/tcb/databasecollectionget", req, postTcbDatabasecollectiongetErrCodes, true, core.SignNone)
}

var postTcbDatabasecountErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDatabasecount 统计集合记录数 (POST /tcb/databasecount)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_getdatabasecount.html
// PostTcbDatabasecountRequest carries the documented parameters of one API call.
type PostTcbDatabasecountRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 数据库操作语句
	Query string `json:"query"`
}

// PostTcbDatabasecountResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDatabasecountResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 记录数量
	Count int64 `json:"count,omitzero"`
}

func (c *Client) PostTcbDatabasecount(ctx context.Context, req *PostTcbDatabasecountRequest) (*PostTcbDatabasecountResponse, error) {
	return core.Call[PostTcbDatabasecountResponse](c.EndpointClient, ctx, "POST", "/tcb/databasecount", req, postTcbDatabasecountErrCodes, true, core.SignNone)
}

var postTcbDatabasedeleteErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDatabasedelete 数据库删除记录 (POST /tcb/databasedelete)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_deletedatabaseitem.html
// PostTcbDatabasedeleteRequest carries the documented parameters of one API call.
type PostTcbDatabasedeleteRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 数据库操作语句
	Query string `json:"query"`
}

// PostTcbDatabasedeleteResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDatabasedeleteResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 删除记录数量
	Deleted int64 `json:"deleted,omitzero"`
}

func (c *Client) PostTcbDatabasedelete(ctx context.Context, req *PostTcbDatabasedeleteRequest) (*PostTcbDatabasedeleteResponse, error) {
	return core.Call[PostTcbDatabasedeleteResponse](c.EndpointClient, ctx, "POST", "/tcb/databasedelete", req, postTcbDatabasedeleteErrCodes, true, core.SignNone)
}

var postTcbDatabasemigrateexportErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDatabasemigrateexport 数据库导出 (POST /tcb/databasemigrateexport)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_exportdatabaseitem.html
// PostTcbDatabasemigrateexportRequest carries the documented parameters of one API call.
type PostTcbDatabasemigrateexportRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 导出文件路径(文件会导出到公共的云存储中,可使用 getDownloadTcbFileLink接口 获取下载链接)
	FilePath string `json:"file_path"`
	// 导出文件类型,文件格式参考 importDatabaseItem接口 的文件格式部分
	FileType int64 `json:"file_type"`
	// 导出条件
	Query string `json:"query"`
}

// PostTcbDatabasemigrateexportResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDatabasemigrateexportResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 导出任务ID,使用 getDatabaseMigrateStatus接口 查询导出结果,获取文件下载链接。
	JobID int64 `json:"job_id,omitzero"`
}

func (c *Client) PostTcbDatabasemigrateexport(ctx context.Context, req *PostTcbDatabasemigrateexportRequest) (*PostTcbDatabasemigrateexportResponse, error) {
	return core.Call[PostTcbDatabasemigrateexportResponse](c.EndpointClient, ctx, "POST", "/tcb/databasemigrateexport", req, postTcbDatabasemigrateexportErrCodes, true, core.SignNone)
}

var postTcbDatabasemigrateimportErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	-501000: {
		Desc:     "",
		Solution: "",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDatabasemigrateimport 数据库导入 (POST /tcb/databasemigrateimport)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_importdatabaseitem.html
// PostTcbDatabasemigrateimportRequest carries the documented parameters of one API call.
type PostTcbDatabasemigrateimportRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 导入 collection 名
	CollectionName string `json:"collection_name"`
	// 导入文件路径(导入文件需先上传到同环境的存储中,可使用开发者工具或 getUploadTcbFileLink接口 上传)
	FilePath string `json:"file_path"`
	// 导入文件类型。1表示JSON。2表示CSV
	FileType int64 `json:"file_type"`
	// 是否在遇到错误时停止导入
	StopOnError bool `json:"stop_on_error"`
	// 冲突处理模式。1表示INSERT。2表示UPSERT。
	ConflictMode int64 `json:"conflict_mode"`
}

// PostTcbDatabasemigrateimportResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDatabasemigrateimportResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 导入任务ID,可使用 getDatabaseMigrateStatus接口 查询导入进度及结果
	JobID int64 `json:"job_id,omitzero"`
}

func (c *Client) PostTcbDatabasemigrateimport(ctx context.Context, req *PostTcbDatabasemigrateimportRequest) (*PostTcbDatabasemigrateimportResponse, error) {
	return core.Call[PostTcbDatabasemigrateimportResponse](c.EndpointClient, ctx, "POST", "/tcb/databasemigrateimport", req, postTcbDatabasemigrateimportErrCodes, true, core.SignNone)
}

var postTcbDatabasemigratequeryinfoErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDatabasemigratequeryinfo 数据库迁移状态查询 (POST /tcb/databasemigratequeryinfo)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_getdatabasemigratestatus.html
// PostTcbDatabasemigratequeryinfoRequest carries the documented parameters of one API call.
type PostTcbDatabasemigratequeryinfoRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 迁移任务ID
	JobID int64 `json:"job_id"`
}

// PostTcbDatabasemigratequeryinfoResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDatabasemigratequeryinfoResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 导出状态
	Status string `json:"status,omitempty"`
	// 导出成功记录数
	RecordSuccess int64 `json:"record_success,omitzero"`
	// 导出失败记录数
	RecordFail int64 `json:"record_fail,omitzero"`
	// 导出错误信息
	ErrorMsg string `json:"error_msg,omitempty"`
	// 导出文件下载地址
	FileURL string `json:"file_url,omitempty"`
}

func (c *Client) PostTcbDatabasemigratequeryinfo(ctx context.Context, req *PostTcbDatabasemigratequeryinfoRequest) (*PostTcbDatabasemigratequeryinfoResponse, error) {
	return core.Call[PostTcbDatabasemigratequeryinfoResponse](c.EndpointClient, ctx, "POST", "/tcb/databasemigratequeryinfo", req, postTcbDatabasemigratequeryinfoErrCodes, true, core.SignNone)
}

var postTcbDatabasequeryErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDatabasequery 数据库查询记录 (POST /tcb/databasequery)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_getdatabaserecord.html
// PostTcbDatabasequeryRequest carries the documented parameters of one API call.
type PostTcbDatabasequeryRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 数据库操作语句
	Query string `json:"query"`
}

// PostTcbDatabasequeryResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDatabasequeryResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 分页信息
	Pager *PostTcbDatabasequeryResponsePagerObject `json:"pager,omitempty"`
	// 记录数组
	Data []string `json:"data,omitempty"`
}

// PostTcbDatabasequeryResponsePagerObject is a documented nested object.
type PostTcbDatabasequeryResponsePagerObject struct {
	// 偏移
	Offset int64 `json:"Offset,omitzero"`
	// 单次查询限制
	Limit int64 `json:"Limit,omitzero"`
	// 符合查询条件的记录总数
	Total int64 `json:"Total,omitzero"`
}

func (c *Client) PostTcbDatabasequery(ctx context.Context, req *PostTcbDatabasequeryRequest) (*PostTcbDatabasequeryResponse, error) {
	return core.Call[PostTcbDatabasequeryResponse](c.EndpointClient, ctx, "POST", "/tcb/databasequery", req, postTcbDatabasequeryErrCodes, true, core.SignNone)
}

var postTcbDatabaseupdateErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDatabaseupdate 数据库更新记录 (POST /tcb/databaseupdate)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_updatedatabaserecord.html
// PostTcbDatabaseupdateRequest carries the documented parameters of one API call.
type PostTcbDatabaseupdateRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 数据库操作语句
	Query string `json:"query"`
}

// PostTcbDatabaseupdateResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDatabaseupdateResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 更新条件匹配到的结果数
	Matched int64 `json:"matched,omitzero"`
	// 修改的记录数,注意:使用set操作新插入的数据不计入修改数目
	Modified int64 `json:"modified,omitzero"`
	// 新插入记录的id,注意:只有使用set操作新插入数据时这个字段会有值
	ID string `json:"id,omitempty"`
}

func (c *Client) PostTcbDatabaseupdate(ctx context.Context, req *PostTcbDatabaseupdateRequest) (*PostTcbDatabaseupdateResponse, error) {
	return core.Call[PostTcbDatabaseupdateResponse](c.EndpointClient, ctx, "POST", "/tcb/databaseupdate", req, postTcbDatabaseupdateErrCodes, true, core.SignNone)
}

var postTcbDescribeextensionuploadinfoErrCodes = map[int]core.ErrDoc{-1: {
	Desc:     "system error",
	Solution: "系统繁忙,此时请开发者稍候再试",
}}

// PostTcbDescribeextensionuploadinfo 描述扩展上传文件信息 (POST /tcb/describeextensionuploadinfo)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/others/api_describeextensionuploadinfo.html
// PostTcbDescribeextensionuploadinfoRequest carries the documented parameters of one API call.
type PostTcbDescribeextensionuploadinfoRequest struct {
	// 待上传的文件列表
	ExtensionFiles []*PostTcbDescribeextensionuploadinfoRequestExtensionFilesObject `json:"ExtensionFiles"`
}

// PostTcbDescribeextensionuploadinfoRequestExtensionFilesObject is a documented nested object.
type PostTcbDescribeextensionuploadinfoRequestExtensionFilesObject struct {
	// 文件类型。枚举值 FUNCTION:函数代码 STATIC:静态托管代码 SMS:短信文件
	FileType string `json:"FileType"`
	// 文件名,长度不超过24
	FileName string `json:"FileName"`
}

// PostTcbDescribeextensionuploadinfoResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDescribeextensionuploadinfoResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 待上传文件的信息数组
	FilesData []*PostTcbDescribeextensionuploadinfoResponseFilesDataObject `json:"FilesData,omitempty"`
	// 唯一请求 ID,每次请求都会返回。定位问题时需要提供该次请求的 RequestId。
	RequestID string `json:"RequestId,omitempty"`
}

// PostTcbDescribeextensionuploadinfoResponseFilesDataObject is a documented nested object.
type PostTcbDescribeextensionuploadinfoResponseFilesDataObject struct {
	// 模板里使用的地址
	CodeURI string `json:"CodeUri,omitempty"`
	// 上传文件的临时地址,含签名
	UploadURL string `json:"UploadUrl,omitempty"`
	// 自定义密钥。如果为空,则表示不需要加密
	CustomKey string `json:"CustomKey,omitempty"`
	// 文件大小限制,单位M,客户端上传前需要主动检查文件大小,超过限制的文件会被删除。
	MaxSize int64 `json:"MaxSize,omitzero"`
}

func (c *Client) PostTcbDescribeextensionuploadinfo(ctx context.Context, req *PostTcbDescribeextensionuploadinfoRequest) (*PostTcbDescribeextensionuploadinfoResponse, error) {
	return core.Call[PostTcbDescribeextensionuploadinfoResponse](c.EndpointClient, ctx, "POST", "/tcb/describeextensionuploadinfo", req, postTcbDescribeextensionuploadinfoErrCodes, true, core.SignNone)
}

var postTcbDescribesmsrecordsErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbDescribesmsrecords 查询短信记录 (POST /tcb/describesmsrecords)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/others/api_describesmsrecords.html
// PostTcbDescribesmsrecordsRequest carries the documented parameters of one API call.
type PostTcbDescribesmsrecordsRequest struct {
	// 环境 ID
	EnvID string `json:"EnvId"`
	// 开始日期, 如:2021-01-01
	StartDate string `json:"StartDate"`
	// 结束日期, 如2021-01-07
	EndDate string `json:"EndDate"`
	// 电话号码
	Mobile string `json:"Mobile"`
	// 查询ID
	QueryID string `json:"QueryId"`
	// 页码(1开始)
	PageNumber int64 `json:"PageNumber"`
	// 每页条目数
	PageSize int64 `json:"PageSize"`
}

// PostTcbDescribesmsrecordsResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbDescribesmsrecordsResponse struct {
	// 发送记录列表
	SmsRecords []*PostTcbDescribesmsrecordsResponseSmsRecordsObject `json:"SmsRecords,omitempty"`
	// 记录总数
	TotalCount int64 `json:"TotalCount,omitzero"`
	// 唯一请求 ID,每次请求都会返回。定位问题时需要提供该次请求的 RequestId。
	RequestID string `json:"RequestId,omitempty"`
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

// PostTcbDescribesmsrecordsResponseSmsRecordsObject is a documented nested object.
type PostTcbDescribesmsrecordsResponseSmsRecordsObject struct {
	// 手机号码
	Mobile string `json:"Mobile,omitempty"`
	// 短信内容
	Content string `json:"Content,omitempty"`
	// 短信内容长度
	ContentSize int64 `json:"ContentSize,omitzero"`
	// 计费条数
	Fee int64 `json:"Fee,omitzero"`
	// 发送时间
	CreateTime string `json:"CreateTime,omitempty"`
	// 用户接收时间
	ReceivedTime string `json:"ReceivedTime,omitempty"`
	// sent(成功), error(失败)
	Status string `json:"Status,omitempty"`
	// 备注
	Remarks string `json:"Remarks,omitempty"`
}

func (c *Client) PostTcbDescribesmsrecords(ctx context.Context, req *PostTcbDescribesmsrecordsRequest) (*PostTcbDescribesmsrecordsResponse, error) {
	return core.Call[PostTcbDescribesmsrecordsResponse](c.EndpointClient, ctx, "POST", "/tcb/describesmsrecords", req, postTcbDescribesmsrecordsErrCodes, true, core.SignNone)
}

var postTcbGetqcloudtokenErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	45009: {
		Desc:     "reach max api daily quota limit",
		Solution: "调用超过天级别频率限制。可调用clear_quota接口恢复调用额度。",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbGetqcloudtoken 获取腾讯云API调用凭证 (POST /tcb/getqcloudtoken)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/others/api_getcloudtoken.html
// PostTcbGetqcloudtokenRequest carries the documented parameters of one API call.
type PostTcbGetqcloudtokenRequest struct {
	// 有效期(单位为秒,最大7200)
	Lifespan int64 `json:"lifespan"`
}

// PostTcbGetqcloudtokenResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbGetqcloudtokenResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// secretid
	Secretid string `json:"secretid,omitempty"`
	// secretkey
	Secretkey string `json:"secretkey,omitempty"`
	// token
	Token string `json:"token,omitempty"`
	// 过期时间戳
	ExpiredTime int64 `json:"expired_time,omitzero"`
}

func (c *Client) PostTcbGetqcloudtoken(ctx context.Context, req *PostTcbGetqcloudtokenRequest) (*PostTcbGetqcloudtokenResponse, error) {
	return core.Call[PostTcbGetqcloudtokenResponse](c.EndpointClient, ctx, "POST", "/tcb/getqcloudtoken", req, postTcbGetqcloudtokenErrCodes, true, core.SignNone)
}

var postTcbGetstatisticsErrCodes = map[int]core.ErrDoc{10011: {
	Desc:     "没有数据",
	Solution: "",
}}

// PostTcbGetstatistics 获取云开发数据 (POST /tcb/getstatistics)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/others/api_getcloudbasestatistics.html
// PostTcbGetstatisticsRequest carries the documented parameters of one API call.
type PostTcbGetstatisticsRequest struct {
	// 获取动作,目前支持(smsMarketingOverviewData:短信营销概览数据;smsMarketingConversionData:短信营销转化数据;smsMarketingRealTimeData:短信营销实时数据)
	Action string `json:"action"`
	// 开始时间戳
	BeginDate int64 `json:"begin_date"`
	// 结束时间戳
	EndDate int64 `json:"end_date"`
	// 分页 limit【action 取 smsMarketingOverviewData、smsMarketingConversionData 时必填】
	PageLimit int64 `json:"page_limit"`
	// 分页 offset【action 取 smsMarketingOverviewData、smsMarketingConversionData 时必填】
	PageOffset int64 `json:"page_offset"`
}

// PostTcbGetstatisticsResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbGetstatisticsResponse struct {
	// 数据列定义
	DataColumn []*PostTcbGetstatisticsResponseDataColumnObject `json:"data_column,omitempty"`
	// 数据行
	DataValue []*PostTcbGetstatisticsResponseDataValueObject `json:"data_value,omitempty"`
	// 总行数
	TotalNum int64 `json:"total_num,omitzero"`
}

// PostTcbGetstatisticsResponseDataColumnObject is a documented nested object.
type PostTcbGetstatisticsResponseDataColumnObject struct {
	// 列 id
	ColID string `json:"col_id,omitempty"`
	// 列名
	ColName string `json:"col_name,omitempty"`
	// 数据类型(0:string;1:number;2:double)
	ColDataType string `json:"col_data_type,omitempty"`
}

// PostTcbGetstatisticsResponseDataValueObject is a documented nested object.
type PostTcbGetstatisticsResponseDataValueObject struct {
	// 数据值
	DataValue []string `json:"data_value,omitempty"`
}

func (c *Client) PostTcbGetstatistics(ctx context.Context, req *PostTcbGetstatisticsRequest) (*PostTcbGetstatisticsResponse, error) {
	return core.Call[PostTcbGetstatisticsResponse](c.EndpointClient, ctx, "POST", "/tcb/getstatistics", req, postTcbGetstatisticsErrCodes, true, core.SignNone)
}

var postTcbInvokecloudfunctionErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空。post请求body参数不能为空。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbInvokecloudfunction 触发云函数 (POST /tcb/invokecloudfunction)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/functions/api_invokecloudfunction.html
// PostTcbInvokecloudfunctionRequest carries the documented parameters of one API call.
type PostTcbInvokecloudfunctionRequest struct {
	// 云开发环境 ID,用于指定要触发云函数的环境
	Env string `json:"env"`
	// 云函数名称,即要触发的云函数的函数名
	Name string `json:"name"`
	// 传递给云函数的输入参数,为 JSON 字符串格式。具体结构由开发者根据云函数业务逻辑自定义定义
	ReqData string `json:"req_data"`
}

// PostTcbInvokecloudfunctionResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbInvokecloudfunctionResponse struct {
	// 错误码,0 表示成功,其他值表示失败
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息,成功时返回 "ok"
	Errmsg string `json:"errmsg,omitempty"`
	// 云函数返回的数据,为 JSON 字符串格式。内容由云函数业务逻辑决定
	RespData string `json:"resp_data,omitempty"`
}

func (c *Client) PostTcbInvokecloudfunction(ctx context.Context, req *PostTcbInvokecloudfunctionRequest) (*PostTcbInvokecloudfunctionResponse, error) {
	return core.Call[PostTcbInvokecloudfunctionResponse](c.EndpointClient, ctx, "POST", "/tcb/invokecloudfunction", req, postTcbInvokecloudfunctionErrCodes, true, core.SignNone)
}

var postTcbUpdateindexErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "access_token 超时,请检查 access_token 的有效期,请参考基础支持 - 获取 access_token 中,对 access_token 的详细机制说明",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbUpdateindex 更新数据库索引 (POST /tcb/updateindex)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/database/api_updatedatabaseindexs.html
// PostTcbUpdateindexRequest carries the documented parameters of one API call.
type PostTcbUpdateindexRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 集合名称
	CollectionName string `json:"collection_name"`
	// 新增索引
	CreateIndexes []*PostTcbUpdateindexRequestCreateIndexesObject `json:"create_indexes"`
	// 删除索引
	DropIndexes []*PostTcbUpdateindexRequestDropIndexesObject `json:"drop_indexes"`
}

// PostTcbUpdateindexRequestCreateIndexesObject is a documented nested object.
type PostTcbUpdateindexRequestCreateIndexesObject struct {
	// 索引名
	Name string `json:"name"`
	// 是否唯一
	Unique bool `json:"unique"`
	// 索引字段
	Keys []map[string]any `json:"keys"`
}

// PostTcbUpdateindexRequestDropIndexesObject is a documented nested object.
type PostTcbUpdateindexRequestDropIndexesObject struct {
	// 索引名
	Name string `json:"name"`
	// 是否唯一
	Unique bool `json:"unique"`
	// 索引字段
	Keys []map[string]any `json:"keys"`
}

// PostTcbUpdateindexResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbUpdateindexResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostTcbUpdateindex(ctx context.Context, req *PostTcbUpdateindexRequest) (*PostTcbUpdateindexResponse, error) {
	return core.Call[PostTcbUpdateindexResponse](c.EndpointClient, ctx, "POST", "/tcb/updateindex", req, postTcbUpdateindexErrCodes, true, core.SignNone)
}

var postTcbUploadfileErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	-1000: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40014: {
		Desc:     "invalid access_token",
		Solution: "不合法的 access_token ,请开发者认真比对 access_token 的有效性(如是否过期),或查看是否正在为恰当的公众号调用接口",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40101: {
		Desc:     "missing parameter",
		Solution: "缺少必填参数",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "缺少 access_token 参数",
	},
	43002: {
		Desc:     "require POST method",
		Solution: "需要 POST 请求",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
	85088: {
		Desc:     "no qbase privilege",
		Solution: "该APP未开通云开发",
	},
}

// PostTcbUploadfile 获取文件上传链接 (POST /tcb/uploadfile)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/storage/api_getuploadtcbfilelink.html
// PostTcbUploadfileRequest carries the documented parameters of one API call.
type PostTcbUploadfileRequest struct {
	// 云环境ID
	Env string `json:"env"`
	// 上传路径
	Path string `json:"path"`
}

// PostTcbUploadfileResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostTcbUploadfileResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 上传url
	URL string `json:"url,omitempty"`
	// token
	Token string `json:"token,omitempty"`
	// authorization
	Authorization string `json:"authorization,omitempty"`
	// 文件ID
	FileID string `json:"file_id,omitempty"`
	// cos文件ID
	CosFileID string `json:"cos_file_id,omitempty"`
}

func (c *Client) PostTcbUploadfile(ctx context.Context, req *PostTcbUploadfileRequest) (*PostTcbUploadfileResponse, error) {
	return core.Call[PostTcbUploadfileResponse](c.EndpointClient, ctx, "POST", "/tcb/uploadfile", req, postTcbUploadfileErrCodes, true, core.SignNone)
}

var postWxaGetopendataErrCodes = map[int]core.ErrDoc{-1: {
	Desc:     "system error",
	Solution: "系统繁忙,此时请开发者稍候再试",
}}

// PostWxaGetopendata 获取cloudID对应的数据 (POST /wxa/getopendata)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/others/api_getopendata.html
// PostWxaGetopendataRequest carries the documented parameters of one API call.
type PostWxaGetopendataRequest struct {
	// 用户openid(敏感信息需要传入)
	OpenID string `query:"openid,omitempty"`
	// CloudID 列表
	CloudidList []string `json:"cloudid_list"`
}

// PostWxaGetopendataResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaGetopendataResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 开放数据列表
	DataList []*PostWxaGetopendataResponseDataListObject `json:"data_list,omitempty"`
}

// PostWxaGetopendataResponseDataListObject is a documented nested object.
type PostWxaGetopendataResponseDataListObject struct {
	// cloud id
	CloudID string `json:"cloud_id,omitempty"`
	// 数据详情
	JSON string `json:"json,omitempty"`
}

func (c *Client) PostWxaGetopendata(ctx context.Context, req *PostWxaGetopendataRequest) (*PostWxaGetopendataResponse, error) {
	return core.Call[PostWxaGetopendataResponse](c.EndpointClient, ctx, "POST", "/wxa/getopendata", req, postWxaGetopendataErrCodes, true, core.SignNone)
}

var postWxaGetvoipsignErrCodes = map[int]core.ErrDoc{-1: {
	Desc:     "system error",
	Solution: "系统繁忙,此时请开发者稍候再试",
}}

// PostWxaGetvoipsign 获取实时语音签名 (POST /wxa/getvoipsign)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/cloudbase/others/api_getcloudbasevoipsign.html
// PostWxaGetvoipsignRequest carries the documented parameters of one API call.
type PostWxaGetvoipsignRequest struct {
	// 游戏房间的标识
	GroupID string `json:"group_id"`
	// 生成这个随机字符串的 UNIX 时间戳(精确到秒)
	Timestamp int64 `json:"timestamp"`
	// 随机字符串,长度应小于 128
	Nonce string `json:"nonce"`
}

// PostWxaGetvoipsignResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaGetvoipsignResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 签名
	Signature string `json:"signature,omitempty"`
}

func (c *Client) PostWxaGetvoipsign(ctx context.Context, req *PostWxaGetvoipsignRequest) (*PostWxaGetvoipsignResponse, error) {
	return core.Call[PostWxaGetvoipsignResponse](c.EndpointClient, ctx, "POST", "/wxa/getvoipsign", req, postWxaGetvoipsignErrCodes, true, core.SignNone)
}
