// Code generated by docsync from the official WeChat documentation. DO NOT EDIT.
// The API surface (names, request/response shapes) is derived deterministically
// from the endpoints; regenerate with "make docs-sync". If this file changes
// under you, the upstream documentation changed.

package miniprogram

import (
	"context"
	"github.com/go-sphere/weixin-api/core"
)

var postWxadramaBatchprocessdramapromotionErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统错误,请重试",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	1: {
		Desc:     "不存在",
		Solution: "",
	},
	2: {
		Desc:     "参数错误",
		Solution: "",
	},
	21000: {
		Desc:     "该剧未授权播放,请通过后台api进行授权",
		Solution: "",
	},
	21001: {
		Desc:     "用户加密的sessionkey不存在",
		Solution: "",
	},
	21002: {
		Desc:     "商家的加密包未进行base64编码",
		Solution: "",
	},
	21003: {
		Desc:     "解密商家加密包失败,请确认是否按接入文档中给出的加密方案加密或sessionkey要使用当前用户最新的",
		Solution: "",
	},
	21004: {
		Desc:     "商家加密前的明文不是合法的json格式或者字段类型不对,请按接入文档排查",
		Solution: "",
	},
	21005: {
		Desc:     "商家加密中的必填参数值(openid、src_appid及drama_id)为空",
		Solution: "",
	},
	21006: {
		Desc:     "播放器的入参与商家加密包中的参数值不匹配",
		Solution: "",
	},
	21007: {
		Desc:     "加密包中的openid无效",
		Solution: "",
	},
	21008: {
		Desc:     "21008 开发者未开启预拉取",
		Solution: "",
	},
	21009: {
		Desc:     "21009 商家流量不足",
		Solution: "",
	},
}

// PostWxadramaBatchprocessdramapromotion 批处理短剧合作推广计划 (POST /wxadrama/batchprocessdramapromotion)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/dramaOthersAPI/api_batchprocessdramapromotion.html
// PostWxadramaBatchprocessdramapromotionRequest carries the documented parameters of one API call.
type PostWxadramaBatchprocessdramapromotionRequest struct {
	// 操作类型。1-加入计划;2-查询计划;3-退出计划
	ActionType int64 `json:"action_type"`
	// 短剧数组
	List []*PostWxadramaBatchprocessdramapromotionRequestListObject `json:"list"`
}

// PostWxadramaBatchprocessdramapromotionRequestListObject is a documented nested object.
type PostWxadramaBatchprocessdramapromotionRequestListObject struct {
	// 提审方小程序的appid
	SrcAppID string `json:"src_appid"`
	// 提审的剧目id
	DramaID string `json:"drama_id"`
}

// PostWxadramaBatchprocessdramapromotionResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxadramaBatchprocessdramapromotionResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 短剧数组
	List []*PostWxadramaBatchprocessdramapromotionResponseListObject `json:"list,omitempty"`
}

// PostWxadramaBatchprocessdramapromotionResponseListObject is a documented nested object.
type PostWxadramaBatchprocessdramapromotionResponseListObject struct {
	// 提审方小程序的appid
	SrcAppID string `json:"src_appid,omitempty"`
	// 提审的剧目id
	DramaID string `json:"drama_id,omitempty"`
	// 短剧状态。 0-未加入计划;1-审核中;2-审核通过;3-审核拒绝;4-退出计划中;5-已被下架
	Status int64 `json:"status,omitzero"`
}

func (c *Client) PostWxadramaBatchprocessdramapromotion(ctx context.Context, req *PostWxadramaBatchprocessdramapromotionRequest) (*PostWxadramaBatchprocessdramapromotionResponse, error) {
	return core.Call[PostWxadramaBatchprocessdramapromotionResponse](c.EndpointClient, ctx, "POST", "/wxadrama/batchprocessdramapromotion", req, postWxadramaBatchprocessdramapromotionErrCodes, true, core.SignNone)
}

var postWxadramaDevelopergetiaadramaErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统错误,请重试",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	1: {
		Desc:     "不存在",
		Solution: "",
	},
	2: {
		Desc:     "参数错误",
		Solution: "",
	},
	21000: {
		Desc:     "该剧未授权播放,请通过后台api进行授权",
		Solution: "",
	},
	21001: {
		Desc:     "用户加密的sessionkey不存在",
		Solution: "",
	},
	21002: {
		Desc:     "商家的加密包未进行base64编码",
		Solution: "",
	},
	21003: {
		Desc:     "解密商家加密包失败,请确认是否按接入文档中给出的加密方案加密或sessionkey要使用当前用户最新的",
		Solution: "",
	},
	21004: {
		Desc:     "商家加密前的明文不是合法的json格式或者字段类型不对,请按接入文档排查",
		Solution: "",
	},
	21005: {
		Desc:     "商家加密中的必填参数值(openid、src_appid及drama_id)为空",
		Solution: "",
	},
	21006: {
		Desc:     "播放器的入参与商家加密包中的参数值不匹配",
		Solution: "",
	},
	21007: {
		Desc:     "加密包中的openid无效",
		Solution: "",
	},
	21008: {
		Desc:     "21008 开发者未开启预拉取",
		Solution: "",
	},
	21009: {
		Desc:     "21009 商家流量不足",
		Solution: "",
	},
}

// PostWxadramaDevelopergetiaadrama 获取短剧变现类型 (POST /wxadrama/developergetiaadrama)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/dramaOthersAPI/api_developergetiaadrama.html
// PostWxadramaDevelopergetiaadramaRequest carries the documented parameters of one API call.
type PostWxadramaDevelopergetiaadramaRequest struct {
	// list
	List []*PostWxadramaDevelopergetiaadramaRequestListObject `json:"list"`
}

// PostWxadramaDevelopergetiaadramaRequestListObject is a documented nested object.
type PostWxadramaDevelopergetiaadramaRequestListObject struct {
	// 提审方小程序的appid
	SrcAppID string `json:"src_appid"`
	// 提审的剧目id
	DramaID string `json:"drama_id"`
}

// PostWxadramaDevelopergetiaadramaResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxadramaDevelopergetiaadramaResponse struct {
	// list
	List []*PostWxadramaDevelopergetiaadramaResponseListObject `json:"list,omitempty"`
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

// PostWxadramaDevelopergetiaadramaResponseListObject is a documented nested object.
type PostWxadramaDevelopergetiaadramaResponseListObject struct {
	// 提审方小程序的appid
	SrcAppID string `json:"src_appid,omitempty"`
	// 提审的剧目id
	DramaID string `json:"drama_id,omitempty"`
	// 短剧变现类型。 1-纯IAA;2-纯IAP;3-IAAP混合变现
	IaaType int64 `json:"iaa_type,omitzero"`
	// 是否存在会员功能。 1-有;2-无
	VipFlag int64 `json:"vip_flag,omitzero"`
}

func (c *Client) PostWxadramaDevelopergetiaadrama(ctx context.Context, req *PostWxadramaDevelopergetiaadramaRequest) (*PostWxadramaDevelopergetiaadramaResponse, error) {
	return core.Call[PostWxadramaDevelopergetiaadramaResponse](c.EndpointClient, ctx, "POST", "/wxadrama/developergetiaadrama", req, postWxadramaDevelopergetiaadramaErrCodes, true, core.SignNone)
}

var postWxadramaDevelopergetpublisheddramaErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统错误,请重试",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	1: {
		Desc:     "不存在",
		Solution: "",
	},
	2: {
		Desc:     "参数错误",
		Solution: "",
	},
	21000: {
		Desc:     "该剧未授权播放,请通过后台api进行授权",
		Solution: "",
	},
	21001: {
		Desc:     "用户加密的sessionkey不存在",
		Solution: "",
	},
	21002: {
		Desc:     "商家的加密包未进行base64编码",
		Solution: "",
	},
	21003: {
		Desc:     "解密商家加密包失败,请确认是否按接入文档中给出的加密方案加密或sessionkey要使用当前用户最新的",
		Solution: "",
	},
	21004: {
		Desc:     "商家加密前的明文不是合法的json格式或者字段类型不对,请按接入文档排查",
		Solution: "",
	},
	21005: {
		Desc:     "商家加密中的必填参数值(openid、src_appid及drama_id)为空",
		Solution: "",
	},
	21006: {
		Desc:     "播放器的入参与商家加密包中的参数值不匹配",
		Solution: "",
	},
	21007: {
		Desc:     "加密包中的openid无效",
		Solution: "",
	},
	21008: {
		Desc:     "21008 开发者未开启预拉取",
		Solution: "",
	},
	21009: {
		Desc:     "21009 商家流量不足",
		Solution: "",
	},
}

// PostWxadramaDevelopergetpublisheddrama 获取已上架短剧 (POST /wxadrama/developergetpublisheddrama)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/dramaOthersAPI/api_developergetpublisheddrama.html
// PostWxadramaDevelopergetpublisheddramaRequest carries the documented parameters of one API call.
type PostWxadramaDevelopergetpublisheddramaRequest struct{}

// PostWxadramaDevelopergetpublisheddramaResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxadramaDevelopergetpublisheddramaResponse struct {
	// list
	List []*PostWxadramaDevelopergetpublisheddramaResponseListObject `json:"list,omitempty"`
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

// PostWxadramaDevelopergetpublisheddramaResponseListObject is a documented nested object.
type PostWxadramaDevelopergetpublisheddramaResponseListObject struct {
	// 提审方小程序的appid
	SrcAppID string `json:"src_appid,omitempty"`
	// 提审的剧目id
	DramaID string `json:"drama_id,omitempty"`
	// 上架时间戳(秒级别)
	PublishTime int64 `json:"publish_time,omitzero"`
}

func (c *Client) PostWxadramaDevelopergetpublisheddrama(ctx context.Context, req *PostWxadramaDevelopergetpublisheddramaRequest) (*PostWxadramaDevelopergetpublisheddramaResponse, error) {
	return core.Call[PostWxadramaDevelopergetpublisheddramaResponse](c.EndpointClient, ctx, "POST", "/wxadrama/developergetpublisheddrama", req, postWxadramaDevelopergetpublisheddramaErrCodes, true, core.SignNone)
}

var postWxadramaDeveloperpublishdramaErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统错误,请重试",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	1: {
		Desc:     "不存在",
		Solution: "",
	},
	2: {
		Desc:     "参数错误",
		Solution: "",
	},
	21000: {
		Desc:     "该剧未授权播放,请通过后台api进行授权",
		Solution: "",
	},
	21001: {
		Desc:     "用户加密的sessionkey不存在",
		Solution: "",
	},
	21002: {
		Desc:     "商家的加密包未进行base64编码",
		Solution: "",
	},
	21003: {
		Desc:     "解密商家加密包失败,请确认是否按接入文档中给出的加密方案加密或sessionkey要使用当前用户最新的",
		Solution: "",
	},
	21004: {
		Desc:     "商家加密前的明文不是合法的json格式或者字段类型不对,请按接入文档排查",
		Solution: "",
	},
	21005: {
		Desc:     "商家加密中的必填参数值(openid、src_appid及drama_id)为空",
		Solution: "",
	},
	21006: {
		Desc:     "播放器的入参与商家加密包中的参数值不匹配",
		Solution: "",
	},
	21007: {
		Desc:     "加密包中的openid无效",
		Solution: "",
	},
	21008: {
		Desc:     "21008 开发者未开启预拉取",
		Solution: "",
	},
	21009: {
		Desc:     "21009 商家流量不足",
		Solution: "",
	},
}

// PostWxadramaDeveloperpublishdrama 短剧上架 (POST /wxadrama/developerpublishdrama)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/dramaOthersAPI/api_developerpublishdrama.html
// PostWxadramaDeveloperpublishdramaRequest carries the documented parameters of one API call.
type PostWxadramaDeveloperpublishdramaRequest struct {
	// list
	List []*PostWxadramaDeveloperpublishdramaRequestListObject `json:"list"`
}

// PostWxadramaDeveloperpublishdramaRequestListObject is a documented nested object.
type PostWxadramaDeveloperpublishdramaRequestListObject struct {
	// 提审方小程序的appid
	SrcAppID string `json:"src_appid"`
	// 提审的剧目id
	DramaID string `json:"drama_id"`
	// 短剧名称
	DramaName string `json:"drama_name"`
	// 上架时间戳(秒级别)
	PublishTime int64 `json:"publish_time"`
}

// PostWxadramaDeveloperpublishdramaResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxadramaDeveloperpublishdramaResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxadramaDeveloperpublishdrama(ctx context.Context, req *PostWxadramaDeveloperpublishdramaRequest) (*PostWxadramaDeveloperpublishdramaResponse, error) {
	return core.Call[PostWxadramaDeveloperpublishdramaResponse](c.EndpointClient, ctx, "POST", "/wxadrama/developerpublishdrama", req, postWxadramaDeveloperpublishdramaErrCodes, true, core.SignNone)
}

var postWxadramaDevelopersetflushdramaErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统错误,请重试",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	1: {
		Desc:     "不存在",
		Solution: "",
	},
	2: {
		Desc:     "参数错误",
		Solution: "",
	},
	21000: {
		Desc:     "该剧未授权播放,请通过后台api进行授权",
		Solution: "",
	},
	21001: {
		Desc:     "用户加密的sessionkey不存在",
		Solution: "",
	},
	21002: {
		Desc:     "商家的加密包未进行base64编码",
		Solution: "",
	},
	21003: {
		Desc:     "解密商家加密包失败,请确认是否按接入文档中给出的加密方案加密或sessionkey要使用当前用户最新的",
		Solution: "",
	},
	21004: {
		Desc:     "商家加密前的明文不是合法的json格式或者字段类型不对,请按接入文档排查",
		Solution: "",
	},
	21005: {
		Desc:     "商家加密中的必填参数值(openid、src_appid及drama_id)为空",
		Solution: "",
	},
	21006: {
		Desc:     "播放器的入参与商家加密包中的参数值不匹配",
		Solution: "",
	},
	21007: {
		Desc:     "加密包中的openid无效",
		Solution: "",
	},
	21008: {
		Desc:     "21008 开发者未开启预拉取",
		Solution: "",
	},
	21009: {
		Desc:     "21009 商家流量不足",
		Solution: "",
	},
}

// PostWxadramaDevelopersetflushdrama 刷剧剧目设置 (POST /wxadrama/developersetflushdrama)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/dramaOthersAPI/api_developersetflushdrama.html
// PostWxadramaDevelopersetflushdramaRequest carries the documented parameters of one API call.
type PostWxadramaDevelopersetflushdramaRequest struct {
	// list
	List []*PostWxadramaDevelopersetflushdramaRequestListObject `json:"list"`
}

// PostWxadramaDevelopersetflushdramaRequestListObject is a documented nested object.
type PostWxadramaDevelopersetflushdramaRequestListObject struct {
	// 提审方小程序的appid
	SrcAppID string `json:"src_appid"`
	// 提审的剧目id
	DramaID string `json:"drama_id"`
	// 短剧名称
	DramaName string `json:"drama_name"`
}

// PostWxadramaDevelopersetflushdramaResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxadramaDevelopersetflushdramaResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxadramaDevelopersetflushdrama(ctx context.Context, req *PostWxadramaDevelopersetflushdramaRequest) (*PostWxadramaDevelopersetflushdramaResponse, error) {
	return core.Call[PostWxadramaDevelopersetflushdramaResponse](c.EndpointClient, ctx, "POST", "/wxadrama/developersetflushdrama", req, postWxadramaDevelopersetflushdramaErrCodes, true, core.SignNone)
}

var postWxadramaDevelopersetiaadramaErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统错误,请重试",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	1: {
		Desc:     "不存在",
		Solution: "",
	},
	2: {
		Desc:     "参数错误",
		Solution: "",
	},
	21000: {
		Desc:     "该剧未授权播放,请通过后台api进行授权",
		Solution: "",
	},
	21001: {
		Desc:     "用户加密的sessionkey不存在",
		Solution: "",
	},
	21002: {
		Desc:     "商家的加密包未进行base64编码",
		Solution: "",
	},
	21003: {
		Desc:     "解密商家加密包失败,请确认是否按接入文档中给出的加密方案加密或sessionkey要使用当前用户最新的",
		Solution: "",
	},
	21004: {
		Desc:     "商家加密前的明文不是合法的json格式或者字段类型不对,请按接入文档排查",
		Solution: "",
	},
	21005: {
		Desc:     "商家加密中的必填参数值(openid、src_appid及drama_id)为空",
		Solution: "",
	},
	21006: {
		Desc:     "播放器的入参与商家加密包中的参数值不匹配",
		Solution: "",
	},
	21007: {
		Desc:     "加密包中的openid无效",
		Solution: "",
	},
	21008: {
		Desc:     "21008 开发者未开启预拉取",
		Solution: "",
	},
	21009: {
		Desc:     "21009 商家流量不足",
		Solution: "",
	},
}

// PostWxadramaDevelopersetiaadrama 设置短剧变现类型 (POST /wxadrama/developersetiaadrama)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/dramaOthersAPI/api_developersetiaadrama.html
// PostWxadramaDevelopersetiaadramaRequest carries the documented parameters of one API call.
type PostWxadramaDevelopersetiaadramaRequest struct {
	// list
	List []*PostWxadramaDevelopersetiaadramaRequestListObject `json:"list"`
}

// PostWxadramaDevelopersetiaadramaRequestListObject is a documented nested object.
type PostWxadramaDevelopersetiaadramaRequestListObject struct {
	// 提审方小程序的appid
	SrcAppID string `json:"src_appid"`
	// 提审的剧目id
	DramaID string `json:"drama_id"`
	// 短剧变现类型。 1-纯IAA;2-纯IAP;3-IAAP混合变现
	IaaType int64 `json:"iaa_type"`
	// 是否存在会员功能。 1-有;2-无
	VipFlag int64 `json:"vip_flag"`
}

// PostWxadramaDevelopersetiaadramaResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxadramaDevelopersetiaadramaResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxadramaDevelopersetiaadrama(ctx context.Context, req *PostWxadramaDevelopersetiaadramaRequest) (*PostWxadramaDevelopersetiaadramaResponse, error) {
	return core.Call[PostWxadramaDevelopersetiaadramaResponse](c.EndpointClient, ctx, "POST", "/wxadrama/developersetiaadrama", req, postWxadramaDevelopersetiaadramaErrCodes, true, core.SignNone)
}

var postWxadramaDevelopersetrecmddramaErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统错误,请重试",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	1: {
		Desc:     "不存在",
		Solution: "",
	},
	2: {
		Desc:     "参数错误",
		Solution: "",
	},
	21000: {
		Desc:     "该剧未授权播放,请通过后台api进行授权",
		Solution: "",
	},
	21001: {
		Desc:     "用户加密的sessionkey不存在",
		Solution: "",
	},
	21002: {
		Desc:     "商家的加密包未进行base64编码",
		Solution: "",
	},
	21003: {
		Desc:     "解密商家加密包失败,请确认是否按接入文档中给出的加密方案加密或sessionkey要使用当前用户最新的",
		Solution: "",
	},
	21004: {
		Desc:     "商家加密前的明文不是合法的json格式或者字段类型不对,请按接入文档排查",
		Solution: "",
	},
	21005: {
		Desc:     "商家加密中的必填参数值(openid、src_appid及drama_id)为空",
		Solution: "",
	},
	21006: {
		Desc:     "播放器的入参与商家加密包中的参数值不匹配",
		Solution: "",
	},
	21007: {
		Desc:     "加密包中的openid无效",
		Solution: "",
	},
	21008: {
		Desc:     "21008 开发者未开启预拉取",
		Solution: "",
	},
	21009: {
		Desc:     "21009 商家流量不足",
		Solution: "",
	},
}

// PostWxadramaDevelopersetrecmddrama 推荐剧目 (POST /wxadrama/developersetrecmddrama)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/dramaOthersAPI/api_developersetrecmddrama.html
// PostWxadramaDevelopersetrecmddramaRequest carries the documented parameters of one API call.
type PostWxadramaDevelopersetrecmddramaRequest struct {
	// 1-剧结束 2-选集最右侧推荐 3-剧集profile页相关推荐
	EntryType int64 `json:"entry_type"`
	// 提审方小程序的appid
	SrcAppID string `json:"src_appid,omitempty"`
	// 提审的剧目id
	DramaID string `json:"drama_id,omitempty"`
	// list
	List []*PostWxadramaDevelopersetrecmddramaRequestListObject `json:"list,omitempty"`
}

// PostWxadramaDevelopersetrecmddramaRequestListObject is a documented nested object.
type PostWxadramaDevelopersetrecmddramaRequestListObject struct {
	// 提审方小程序的appid
	SrcAppID string `json:"src_appid"`
	// 提审的剧目id
	DramaID string `json:"drama_id"`
}

// PostWxadramaDevelopersetrecmddramaResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxadramaDevelopersetrecmddramaResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxadramaDevelopersetrecmddrama(ctx context.Context, req *PostWxadramaDevelopersetrecmddramaRequest) (*PostWxadramaDevelopersetrecmddramaResponse, error) {
	return core.Call[PostWxadramaDevelopersetrecmddramaResponse](c.EndpointClient, ctx, "POST", "/wxadrama/developersetrecmddrama", req, postWxadramaDevelopersetrecmddramaErrCodes, true, core.SignNone)
}

var postWxadramaGetfindereventErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统错误,请重试",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	1: {
		Desc:     "不存在",
		Solution: "",
	},
	2: {
		Desc:     "参数错误",
		Solution: "",
	},
	21000: {
		Desc:     "该剧未授权播放,请通过后台api进行授权",
		Solution: "",
	},
	21001: {
		Desc:     "用户加密的sessionkey不存在",
		Solution: "",
	},
	21002: {
		Desc:     "商家的加密包未进行base64编码",
		Solution: "",
	},
	21003: {
		Desc:     "解密商家加密包失败,请确认是否按接入文档中给出的加密方案加密或sessionkey要使用当前用户最新的",
		Solution: "",
	},
	21004: {
		Desc:     "商家加密前的明文不是合法的json格式或者字段类型不对,请按接入文档排查",
		Solution: "",
	},
	21005: {
		Desc:     "商家加密中的必填参数值(openid、src_appid及drama_id)为空",
		Solution: "",
	},
	21006: {
		Desc:     "播放器的入参与商家加密包中的参数值不匹配",
		Solution: "",
	},
	21007: {
		Desc:     "加密包中的openid无效",
		Solution: "",
	},
	21008: {
		Desc:     "21008 开发者未开启预拉取",
		Solution: "",
	},
	21009: {
		Desc:     "21009 商家流量不足",
		Solution: "",
	},
}

// PostWxadramaGetfinderevent 获取短剧合作推广活动 (POST /wxadrama/getfinderevent)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/dramaOthersAPI/api_getfinderevent.html
// PostWxadramaGetfindereventRequest carries the documented parameters of one API call.
type PostWxadramaGetfindereventRequest struct {
	// 筛选短剧合作推广活动
	EventIDList []string `json:"event_id_list,omitempty"`
}

// PostWxadramaGetfindereventResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxadramaGetfindereventResponse struct {
	// 推广计划数组
	FinderEventList []*PostWxadramaGetfindereventResponseFinderEventListObject `json:"finder_event_list,omitempty"`
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

// PostWxadramaGetfindereventResponseFinderEventListObject is a documented nested object.
type PostWxadramaGetfindereventResponseFinderEventListObject struct {
	// 活动id
	EncryptedEventID string `json:"encrypted_event_id,omitempty"`
	// 活动名
	EventName string `json:"event_name,omitempty"`
	// 活动链接
	EventURL string `json:"event_url,omitempty"`
	// 提审小程序id
	SrcAppID string `json:"src_appid,omitempty"`
	// 提审剧目id
	DramaID string `json:"drama_id,omitempty"`
}

func (c *Client) PostWxadramaGetfinderevent(ctx context.Context, req *PostWxadramaGetfindereventRequest) (*PostWxadramaGetfindereventResponse, error) {
	return core.Call[PostWxadramaGetfindereventResponse](c.EndpointClient, ctx, "POST", "/wxadrama/getfinderevent", req, postWxadramaGetfindereventErrCodes, true, core.SignNone)
}

var postWxadramaSetplayerdramarecmdswitchErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统错误,请重试",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	1: {
		Desc:     "不存在",
		Solution: "",
	},
	2: {
		Desc:     "参数错误",
		Solution: "",
	},
	21000: {
		Desc:     "该剧未授权播放,请通过后台api进行授权",
		Solution: "",
	},
	21001: {
		Desc:     "用户加密的sessionkey不存在",
		Solution: "",
	},
	21002: {
		Desc:     "商家的加密包未进行base64编码",
		Solution: "",
	},
	21003: {
		Desc:     "解密商家加密包失败,请确认是否按接入文档中给出的加密方案加密或sessionkey要使用当前用户最新的",
		Solution: "",
	},
	21004: {
		Desc:     "商家加密前的明文不是合法的json格式或者字段类型不对,请按接入文档排查",
		Solution: "",
	},
	21005: {
		Desc:     "商家加密中的必填参数值(openid、src_appid及drama_id)为空",
		Solution: "",
	},
	21006: {
		Desc:     "播放器的入参与商家加密包中的参数值不匹配",
		Solution: "",
	},
	21007: {
		Desc:     "加密包中的openid无效",
		Solution: "",
	},
	21008: {
		Desc:     "21008 开发者未开启预拉取",
		Solution: "",
	},
	21009: {
		Desc:     "21009 商家流量不足",
		Solution: "",
	},
}

// PostWxadramaSetplayerdramarecmdswitch 播放原始视频-推荐位控制接口 (POST /wxadrama/setplayerdramarecmdswitch)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/dramaOthersAPI/api_setplayerdramarecmdswitch.html
// PostWxadramaSetplayerdramarecmdswitchRequest carries the documented parameters of one API call.
type PostWxadramaSetplayerdramarecmdswitchRequest struct {
	// 此处填2002(当需要控制推荐位时,可选值为:1-剧结束 2-选集最右侧推荐 3-剧集profile页相关推荐)
	EntryType int64 `json:"entry_type"`
	// true-打开 false-关闭,没有打开过的都默认为关闭(当需要控制推荐位时:true-打开 false-关闭,1-剧结束&3-剧集profile页默认打开)
	SwitchStatus bool `json:"switch_status"`
}

// PostWxadramaSetplayerdramarecmdswitchResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxadramaSetplayerdramarecmdswitchResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxadramaSetplayerdramarecmdswitch(ctx context.Context, req *PostWxadramaSetplayerdramarecmdswitchRequest) (*PostWxadramaSetplayerdramarecmdswitchResponse, error) {
	return core.Call[PostWxadramaSetplayerdramarecmdswitchResponse](c.EndpointClient, ctx, "POST", "/wxadrama/setplayerdramarecmdswitch", req, postWxadramaSetplayerdramarecmdswitchErrCodes, true, core.SignNone)
}
