// Code generated by docsync from the official WeChat documentation. DO NOT EDIT.
// The API surface (names, request/response shapes) is derived deterministically
// from the endpoints; regenerate with "make docs-sync". If this file changes
// under you, the upstream documentation changed.

package miniprogram

import (
	"context"
	"github.com/go-sphere/weixin-api/core"
)

var postCgiBinExpressLocalBusinessDeliveryGetallErrCodes = map[int]core.ErrDoc{40001: {
	Desc:     "invalid credential access_token isinvalid or not latest",
	Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
}}

// PostCgiBinExpressLocalBusinessDeliveryGetall 获取已支持的配送公司列表 (POST /cgi-bin/express/local/business/delivery/getall)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_getallimmedelivery.html
// PostCgiBinExpressLocalBusinessDeliveryGetallRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessDeliveryGetallRequest struct{}

// PostCgiBinExpressLocalBusinessDeliveryGetallResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessDeliveryGetallResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
	// 配送公司列表
	List []*PostCgiBinExpressLocalBusinessDeliveryGetallResponseListObject `json:"list,omitempty"`
}

// PostCgiBinExpressLocalBusinessDeliveryGetallResponseListObject is a documented nested object.
type PostCgiBinExpressLocalBusinessDeliveryGetallResponseListObject struct {
	// 配送公司Id
	DeliveryID string `json:"delivery_id,omitempty"`
	// 配送公司名称
	DeliveryName string `json:"delivery_name,omitempty"`
}

func (c *Client) PostCgiBinExpressLocalBusinessDeliveryGetall(ctx context.Context, req *PostCgiBinExpressLocalBusinessDeliveryGetallRequest) (*PostCgiBinExpressLocalBusinessDeliveryGetallResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessDeliveryGetallResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/delivery/getall", req, postCgiBinExpressLocalBusinessDeliveryGetallErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessOpenErrCodes = map[int]core.ErrDoc{40001: {
	Desc:     "invalid credential access_token isinvalid or not latest",
	Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
}}

// PostCgiBinExpressLocalBusinessOpen 申请开通即时配送 (POST /cgi-bin/express/local/business/open)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_opendelivery.html
// PostCgiBinExpressLocalBusinessOpenRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessOpenRequest struct{}

// PostCgiBinExpressLocalBusinessOpenResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessOpenResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
}

func (c *Client) PostCgiBinExpressLocalBusinessOpen(ctx context.Context, req *PostCgiBinExpressLocalBusinessOpenRequest) (*PostCgiBinExpressLocalBusinessOpenResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessOpenResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/open", req, postCgiBinExpressLocalBusinessOpenErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessOrderAddErrCodes = map[int]core.ErrDoc{
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	9300535: {
		Desc:     "shop字段商品缩略图 url、商品名称为空或者非法,或者商品数量为0",
		Solution: "",
	},
	930555: {
		Desc:     "微信平台系统错误",
		Solution: "",
	},
	930556: {
		Desc:     "配送公司超时",
		Solution: "",
	},
	930557: {
		Desc:     "配送公司系统错误",
		Solution: "",
	},
	930558: {
		Desc:     "配送公司逻辑错误",
		Solution: "",
	},
	930559: {
		Desc:     "openid无效",
		Solution: "",
	},
	930560: {
		Desc:     "未绑定的商户号",
		Solution: "",
	},
	930561: {
		Desc:     "参数错误",
		Solution: "",
	},
	930562: {
		Desc:     "配送单已经存在",
		Solution: "",
	},
	930563: {
		Desc:     "配送单不存在",
		Solution: "",
	},
	930564: {
		Desc:     "调用无配额",
		Solution: "",
	},
	930565: {
		Desc:     "配送单已结束",
		Solution: "",
	},
}

// PostCgiBinExpressLocalBusinessOrderAdd 添加配送单 (POST /cgi-bin/express/local/business/order/add)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_addlocalorder.html
// PostCgiBinExpressLocalBusinessOrderAddRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessOrderAddRequest struct {
	// 商家id,由配送公司分配的appkey
	Shopid string `json:"shopid"`
	// 唯一标识订单的 ID,由商户生成, 不超过128字节
	ShopOrderID string `json:"shop_order_id"`
	// 配送公司ID
	DeliveryID string `json:"delivery_id"`
	// 下单用户的openid
	OpenID string `json:"openid"`
	// 发件人信息,顺丰同城急送必须填写,美团配送、达达、闪送,若传了shop_no的值可不填该字段
	Sender *PostCgiBinExpressLocalBusinessOrderAddRequestSenderObject `json:"sender"`
	// 收件人信息
	Receiver *PostCgiBinExpressLocalBusinessOrderAddRequestReceiverObject `json:"receiver"`
	// 货物信息
	Cargo *PostCgiBinExpressLocalBusinessOrderAddRequestCargoObject `json:"cargo"`
	// 订单信息
	OrderInfo *PostCgiBinExpressLocalBusinessOrderAddRequestOrderInfoObject `json:"order_info"`
	// 商品信息,会展示到物流通知消息中
	Shop *PostCgiBinExpressLocalBusinessOrderAddRequestShopObject `json:"shop"`
	// 预下单接口返回的参数,配送公司可保证在一段时间内运费不变
	DeliveryToken string `json:"delivery_token"`
	// 用配送公司提供的appSecret加密的校验串,见注意事项
	DeliverySign string `json:"delivery_sign"`
	// 商家门店编号,在配送公司登记,如果只有一个门店,美团闪送必填, 值为店铺id
	ShopNo string `json:"shop_no"`
	// 子商户id,区分小程序内部多个子商户
	SubBizID string `json:"sub_biz_id,omitempty"`
}

// PostCgiBinExpressLocalBusinessOrderAddRequestSenderObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderAddRequestSenderObject struct {
	// 姓名,最长不超过256个字符
	Name string `json:"name"`
	// 城市名称,如广州市
	City string `json:"city"`
	// 地址(街道、小区、大厦等,用于定位)
	Address string `json:"address"`
	// 地址详情(楼号、单元号、层号)
	AddressDetail string `json:"address_detail"`
	// 电话/手机号,最长不超过64个字符
	Phone string `json:"phone"`
	// 经度(火星坐标或百度坐标,和 coordinate_type 字段配合使用,确到小数点后6位
	Lng float64 `json:"lng"`
	// 纬度(火星坐标或百度坐标,和 coordinate_type 字段配合使用,精确到小数点后6位)
	Lat float64 `json:"lat"`
	// 坐标类型,0:火星坐标(高德,腾讯地图均采用火星坐标) 1:百度坐标
	CoordinateType float64 `json:"coordinate_type,omitzero"`
}

// PostCgiBinExpressLocalBusinessOrderAddRequestReceiverObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderAddRequestReceiverObject struct {
	// 姓名,最长不超过256个字符
	Name string `json:"name"`
	// 城市名称,如广州市
	City string `json:"city"`
	// 地址(街道、小区、大厦等,用于定位)
	Address string `json:"address"`
	// 地址详情(楼号、单元号、层号)
	AddressDetail string `json:"address_detail"`
	// 电话/手机号,最长不超过64个字符
	Phone string `json:"phone"`
	// 经度(火星坐标或百度坐标,和 coordinate_type 字段配合使用,确到小数点后6位
	Lng float64 `json:"lng"`
	// 纬度(火星坐标或百度坐标,和 coordinate_type 字段配合使用,精确到小数点后6位)
	Lat float64 `json:"lat"`
	// 坐标类型,0:火星坐标(高德,腾讯地图均采用火星坐标) 1:百度坐标
	CoordinateType float64 `json:"coordinate_type,omitzero"`
}

// PostCgiBinExpressLocalBusinessOrderAddRequestCargoObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderAddRequestCargoObject struct {
	// 货物价格,单位为元,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-5000]
	GoodsValue float64 `json:"goods_value"`
	// 货物高度,单位为cm,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-45]
	GoodsHeight float64 `json:"goods_height,omitzero"`
	// 货物宽度,单位为cm,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-50]
	GoodsWidth float64 `json:"goods_width,omitzero"`
	// 货物长度,单位为cm,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-65]
	GoodsLength float64 `json:"goods_length,omitzero"`
	// 货物重量,单位为kg,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-50]
	GoodsWeight float64 `json:"goods_weight"`
	// 货物详情,最长不超过10240个字符
	GoodsDetail *PostCgiBinExpressLocalBusinessOrderAddRequestGoodsDetailObject `json:"goods_detail,omitempty"`
	// 货物取货信息,用于骑手到店取货,最长不超过100个字符
	GoodsPickupInfo string `json:"goods_pickup_info,omitempty"`
	// 品类一级类目
	CargoFirstClass string `json:"cargo_first_class"`
	// 品类二级类目
	CargoSecondClass string `json:"cargo_second_class"`
}

// PostCgiBinExpressLocalBusinessOrderAddRequestGoodsDetailObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderAddRequestGoodsDetailObject struct {
	// 货物列表
	Goods []*PostCgiBinExpressLocalBusinessOrderAddRequestGoodsObject `json:"goods"`
}

// PostCgiBinExpressLocalBusinessOrderAddRequestGoodsObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderAddRequestGoodsObject struct {
	// 货物数量
	GoodCount int64 `json:"good_count"`
	// 货品名称
	GoodName string `json:"good_name"`
	// 货品单价,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数)
	GoodPrice float64 `json:"good_price,omitzero"`
	// 货品单位,最长不超过20个字符
	GoodUnit string `json:"good_unit,omitempty"`
}

// PostCgiBinExpressLocalBusinessOrderAddRequestOrderInfoObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderAddRequestOrderInfoObject struct {
	// 配送服务代码 不同配送公司自定义, 顺丰和达达不填
	DeliveryServiceCode string `json:"delivery_service_code,omitempty"`
	// 期望派单时间(达达支持,表示达达系统调度时间, 到那个时间才会有状态更新的回调通知),unix-timestamp, 比如1586342180
	ExpectedDeliveryTime int64 `json:"expected_delivery_time,omitzero"`
	// 订单类型, 0: 即时单 1 预约单,如预约单,需要设置expected_delivery_time或expected_finish_time或expected_pick_time
	OrderType int64 `json:"order_type,omitzero"`
	// 门店订单流水号,建议提供,方便骑手门店取货,最长不超过32个字符
	PoiSeq string `json:"poi_seq,omitempty"`
	// 备注,最长不超过200个字符
	Note string `json:"note,omitempty"`
	// 用户下单付款时间, 顺丰必填, 比如1555220757
	OrderTime int64 `json:"order_time,omitzero"`
	// 是否保价,0,非保价,1.保价
	IsInsured int64 `json:"is_insured,omitzero"`
	// 保价金额,单位为元,精确到分
	DeclaredValue int64 `json:"declared_value,omitzero"`
	// 小费,单位为元, 下单一般不加小费
	Tips int64 `json:"tips,omitzero"`
	// 是否选择直拿直送(0:不需要;1:需要。选择直拿直送后,同一时间骑手只能配送此订单至完成,配送费用也相应高一些,闪送必须选1,达达可选0或1,其余配送公司不支持直拿直送)
	IsDirectDelivery int64 `json:"is_direct_delivery,omitzero"`
	// 骑手应付金额,单位为元,精确到分
	CashOnDelivery int64 `json:"cash_on_delivery,omitzero"`
	// 骑手应收金额,单位为元,精确到分
	CashOnPickup int64 `json:"cash_on_pickup,omitzero"`
	// 物流流向,1:从门店取件送至用户;2:从用户取件送至门店
	RiderPickMethod int64 `json:"rider_pick_method,omitzero"`
	// 收货码(0:不需要;1:需要。收货码的作用是:骑手必须输入收货码才能完成订单妥投)
	IsFinishCodeNeeded int64 `json:"is_finish_code_needed,omitzero"`
	// 取货码(0:不需要;1:需要。取货码的作用是:骑手必须输入取货码才能从商家取货)
	IsPickupCodeNeeded int64 `json:"is_pickup_code_needed,omitzero"`
	// 期望送达时间(美团、顺丰同城急送支持),unix-timestamp, 比如1586342180
	ExpectedFinishTime int64 `json:"expected_finish_time,omitzero"`
	// 期望取件时间(闪送、顺丰同城急送支持,闪送需要设置两个小时后的时间,顺丰同城急送只需传expected_finish_time或expected_pick_time其中之一即可,同时都传则以expected_finish_time为准),unix-timestamp, 比如1586342180
	ExpectedPickTime int64 `json:"expected_pick_time,omitzero"`
}

// PostCgiBinExpressLocalBusinessOrderAddRequestShopObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderAddRequestShopObject struct {
	// 商家小程序的路径,建议为订单页面
	WxaPath string `json:"wxa_path,omitempty"`
	// 商品缩略图 url;shop.detail_list为空则必传,shop.detail_list非空可不传。
	ImgURL string `json:"img_url,omitempty"`
	// 商品名称, 不超过128字节;shop.detail_list为空则必传,shop.detail_list非空可不传。
	GoodsName string `json:"goods_name,omitempty"`
	// 商品数量;shop.detail_list为空则必传。shop.detail_list非空可不传,默认取shop.detail_list的size
	GoodsCount int64 `json:"goods_count,omitzero"`
	// 该参数在【即使配送】的addOrder接口才生效。若结算方式为:第三方向配送公司统一结算,商户后续和第三方结算,则该参数必填;在该结算模式下,第三方用自己的开发小程序替授权商户发起下单,并将授权小程序的appid给平台,后续配送通知中可回流授权商户小程序。
	WxaAppID string `json:"wxa_appid,omitempty"`
}

// PostCgiBinExpressLocalBusinessOrderAddResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessOrderAddResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
	// 实际运费(单位:元),运费减去优惠券费用
	Fee int64 `json:"fee,omitzero"`
	// 运费(单位:元)
	Deliverfee int64 `json:"deliverfee,omitzero"`
	// 优惠券费用(单位:元)
	Couponfee int64 `json:"couponfee,omitzero"`
	// 小费(单位:元)
	Tips int64 `json:"tips,omitzero"`
	// 保价费(单位:元)
	Insurancfee int64 `json:"insurancfee,omitzero"`
	// 配送距离(整数单位:米)
	Distance int64 `json:"distance,omitzero"`
	// 配送单号
	WaybillID string `json:"waybill_id,omitempty"`
	// 配送状态。
	OrderStatus int64 `json:"order_status,omitzero"`
	// 收货码
	FinishCode int64 `json:"finish_code,omitzero"`
	// 取货码
	PickupCode int64 `json:"pickup_code,omitzero"`
	// 预计骑手接单时间,单位秒,比如5分钟,就填300, 无法预计填0
	DispatchDuration int64 `json:"dispatch_duration,omitzero"`
}

func (c *Client) PostCgiBinExpressLocalBusinessOrderAdd(ctx context.Context, req *PostCgiBinExpressLocalBusinessOrderAddRequest) (*PostCgiBinExpressLocalBusinessOrderAddResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessOrderAddResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/order/add", req, postCgiBinExpressLocalBusinessOrderAddErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessOrderAddtipsErrCodes = map[int]core.ErrDoc{-1: {
	Desc:     "system error",
	Solution: "系统繁忙,此时请开发者稍候再试",
}}

// PostCgiBinExpressLocalBusinessOrderAddtips 添加小费 (POST /cgi-bin/express/local/business/order/addtips)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_addtips.html
// PostCgiBinExpressLocalBusinessOrderAddtipsRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessOrderAddtipsRequest struct {
	// 商家id, 由配送公司分配的appkey
	Shopid string `json:"shopid"`
	// 唯一标识订单的 ID,由商户生成
	ShopOrderID string `json:"shop_order_id"`
	// 配送单id
	WaybillID string `json:"waybill_id"`
	// 小费金额(单位:元) 各家配送公司最大值不同
	Tips int64 `json:"tips"`
	// 备注
	Remark string `json:"remark"`
	// 用配送公司提供的appSecret加密的校验串说明
	DeliverySign string `json:"delivery_sign"`
	// 商家门店编号,在配送公司登记,如果只有一个门店,闪送shop_no必填,值为店铺id
	ShopNo string `json:"shop_no"`
}

// PostCgiBinExpressLocalBusinessOrderAddtipsResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessOrderAddtipsResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
}

func (c *Client) PostCgiBinExpressLocalBusinessOrderAddtips(ctx context.Context, req *PostCgiBinExpressLocalBusinessOrderAddtipsRequest) (*PostCgiBinExpressLocalBusinessOrderAddtipsResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessOrderAddtipsResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/order/addtips", req, postCgiBinExpressLocalBusinessOrderAddtipsErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessOrderCancelErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	9300535: {
		Desc:     "shop字段商品缩略图 url、商品名称为空或者非法,或者商品数量为0",
		Solution: "",
	},
	930555: {
		Desc:     "微信平台系统错误",
		Solution: "",
	},
	930556: {
		Desc:     "配送公司超时",
		Solution: "",
	},
	930557: {
		Desc:     "配送公司系统错误",
		Solution: "",
	},
	930558: {
		Desc:     "配送公司逻辑错误",
		Solution: "",
	},
	930559: {
		Desc:     "openid无效",
		Solution: "",
	},
	930560: {
		Desc:     "未绑定的商户号",
		Solution: "",
	},
	930561: {
		Desc:     "参数错误",
		Solution: "",
	},
	930562: {
		Desc:     "配送单已经存在",
		Solution: "",
	},
	930563: {
		Desc:     "配送单不存在",
		Solution: "",
	},
	930564: {
		Desc:     "调用无配额",
		Solution: "",
	},
	930565: {
		Desc:     "配送单已结束",
		Solution: "",
	},
}

// PostCgiBinExpressLocalBusinessOrderCancel 取消配送单 (POST /cgi-bin/express/local/business/order/cancel)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_cancellocalorder.html
// PostCgiBinExpressLocalBusinessOrderCancelRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessOrderCancelRequest struct {
	// 商家id, 由配送公司分配的appkey
	Shopid string `json:"shopid"`
	// 唯一标识订单的 ID,由商户生成
	ShopOrderID string `json:"shop_order_id"`
	// 快递公司ID
	DeliveryID string `json:"delivery_id"`
	// 配送单id(顺丰同城必填)
	WaybillID string `json:"waybill_id,omitempty"`
	// 取消原因Id。1表示暂时不需要邮寄;2表示价格不合适;3表示订单信息有误,重新下单;4表示骑手取货不及时;5表示骑手配送不及时;6表示其他原因( 如果选择6,需要填写取消原因,否则不需要填写 )
	CancelReasonID int64 `json:"cancel_reason_id"`
	// 取消原因
	CancelReason string `json:"cancel_reason"`
	// 商家门店编号,如果只有一个门店,闪送shop_no必填,值为店铺id
	ShopNo string `json:"shop_no"`
	// 用配送公司提供的appSecret加密的校验串,见注意事项
	DeliverySign string `json:"delivery_sign"`
}

// PostCgiBinExpressLocalBusinessOrderCancelResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessOrderCancelResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
	// 扣除的违约金(单位:元),精确到分
	DeductFee int64 `json:"deduct_fee,omitzero"`
	// 说明
	Desc string `json:"desc,omitempty"`
}

func (c *Client) PostCgiBinExpressLocalBusinessOrderCancel(ctx context.Context, req *PostCgiBinExpressLocalBusinessOrderCancelRequest) (*PostCgiBinExpressLocalBusinessOrderCancelResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessOrderCancelResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/order/cancel", req, postCgiBinExpressLocalBusinessOrderCancelErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessOrderConfirmReturnErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	9300535: {
		Desc:     "shop字段商品缩略图 url、商品名称为空或者非法,或者商品数量为0",
		Solution: "",
	},
	930555: {
		Desc:     "微信平台系统错误",
		Solution: "",
	},
	930556: {
		Desc:     "配送公司超时",
		Solution: "",
	},
	930557: {
		Desc:     "配送公司系统错误",
		Solution: "",
	},
	930558: {
		Desc:     "配送公司逻辑错误",
		Solution: "",
	},
	930559: {
		Desc:     "openid无效",
		Solution: "",
	},
	930560: {
		Desc:     "未绑定的商户号",
		Solution: "",
	},
	930561: {
		Desc:     "参数错误",
		Solution: "",
	},
	930562: {
		Desc:     "配送单已经存在",
		Solution: "",
	},
	930563: {
		Desc:     "配送单不存在",
		Solution: "",
	},
	930564: {
		Desc:     "调用无配额",
		Solution: "",
	},
	930565: {
		Desc:     "配送单已结束",
		Solution: "",
	},
}

// PostCgiBinExpressLocalBusinessOrderConfirmReturn 异常件退回商家确认 (POST /cgi-bin/express/local/business/order/confirm_return)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_abnormalconfirm.html
// PostCgiBinExpressLocalBusinessOrderConfirmReturnRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessOrderConfirmReturnRequest struct {
	// 商家id,由配送公司分配的appkey
	Shopid string `json:"shopid"`
	// 唯一标识订单的 ID,由商户生成
	ShopOrderID string `json:"shop_order_id"`
	// 配送单id
	WaybillID string `json:"waybill_id"`
	// 用配送公司提供的appSecret加密的校验串,见注意事项
	DeliverySign string `json:"delivery_sign"`
	// 商家门店编号,在配送公司登记,闪送必填,值为店铺id
	ShopNo string `json:"shop_no"`
	// 备注
	Remark string `json:"remark,omitempty"`
}

// PostCgiBinExpressLocalBusinessOrderConfirmReturnResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessOrderConfirmReturnResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
}

func (c *Client) PostCgiBinExpressLocalBusinessOrderConfirmReturn(ctx context.Context, req *PostCgiBinExpressLocalBusinessOrderConfirmReturnRequest) (*PostCgiBinExpressLocalBusinessOrderConfirmReturnResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessOrderConfirmReturnResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/order/confirm_return", req, postCgiBinExpressLocalBusinessOrderConfirmReturnErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessOrderGetErrCodes = map[int]core.ErrDoc{
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	9300535: {
		Desc:     "shop字段商品缩略图 url、商品名称为空或者非法,或者商品数量为0",
		Solution: "",
	},
	930555: {
		Desc:     "微信平台系统错误",
		Solution: "",
	},
	930556: {
		Desc:     "配送公司超时",
		Solution: "",
	},
	930557: {
		Desc:     "配送公司系统错误",
		Solution: "",
	},
	930558: {
		Desc:     "配送公司逻辑错误",
		Solution: "",
	},
	930559: {
		Desc:     "openid无效",
		Solution: "",
	},
	930560: {
		Desc:     "未绑定的商户号",
		Solution: "",
	},
	930561: {
		Desc:     "参数错误",
		Solution: "",
	},
	930562: {
		Desc:     "配送单已经存在",
		Solution: "",
	},
	930563: {
		Desc:     "配送单不存在",
		Solution: "",
	},
	930564: {
		Desc:     "调用无配额",
		Solution: "",
	},
	930565: {
		Desc:     "配送单已结束",
		Solution: "",
	},
}

// PostCgiBinExpressLocalBusinessOrderGet 拉取配送单信息 (POST /cgi-bin/express/local/business/order/get)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_getlocalorder.html
// PostCgiBinExpressLocalBusinessOrderGetRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessOrderGetRequest struct {
	// 商家id, 由配送公司分配的appkey
	Shopid string `json:"shopid"`
	// 唯一标识订单的 ID,由商户生成
	ShopOrderID string `json:"shop_order_id"`
	// 商家门店编号, 在配送公司登记,如果只有一个门店,可以不填
	ShopNo string `json:"shop_no"`
	// 用配送公司提供的appSecret加密的校验串,见注意事项
	DeliverySign string `json:"delivery_sign"`
}

// PostCgiBinExpressLocalBusinessOrderGetResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessOrderGetResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
	// 配送状态
	OrderStatus int64 `json:"order_status,omitzero"`
	// 配送单号
	WaybillID string `json:"waybill_id,omitempty"`
	// 骑手姓名
	RiderName string `json:"rider_name,omitempty"`
	// 骑手电话
	RiderPhone string `json:"rider_phone,omitempty"`
	// 骑手位置经度, 配送中时返回
	RiderLng int64 `json:"rider_lng,omitzero"`
	// 骑手位置纬度, 配送中时返回
	RiderLat int64 `json:"rider_lat,omitzero"`
	// 预计还剩多久送达时间, 配送中时返回,单位秒, 已取货配送中需返回,比如5分钟后送达,填300
	ReachTime int64 `json:"reach_time,omitzero"`
}

func (c *Client) PostCgiBinExpressLocalBusinessOrderGet(ctx context.Context, req *PostCgiBinExpressLocalBusinessOrderGetRequest) (*PostCgiBinExpressLocalBusinessOrderGetResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessOrderGetResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/order/get", req, postCgiBinExpressLocalBusinessOrderGetErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessOrderPreAddErrCodes = map[int]core.ErrDoc{40001: {
	Desc:     "invalid credential access_token isinvalid or not latest",
	Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
}}

// PostCgiBinExpressLocalBusinessOrderPreAdd 预下配送单 (POST /cgi-bin/express/local/business/order/pre_add)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_preaddorder.html
// PostCgiBinExpressLocalBusinessOrderPreAddRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessOrderPreAddRequest struct {
	// 商家id, 由配送公司分配的appkey
	Shopid string `json:"shopid"`
	// 唯一标识订单的 ID,由商户生成, 不超过128字节
	ShopOrderID string `json:"shop_order_id"`
	// 配送公司ID
	DeliveryID string `json:"delivery_id"`
	// 下单用户的openid
	OpenID string `json:"openid"`
	// 发件人信息,闪送、顺丰同城急送必须填写,美团配送、达达,若传了shop_no的值可不填该字段
	Sender *PostCgiBinExpressLocalBusinessOrderPreAddRequestSenderObject `json:"sender"`
	// 收件人信息
	Receiver *PostCgiBinExpressLocalBusinessOrderPreAddRequestReceiverObject `json:"receiver"`
	// 货物信息
	Cargo *PostCgiBinExpressLocalBusinessOrderPreAddRequestCargoObject `json:"cargo"`
	// 订单信息
	OrderInfo *PostCgiBinExpressLocalBusinessOrderPreAddRequestOrderInfoObject `json:"order_info"`
	// 商品信息,会展示到物流通知消息中
	Shop *PostCgiBinExpressLocalBusinessOrderPreAddRequestShopObject `json:"shop"`
	// 用配送公司提供的appSecret加密的校验串说明
	DeliverySign string `json:"delivery_sign"`
	// 商家门店编号,在配送公司登记,美团、闪送必填
	ShopNo string `json:"shop_no"`
	// 子商户id,区分小程序内部多个子商户
	SubBizID string `json:"sub_biz_id"`
}

// PostCgiBinExpressLocalBusinessOrderPreAddRequestSenderObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderPreAddRequestSenderObject struct {
	// 姓名,最长不超过256个字符
	Name string `json:"name"`
	// 城市名称,如广州市
	City string `json:"city"`
	// 地址(街道、小区、大厦等,用于定位)
	Address string `json:"address"`
	// 地址详情(楼号、单元号、层号)
	AddressDetail string `json:"address_detail"`
	// 电话/手机号,最长不超过64个字符
	Phone string `json:"phone"`
	// 经度(火星坐标或百度坐标,和 coordinate_type 字段配合使用,确到小数点后6位
	Lng float64 `json:"lng"`
	// 纬度(火星坐标或百度坐标,和 coordinate_type 字段配合使用,精确到小数点后6位)
	Lat float64 `json:"lat"`
	// 坐标类型,0:火星坐标(高德,腾讯地图均采用火星坐标) 1:百度坐标
	CoordinateType float64 `json:"coordinate_type,omitzero"`
}

// PostCgiBinExpressLocalBusinessOrderPreAddRequestReceiverObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderPreAddRequestReceiverObject struct {
	// 姓名,最长不超过256个字符
	Name string `json:"name"`
	// 城市名称,如广州市
	City string `json:"city"`
	// 地址(街道、小区、大厦等,用于定位)
	Address string `json:"address"`
	// 地址详情(楼号、单元号、层号)
	AddressDetail string `json:"address_detail"`
	// 电话/手机号,最长不超过64个字符
	Phone string `json:"phone"`
	// 经度(火星坐标或百度坐标,和 coordinate_type 字段配合使用,确到小数点后6位
	Lng float64 `json:"lng"`
	// 纬度(火星坐标或百度坐标,和 coordinate_type 字段配合使用,精确到小数点后6位)
	Lat float64 `json:"lat"`
	// 坐标类型,0:火星坐标(高德,腾讯地图均采用火星坐标) 1:百度坐标
	CoordinateType float64 `json:"coordinate_type,omitzero"`
}

// PostCgiBinExpressLocalBusinessOrderPreAddRequestCargoObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderPreAddRequestCargoObject struct {
	// 货物价格,单位为元,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-5000]
	GoodsValue float64 `json:"goods_value"`
	// 货物高度,单位为cm,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-45]
	GoodsHeight float64 `json:"goods_height,omitzero"`
	// 货物宽度,单位为cm,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-50]
	GoodsWidth float64 `json:"goods_width,omitzero"`
	// 货物长度,单位为cm,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-65]
	GoodsLength float64 `json:"goods_length,omitzero"`
	// 货物重量,单位为kg,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-50]
	GoodsWeight float64 `json:"goods_weight"`
	// 货物详情,最长不超过10240个字符
	GoodsDetail *PostCgiBinExpressLocalBusinessOrderPreAddRequestGoodsDetailObject `json:"goods_detail,omitempty"`
	// 货物取货信息,用于骑手到店取货,最长不超过100个字符
	GoodsPickupInfo string `json:"goods_pickup_info,omitempty"`
	// 品类一级类目,
	CargoFirstClass string `json:"cargo_first_class"`
	// 品类二级类目
	CargoSecondClass string `json:"cargo_second_class"`
}

// PostCgiBinExpressLocalBusinessOrderPreAddRequestGoodsDetailObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderPreAddRequestGoodsDetailObject struct {
	// 货物列表
	Goods []*PostCgiBinExpressLocalBusinessOrderPreAddRequestGoodsObject `json:"goods"`
}

// PostCgiBinExpressLocalBusinessOrderPreAddRequestGoodsObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderPreAddRequestGoodsObject struct {
	// 货物数量
	GoodCount int64 `json:"good_count"`
	// 货品名称
	GoodName string `json:"good_name"`
	// 货品单价,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数)
	GoodPrice float64 `json:"good_price,omitzero"`
	// 货品单位,最长不超过20个字符
	GoodUnit string `json:"good_unit,omitempty"`
}

// PostCgiBinExpressLocalBusinessOrderPreAddRequestOrderInfoObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderPreAddRequestOrderInfoObject struct {
	// 配送服务代码 不同配送公司自定义, 顺丰和达达不填
	DeliveryServiceCode string `json:"delivery_service_code,omitempty"`
	// 期望派单时间(达达支持,表示达达系统调度时间, 到那个时间才会有状态更新的回调通知),unix-timestamp, 比如1586342180
	ExpectedDeliveryTime int64 `json:"expected_delivery_time,omitzero"`
	// 订单类型, 0: 即时单 1 预约单,如预约单,需要设置expected_delivery_time或expected_finish_time或expected_pick_time
	OrderType int64 `json:"order_type,omitzero"`
	// 门店订单流水号,建议提供,方便骑手门店取货,最长不超过32个字符
	PoiSeq string `json:"poi_seq,omitempty"`
	// 备注,最长不超过200个字符
	Note string `json:"note,omitempty"`
	// 用户下单付款时间, 顺丰必填, 比如1555220757
	OrderTime int64 `json:"order_time,omitzero"`
	// 是否保价,0,非保价,1.保价
	IsInsured int64 `json:"is_insured,omitzero"`
	// 保价金额,单位为元,精确到分
	DeclaredValue int64 `json:"declared_value,omitzero"`
	// 小费,单位为元, 下单一般不加小费
	Tips int64 `json:"tips,omitzero"`
	// 是否选择直拿直送(0:不需要;1:需要。选择直拿直送后,同一时间骑手只能配送此订单至完成,配送费用也相应高一些,闪送必须选1,达达可选0或1,其余配送公司不支持直拿直送)
	IsDirectDelivery int64 `json:"is_direct_delivery,omitzero"`
	// 骑手应付金额,单位为元,精确到分
	CashOnDelivery int64 `json:"cash_on_delivery,omitzero"`
	// 骑手应收金额,单位为元,精确到分
	CashOnPickup int64 `json:"cash_on_pickup,omitzero"`
	// 物流流向,1:从门店取件送至用户;2:从用户取件送至门店
	RiderPickMethod int64 `json:"rider_pick_method,omitzero"`
	// 收货码(0:不需要;1:需要。收货码的作用是:骑手必须输入收货码才能完成订单妥投)
	IsFinishCodeNeeded int64 `json:"is_finish_code_needed,omitzero"`
	// 取货码(0:不需要;1:需要。取货码的作用是:骑手必须输入取货码才能从商家取货)
	IsPickupCodeNeeded int64 `json:"is_pickup_code_needed,omitzero"`
	// 期望送达时间(美团、顺丰同城急送支持),unix-timestamp, 比如1586342180
	ExpectedFinishTime int64 `json:"expected_finish_time,omitzero"`
	// 期望取件时间(闪送、顺丰同城急送支持,闪送需要设置两个小时后的时间,顺丰同城急送只需传expected_finish_time或expected_pick_time其中之一即可,同时都传则以expected_finish_time为准),unix-timestamp, 比如1586342180
	ExpectedPickTime int64 `json:"expected_pick_time,omitzero"`
}

// PostCgiBinExpressLocalBusinessOrderPreAddRequestShopObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderPreAddRequestShopObject struct {
	// 商家小程序的路径,建议为订单页面
	WxaPath string `json:"wxa_path,omitempty"`
	// 商品缩略图 url;shop.detail_list为空则必传,shop.detail_list非空可不传。
	ImgURL string `json:"img_url,omitempty"`
	// 商品名称, 不超过128字节;shop.detail_list为空则必传,shop.detail_list非空可不传。
	GoodsName string `json:"goods_name,omitempty"`
	// 商品数量;shop.detail_list为空则必传。shop.detail_list非空可不传,默认取shop.detail_list的size
	GoodsCount int64 `json:"goods_count,omitzero"`
	// 该参数在【即时配送】的 addLocalOrder 接口才生效。若结算方式为:第三方向配送公司统一结算,商户后续和第三方结算,则该参数必填;在该结算模式下,第三方用自己的开发小程序替授权商户发起下单,并将授权小程序的appid给平台,后续配送通知中可回流授权商户小程序。
	WxaAppID string `json:"wxa_appid,omitempty"`
}

// PostCgiBinExpressLocalBusinessOrderPreAddResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessOrderPreAddResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
	// 实际运费(单位:元),运费减去优惠券费用
	Fee int64 `json:"fee,omitzero"`
	// 运费(单位:元)
	Deliverfee int64 `json:"deliverfee,omitzero"`
	// 优惠券费用(单位:元)
	CouponFee int64 `json:"couponFee,omitzero"`
	// 小费(单位:元)
	Tips int64 `json:"tips,omitzero"`
	// 保价费(单位:元)
	Insurancefee int64 `json:"insurancefee,omitzero"`
	// 配送距离(单位:米)预计骑手接单时间,单位秒,比如5分钟,就填300, 无法预计填0
	Distance int64 `json:"distance,omitzero"`
	// 配送公司可以返回此字段,当用户下单时候带上这个字段,保证在一段时间内运费不变
	DeliveryToken string `json:"delivery_token,omitempty"`
	// 预计骑手接单时间,单位秒,比如5分钟,就填300, 无法预计填0
	DispatchDuration int64 `json:"dispatch_duration,omitzero"`
}

func (c *Client) PostCgiBinExpressLocalBusinessOrderPreAdd(ctx context.Context, req *PostCgiBinExpressLocalBusinessOrderPreAddRequest) (*PostCgiBinExpressLocalBusinessOrderPreAddResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessOrderPreAddResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/order/pre_add", req, postCgiBinExpressLocalBusinessOrderPreAddErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessOrderPrecancelErrCodes = map[int]core.ErrDoc{-1: {
	Desc:     "system error",
	Solution: "系统繁忙,此时请开发者稍候再试",
}}

// PostCgiBinExpressLocalBusinessOrderPrecancel 预取消配送单 (POST /cgi-bin/express/local/business/order/precancel)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_precancelorder.html
// PostCgiBinExpressLocalBusinessOrderPrecancelRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessOrderPrecancelRequest struct {
	// 商家id, 由配送公司分配的appkey
	Shopid string `json:"shopid"`
	// 唯一标识订单的 ID,由商户生成
	ShopOrderID string `json:"shop_order_id"`
	// 快递公司ID
	DeliveryID string `json:"delivery_id"`
	// 配送单id
	WaybillID string `json:"waybill_id"`
	// 取消原因Id
	CancelReasonID int64 `json:"cancel_reason_id,omitzero"`
	// 取消原因
	CancelReason string `json:"cancel_reason,omitempty"`
	// 商家门店编号,在配送公司登记,闪送shop_no必填,值为店铺id
	ShopNo string `json:"shop_no"`
	// 用配送公司提供的appSecret加密的校验串说明
	DeliverySign string `json:"delivery_sign"`
}

// PostCgiBinExpressLocalBusinessOrderPrecancelResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessOrderPrecancelResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
	// 预计扣除的违约金(单位:元),精确到分
	DeductFee int64 `json:"deduct_fee,omitzero"`
	// 说明
	Desc string `json:"desc,omitempty"`
}

func (c *Client) PostCgiBinExpressLocalBusinessOrderPrecancel(ctx context.Context, req *PostCgiBinExpressLocalBusinessOrderPrecancelRequest) (*PostCgiBinExpressLocalBusinessOrderPrecancelResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessOrderPrecancelResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/order/precancel", req, postCgiBinExpressLocalBusinessOrderPrecancelErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessOrderReaddErrCodes = map[int]core.ErrDoc{-1: {
	Desc:     "system error",
	Solution: "系统繁忙,此时请开发者稍候再试",
}}

// PostCgiBinExpressLocalBusinessOrderReadd 重新下单 (POST /cgi-bin/express/local/business/order/readd)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_reorder.html
// PostCgiBinExpressLocalBusinessOrderReaddRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessOrderReaddRequest struct {
	// 商家id,由配送公司分配的appkey
	Shopid string `json:"shopid"`
	// 唯一标识订单的 ID,由商户生成, 不超过128字节
	ShopOrderID string `json:"shop_order_id"`
	// 配送公司ID
	DeliveryID string `json:"delivery_id"`
	// 下单用户的openid
	OpenID string `json:"openid"`
	// 发件人信息,顺丰同城急送必须填写,美团配送、达达、闪送,若传了shop_no的值可不填该字段
	Sender *PostCgiBinExpressLocalBusinessOrderReaddRequestSenderObject `json:"sender"`
	// 收件人信息
	Receiver *PostCgiBinExpressLocalBusinessOrderReaddRequestReceiverObject `json:"receiver"`
	// 货物信息
	Cargo *PostCgiBinExpressLocalBusinessOrderReaddRequestCargoObject `json:"cargo"`
	// 订单信息
	OrderInfo *PostCgiBinExpressLocalBusinessOrderReaddRequestOrderInfoObject `json:"order_info"`
	// 商品信息,会展示到物流通知消息中
	Shop *PostCgiBinExpressLocalBusinessOrderReaddRequestShopObject `json:"shop"`
	// 预下单接口返回的参数,配送公司可保证在一段时间内运费不变
	DeliveryToken string `json:"delivery_token"`
	// 用配送公司提供的appSecret加密的校验串说明
	DeliverySign string `json:"delivery_sign"`
	// 商家门店编号,在配送公司登记,如果只有一个门店,美团闪送必填, 值为店铺id
	ShopNo string `json:"shop_no"`
	// 子商户id,区分小程序内部多个子商户
	SubBizID string `json:"sub_biz_id,omitempty"`
}

// PostCgiBinExpressLocalBusinessOrderReaddRequestSenderObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderReaddRequestSenderObject struct {
	// 姓名,最长不超过256个字符
	Name string `json:"name"`
	// 城市名称,如广州市
	City string `json:"city"`
	// 地址(街道、小区、大厦等,用于定位)
	Address string `json:"address"`
	// 地址详情(楼号、单元号、层号)
	AddressDetail string `json:"address_detail"`
	// 电话/手机号,最长不超过64个字符
	Phone string `json:"phone"`
	// 经度(火星坐标或百度坐标,和 coordinate_type 字段配合使用,确到小数点后6位
	Lng float64 `json:"lng"`
	// 纬度(火星坐标或百度坐标,和 coordinate_type 字段配合使用,精确到小数点后6位)
	Lat float64 `json:"lat"`
	// 坐标类型,0:火星坐标(高德,腾讯地图均采用火星坐标) 1:百度坐标
	CoordinateType float64 `json:"coordinate_type,omitzero"`
}

// PostCgiBinExpressLocalBusinessOrderReaddRequestReceiverObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderReaddRequestReceiverObject struct {
	// 姓名,最长不超过256个字符
	Name string `json:"name"`
	// 城市名称,如广州市
	City string `json:"city"`
	// 地址(街道、小区、大厦等,用于定位)
	Address string `json:"address"`
	// 地址详情(楼号、单元号、层号)
	AddressDetail string `json:"address_detail"`
	// 电话/手机号,最长不超过64个字符
	Phone string `json:"phone"`
	// 经度(火星坐标或百度坐标,和 coordinate_type 字段配合使用,确到小数点后6位
	Lng float64 `json:"lng"`
	// 纬度(火星坐标或百度坐标,和 coordinate_type 字段配合使用,精确到小数点后6位)
	Lat float64 `json:"lat"`
	// 坐标类型,0:火星坐标(高德,腾讯地图均采用火星坐标) 1:百度坐标
	CoordinateType float64 `json:"coordinate_type,omitzero"`
}

// PostCgiBinExpressLocalBusinessOrderReaddRequestCargoObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderReaddRequestCargoObject struct {
	// 货物价格,单位为元,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-5000]
	GoodsValue float64 `json:"goods_value"`
	// 货物高度,单位为cm,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-45]
	GoodsHeight float64 `json:"goods_height,omitzero"`
	// 货物宽度,单位为cm,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-50]
	GoodsWidth float64 `json:"goods_width,omitzero"`
	// 货物长度,单位为cm,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-65]
	GoodsLength float64 `json:"goods_length,omitzero"`
	// 货物重量,单位为kg,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数),范围为(0-50]
	GoodsWeight float64 `json:"goods_weight"`
	// 货物详情,最长不超过10240个字符
	GoodsDetail *PostCgiBinExpressLocalBusinessOrderReaddRequestGoodsDetailObject `json:"goods_detail,omitempty"`
	// 货物取货信息,用于骑手到店取货,最长不超过100个字符
	GoodsPickupInfo string `json:"goods_pickup_info,omitempty"`
	// 品类一级类目
	CargoFirstClass string `json:"cargo_first_class"`
	// 品类二级类目
	CargoSecondClass string `json:"cargo_second_class"`
}

// PostCgiBinExpressLocalBusinessOrderReaddRequestGoodsDetailObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderReaddRequestGoodsDetailObject struct {
	// 货物列表
	Goods []*PostCgiBinExpressLocalBusinessOrderReaddRequestGoodsObject `json:"goods"`
}

// PostCgiBinExpressLocalBusinessOrderReaddRequestGoodsObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderReaddRequestGoodsObject struct {
	// 货物数量
	GoodCount int64 `json:"good_count"`
	// 货品名称
	GoodName string `json:"good_name"`
	// 货品单价,精确到小数点后两位(如果小数点后位数多于两位,则四舍五入保留两位小数)
	GoodPrice float64 `json:"good_price,omitzero"`
	// 货品单位,最长不超过20个字符
	GoodUnit string `json:"good_unit,omitempty"`
}

// PostCgiBinExpressLocalBusinessOrderReaddRequestOrderInfoObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderReaddRequestOrderInfoObject struct {
	// 配送服务代码 不同配送公司自定义, 顺丰和达达不填
	DeliveryServiceCode string `json:"delivery_service_code,omitempty"`
	// 期望派单时间(达达支持,表示达达系统调度时间, 到那个时间才会有状态更新的回调通知),unix-timestamp, 比如1586342180
	ExpectedDeliveryTime int64 `json:"expected_delivery_time,omitzero"`
	// 订单类型, 0: 即时单 1 预约单,如预约单,需要设置expected_delivery_time或expected_finish_time或expected_pick_time
	OrderType int64 `json:"order_type,omitzero"`
	// 门店订单流水号,建议提供,方便骑手门店取货,最长不超过32个字符
	PoiSeq string `json:"poi_seq,omitempty"`
	// 备注,最长不超过200个字符
	Note string `json:"note,omitempty"`
	// 用户下单付款时间, 顺丰必填, 比如1555220757
	OrderTime int64 `json:"order_time,omitzero"`
	// 是否保价,0,非保价,1.保价
	IsInsured int64 `json:"is_insured,omitzero"`
	// 保价金额,单位为元,精确到分
	DeclaredValue int64 `json:"declared_value,omitzero"`
	// 小费,单位为元, 下单一般不加小费
	Tips int64 `json:"tips,omitzero"`
	// 是否选择直拿直送(0:不需要;1:需要。选择直拿直送后,同一时间骑手只能配送此订单至完成,配送费用也相应高一些,闪送必须选1,达达可选0或1,其余配送公司不支持直拿直送)
	IsDirectDelivery int64 `json:"is_direct_delivery,omitzero"`
	// 骑手应付金额,单位为元,精确到分
	CashOnDelivery int64 `json:"cash_on_delivery,omitzero"`
	// 骑手应收金额,单位为元,精确到分
	CashOnPickup int64 `json:"cash_on_pickup,omitzero"`
	// 物流流向,1:从门店取件送至用户;2:从用户取件送至门店
	RiderPickMethod int64 `json:"rider_pick_method,omitzero"`
	// 收货码(0:不需要;1:需要。收货码的作用是:骑手必须输入收货码才能完成订单妥投)
	IsFinishCodeNeeded int64 `json:"is_finish_code_needed,omitzero"`
	// 取货码(0:不需要;1:需要。取货码的作用是:骑手必须输入取货码才能从商家取货)
	IsPickupCodeNeeded int64 `json:"is_pickup_code_needed,omitzero"`
	// 期望送达时间(美团、顺丰同城急送支持),unix-timestamp, 比如1586342180
	ExpectedFinishTime int64 `json:"expected_finish_time,omitzero"`
	// 期望取件时间(闪送、顺丰同城急送支持,闪送需要设置两个小时后的时间,顺丰同城急送只需传expected_finish_time或expected_pick_time其中之一即可,同时都传则以expected_finish_time为准),unix-timestamp, 比如1586342180
	ExpectedPickTime int64 `json:"expected_pick_time,omitzero"`
}

// PostCgiBinExpressLocalBusinessOrderReaddRequestShopObject is a documented nested object.
type PostCgiBinExpressLocalBusinessOrderReaddRequestShopObject struct {
	// 商家小程序的路径,建议为订单页面
	WxaPath string `json:"wxa_path,omitempty"`
	// 商品缩略图 url;shop.detail_list为空则必传,shop.detail_list非空可不传。
	ImgURL string `json:"img_url,omitempty"`
	// 商品名称, 不超过128字节;shop.detail_list为空则必传,shop.detail_list非空可不传。
	GoodsName string `json:"goods_name,omitempty"`
	// 商品数量;shop.detail_list为空则必传。shop.detail_list非空可不传,默认取shop.detail_list的size
	GoodsCount int64 `json:"goods_count,omitzero"`
	// 该参数在【即时配送】的 addLocalOrder 接口才生效。若结算方式为:第三方向配送公司统一结算,商户后续和第三方结算,则该参数必填;在该结算模式下,第三方用自己的开发小程序替授权商户发起下单,并将授权小程序的appid给平台,后续配送通知中可回流授权商户小程序。
	WxaAppID string `json:"wxa_appid,omitempty"`
}

// PostCgiBinExpressLocalBusinessOrderReaddResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessOrderReaddResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
	// 实际运费(单位:元),运费减去优惠券费用
	Fee int64 `json:"fee,omitzero"`
	// 运费(单位:元)
	Deliverfee int64 `json:"deliverfee,omitzero"`
	// 优惠券费用(单位:元)
	Couponfee int64 `json:"couponfee,omitzero"`
	// 小费(单位:元)
	Tips int64 `json:"tips,omitzero"`
	// 保价费(单位:元)
	Insurancfee int64 `json:"insurancfee,omitzero"`
	// 配送距离(整数单位:米)
	Distance int64 `json:"distance,omitzero"`
	// 配送单号
	WaybillID string `json:"waybill_id,omitempty"`
	// 配送状态
	OrderStatus int64 `json:"order_status,omitzero"`
	// 收货码
	FinishCode int64 `json:"finish_code,omitzero"`
	// 取货码
	PickupCode int64 `json:"pickup_code,omitzero"`
	// 预计骑手接单时间,单位秒,比如5分钟,就填300, 无法预计填0
	DispatchDuration int64 `json:"dispatch_duration,omitzero"`
}

func (c *Client) PostCgiBinExpressLocalBusinessOrderReadd(ctx context.Context, req *PostCgiBinExpressLocalBusinessOrderReaddRequest) (*PostCgiBinExpressLocalBusinessOrderReaddResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessOrderReaddResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/order/readd", req, postCgiBinExpressLocalBusinessOrderReaddErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessRealmockUpdateOrderErrCodes = map[int]core.ErrDoc{-1: {
	Desc:     "system error",
	Solution: "系统繁忙,此时请开发者稍候再试",
}}

// PostCgiBinExpressLocalBusinessRealmockUpdateOrder 模拟更新配送单状态 (POST /cgi-bin/express/local/business/realmock_update_order)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_realmockupdateorder.html
// PostCgiBinExpressLocalBusinessRealmockUpdateOrderRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessRealmockUpdateOrderRequest struct {
	// 商家id
	Shopid string `json:"shopid"`
	// 唯一标识订单的 ID,由商户生成
	ShopOrderID string `json:"shop_order_id"`
	// 配送状态,详见下文
	OrderStatus int64 `json:"order_status"`
	// 状态变更时间点,Unix秒级时间戳
	ActionTime int64 `json:"action_time"`
	// 附加信息
	ActionMsg string `json:"action_msg,omitempty"`
	// 用配送公司提供的appSecret加密的校验串说明
	DeliverySign string `json:"delivery_sign"`
}

// PostCgiBinExpressLocalBusinessRealmockUpdateOrderResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessRealmockUpdateOrderResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
}

func (c *Client) PostCgiBinExpressLocalBusinessRealmockUpdateOrder(ctx context.Context, req *PostCgiBinExpressLocalBusinessRealmockUpdateOrderRequest) (*PostCgiBinExpressLocalBusinessRealmockUpdateOrderResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessRealmockUpdateOrderResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/realmock_update_order", req, postCgiBinExpressLocalBusinessRealmockUpdateOrderErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessShopAddErrCodes = map[int]core.ErrDoc{-1: {
	Desc:     "system error",
	Solution: "系统繁忙,此时请开发者稍候再试",
}}

// PostCgiBinExpressLocalBusinessShopAdd 发起绑定请求 (POST /cgi-bin/express/local/business/shop/add)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_bindlocalaccount.html
// PostCgiBinExpressLocalBusinessShopAddRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessShopAddRequest struct {
	// 配送公司ID
	DeliveryID string `json:"delivery_id"`
}

// PostCgiBinExpressLocalBusinessShopAddResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessShopAddResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
}

func (c *Client) PostCgiBinExpressLocalBusinessShopAdd(ctx context.Context, req *PostCgiBinExpressLocalBusinessShopAddRequest) (*PostCgiBinExpressLocalBusinessShopAddResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessShopAddResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/shop/add", req, postCgiBinExpressLocalBusinessShopAddErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessShopGetErrCodes = map[int]core.ErrDoc{40001: {
	Desc:     "invalid credential access_token isinvalid or not latest",
	Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
}}

// PostCgiBinExpressLocalBusinessShopGet 拉取已绑定账号 (POST /cgi-bin/express/local/business/shop/get)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_getbindaccount.html
// PostCgiBinExpressLocalBusinessShopGetRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessShopGetRequest struct{}

// PostCgiBinExpressLocalBusinessShopGetResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessShopGetResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
	// 绑定的商家签约账号列表
	ShopList []*PostCgiBinExpressLocalBusinessShopGetResponseShopListObject `json:"shop_list,omitempty"`
}

// PostCgiBinExpressLocalBusinessShopGetResponseShopListObject is a documented nested object.
type PostCgiBinExpressLocalBusinessShopGetResponseShopListObject struct {
	// 商家id
	Shopid string `json:"shopid,omitempty"`
	// 配送公司Id
	DeliveryID string `json:"delivery_id,omitempty"`
	// 审核状态.0表示审核通过;1表示审核中;2表示审核不通过。
	AuditResult int64 `json:"audit_result,omitzero"`
}

func (c *Client) PostCgiBinExpressLocalBusinessShopGet(ctx context.Context, req *PostCgiBinExpressLocalBusinessShopGetRequest) (*PostCgiBinExpressLocalBusinessShopGetResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessShopGetResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/shop/get", req, postCgiBinExpressLocalBusinessShopGetErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalBusinessTestUpdateOrderErrCodes = map[int]core.ErrDoc{40001: {
	Desc:     "invalid credential access_token isinvalid or not latest",
	Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
}}

// PostCgiBinExpressLocalBusinessTestUpdateOrder 模拟配送公司更新配送单状态 (POST /cgi-bin/express/local/business/test_update_order)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-business/api_mockupdateorder.html
// PostCgiBinExpressLocalBusinessTestUpdateOrderRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalBusinessTestUpdateOrderRequest struct {
	// 商家id, 必须是 "test_shop_id"
	Shopid string `json:"shopid"`
	// 唯一标识订单的 ID,由商户生成
	ShopOrderID string `json:"shop_order_id"`
	// 配送状态
	OrderStatus int64 `json:"order_status"`
	// 状态变更时间点,Unix秒级时间戳
	ActionTime int64 `json:"action_time"`
	// 附加信息
	ActionMsg string `json:"action_msg,omitempty"`
}

// PostCgiBinExpressLocalBusinessTestUpdateOrderResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalBusinessTestUpdateOrderResponse struct {
	// 运力返回的错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 运力返回的错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
}

func (c *Client) PostCgiBinExpressLocalBusinessTestUpdateOrder(ctx context.Context, req *PostCgiBinExpressLocalBusinessTestUpdateOrderRequest) (*PostCgiBinExpressLocalBusinessTestUpdateOrderResponse, error) {
	return core.Call[PostCgiBinExpressLocalBusinessTestUpdateOrderResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/business/test_update_order", req, postCgiBinExpressLocalBusinessTestUpdateOrderErrCodes, true, core.SignNone)
}

var postCgiBinExpressLocalDeliveryUpdateOrderErrCodes = map[int]core.ErrDoc{-1: {
	Desc:     "system error",
	Solution: "系统繁忙,此时请开发者稍候再试",
}}

// PostCgiBinExpressLocalDeliveryUpdateOrder 更新配送单状态 (POST /cgi-bin/express/local/delivery/update_order)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/immediate-delivery/deliver-by-provider/api_updateorder.html
// PostCgiBinExpressLocalDeliveryUpdateOrderRequest carries the documented parameters of one API call.
type PostCgiBinExpressLocalDeliveryUpdateOrderRequest struct {
	// 下单事件 中推送的token字段
	WxToken string `json:"wx_token"`
	// 订单状态
	OrderStatus int64 `json:"order_status"`
	// 配送单id
	WaybillID string `json:"waybill_id"`
	// 附加信息
	ActionMsg string `json:"action_msg,omitempty"`
	// 状态变更时间点,Unix秒级时间戳
	ActionTime int64 `json:"action_time"`
	// 骑手信息, 骑手接单时需返回
	Agent *PostCgiBinExpressLocalDeliveryUpdateOrderRequestAgentObject `json:"agent,omitempty"`
	// 商家id, 由配送公司分配,可以是dev_id或者appkey
	Shopid string `json:"shopid"`
	// 唯一标识订单的 ID,由商户生成
	ShopOrderID string `json:"shop_order_id"`
	// 商家门店编号, 在配送公司侧登记
	ShopNo string `json:"shop_no,omitempty"`
	// 配送公司小程序跳转路径,用于用户收到消息会间接跳转到这个页面
	WxaPath string `json:"wxa_path"`
	// 预计送达时间戳, 骑手接单时需返回
	ExpectedDeliveryTime int64 `json:"expected_delivery_time,omitzero"`
}

// PostCgiBinExpressLocalDeliveryUpdateOrderRequestAgentObject is a documented nested object.
type PostCgiBinExpressLocalDeliveryUpdateOrderRequestAgentObject struct {
	// 骑手姓名
	Name string `json:"name"`
	// 骑手电话
	Phone string `json:"phone"`
	// 电话是否加密。默认是0不加密,1表示加密。
	IsPhoneEncrypted int64 `json:"is_phone_encrypted,omitzero"`
}

// PostCgiBinExpressLocalDeliveryUpdateOrderResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinExpressLocalDeliveryUpdateOrderResponse struct {
	// 错误码
	Resultcode int64 `json:"resultcode,omitzero"`
	// 错误描述
	Resultmsg string `json:"resultmsg,omitempty"`
}

func (c *Client) PostCgiBinExpressLocalDeliveryUpdateOrder(ctx context.Context, req *PostCgiBinExpressLocalDeliveryUpdateOrderRequest) (*PostCgiBinExpressLocalDeliveryUpdateOrderResponse, error) {
	return core.Call[PostCgiBinExpressLocalDeliveryUpdateOrderResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/express/local/delivery/update_order", req, postCgiBinExpressLocalDeliveryUpdateOrderErrCodes, true, core.SignNone)
}
