// Code generated by docsync from the official WeChat documentation. DO NOT EDIT.
// The API surface (names, request/response shapes) is derived deterministically
// from the endpoints; regenerate with "make docs-sync". If this file changes
// under you, the upstream documentation changed.

package miniprogram

import (
	"context"
	"github.com/go-sphere/weixin-api/core"
)

var postCgiBinBusinessGetErrCodes = map[int]core.ErrDoc{45071: {
	Desc:     "business_id对应的商户不存在",
	Solution: "",
}}

// PostCgiBinBusinessGet 客服子商户拉取单个商户信息 (POST /cgi-bin/business/get)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-management/api_getbusiness.html
// PostCgiBinBusinessGetRequest carries the documented parameters of one API call.
type PostCgiBinBusinessGetRequest struct {
	// 创建商户时得到的商户id,与account_name选填一个
	BusinessID string `json:"business_id,omitempty"`
	// 创建商户时用到的account_name,与business_id选填一个
	AccountName string `json:"account_name,omitempty"`
}

// PostCgiBinBusinessGetResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinBusinessGetResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误描述
	Errmsg string `json:"errmsg,omitempty"`
	// 商户信息
	BusinessInfo *PostCgiBinBusinessGetResponseBusinessInfoObject `json:"business_info,omitempty"`
}

// PostCgiBinBusinessGetResponseBusinessInfoObject is a documented nested object.
type PostCgiBinBusinessGetResponseBusinessInfoObject struct {
	// 商户ID
	BusinessID string `json:"business_id,omitempty"`
	// 商户账号名称
	AccountName string `json:"account_name,omitempty"`
	// 商户昵称,会在客户端会话里展示
	Nickname string `json:"nickname,omitempty"`
	// 商户头像
	IconMediaID string `json:"icon_media_id,omitempty"`
}

func (c *Client) PostCgiBinBusinessGet(ctx context.Context, req *PostCgiBinBusinessGetRequest) (*PostCgiBinBusinessGetResponse, error) {
	return core.Call[PostCgiBinBusinessGetResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/business/get", req, postCgiBinBusinessGetErrCodes, true, core.SignNone)
}

// PostCgiBinBusinessList 客服子商户拉取多个商户信息 (POST /cgi-bin/business/list)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-management/api_listbusiness.html
// PostCgiBinBusinessListRequest carries the documented parameters of one API call.
type PostCgiBinBusinessListRequest struct {
	// 用于分页拉取,从0开始
	Offset int64 `json:"offset"`
	// 一次拉取的商户个数,最多为200
	Count int64 `json:"count"`
}

// PostCgiBinBusinessListResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinBusinessListResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误描述
	Errmsg string `json:"errmsg,omitempty"`
	// 商户信息列表
	List []*PostCgiBinBusinessListResponseListObject `json:"list,omitempty"`
}

// PostCgiBinBusinessListResponseListObject is a documented nested object.
type PostCgiBinBusinessListResponseListObject struct {
	// 商户ID
	BusinessID string `json:"business_id,omitempty"`
	// 商户账号名称
	AccountName string `json:"account_name,omitempty"`
	// 商户昵称,会在客户端会话里展示
	Nickname string `json:"nickname,omitempty"`
	// 商户头像
	IconMediaID string `json:"icon_media_id,omitempty"`
}

func (c *Client) PostCgiBinBusinessList(ctx context.Context, req *PostCgiBinBusinessListRequest) (*PostCgiBinBusinessListResponse, error) {
	return core.Call[PostCgiBinBusinessListResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/business/list", req, nil, true, core.SignNone)
}

var postCgiBinBusinessRegisterErrCodes = map[int]core.ErrDoc{
	40004: {
		Desc:     "icon_media_id类型不对,应该为图片类型",
		Solution: "",
	},
	40007: {
		Desc:     "icon_media_id不是合法的media_id",
		Solution: "",
	},
	45070: {
		Desc:     "account_name对应账号已经被创建(一个account_name对应一个business_id)",
		Solution: "",
	},
	45077: {
		Desc:     "子商户数量已达到上限",
		Solution: "",
	},
	45078: {
		Desc:     "昵称不合法,请检查是否满足nickname规则",
		Solution: "",
	},
	45079: {
		Desc:     "昵称含有违规词汇",
		Solution: "",
	},
	45091: {
		Desc:     "account_name不合法,请检查是否满足account_name规则",
		Solution: "",
	},
}

// PostCgiBinBusinessRegister 客服子商户创建商户 (POST /cgi-bin/business/register)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-management/api_registerbusiness.html
// PostCgiBinBusinessRegisterRequest carries the documented parameters of one API call.
type PostCgiBinBusinessRegisterRequest struct {
	// 创建商户时用到,一个account_name只能创建一次,account_name为6-30字符,必须为英文、数字、或者下划线,区分大小写。
	AccountName string `json:"account_name"`
	// 商户昵称,会在客户端会话里展示,4-30字符(中文视为2字符),由中文、英文、数字组成
	Nickname string `json:"nickname"`
	// 头像,图片类型,需要用临时素材接口得到,使用 新增临时素材 ,为空则不更新头像
	IconMediaID string `json:"icon_media_id"`
	// 是否将消息转发到通用客服,false为不转发,true为转发,如果transfer_to_commkf=true时,可以使用客服管理相关api,请求参数新增business_id
	TransferToCommkf bool `json:"transfer_to_commkf,omitzero"`
}

// PostCgiBinBusinessRegisterResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinBusinessRegisterResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误描述
	Errmsg string `json:"errmsg,omitempty"`
	// 商户ID
	BusinessID string `json:"business_id,omitempty"`
}

func (c *Client) PostCgiBinBusinessRegister(ctx context.Context, req *PostCgiBinBusinessRegisterRequest) (*PostCgiBinBusinessRegisterResponse, error) {
	return core.Call[PostCgiBinBusinessRegisterResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/business/register", req, postCgiBinBusinessRegisterErrCodes, true, core.SignNone)
}

var postCgiBinBusinessUpdateErrCodes = map[int]core.ErrDoc{
	40004: {
		Desc:     "icon_media_id类型不对,应该为图片类型",
		Solution: "",
	},
	40007: {
		Desc:     "icon_media_id不是合法的media_id",
		Solution: "",
	},
	45071: {
		Desc:     "business_id对应的商户不存在",
		Solution: "",
	},
	45077: {
		Desc:     "子商户数量已达到上限",
		Solution: "",
	},
	45078: {
		Desc:     "昵称不合法,请检查是否满足nickname规则",
		Solution: "",
	},
	45079: {
		Desc:     "昵称含有违规词汇",
		Solution: "",
	},
}

// PostCgiBinBusinessUpdate 客服子商户更新商户信息 (POST /cgi-bin/business/update)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-management/api_updatebusiness.html
// PostCgiBinBusinessUpdateRequest carries the documented parameters of one API call.
type PostCgiBinBusinessUpdateRequest struct {
	// 创建商户时得到的商户id
	BusinessID string `json:"business_id"`
	// 商户昵称,会在客户端会话里展示,4-30字符(中文视为2字符),由中文、英文、数字组成
	Nickname string `json:"nickname,omitempty"`
	// 头像,图片类型,需要用临时素材接口得到,使用 新增临时素材 ,为空则不更新头像
	IconMediaID string `json:"icon_media_id,omitempty"`
}

// PostCgiBinBusinessUpdateResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinBusinessUpdateResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误描述
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostCgiBinBusinessUpdate(ctx context.Context, req *PostCgiBinBusinessUpdateRequest) (*PostCgiBinBusinessUpdateResponse, error) {
	return core.Call[PostCgiBinBusinessUpdateResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/business/update", req, postCgiBinBusinessUpdateErrCodes, true, core.SignNone)
}

var getCgiBinCustomserviceGetkflistErrCodes = map[int]core.ErrDoc{
	0: {
		Desc:     "成功",
		Solution: "",
	},
	40003: {
		Desc:     "非法的openid",
		Solution: "",
	},
	40005: {
		Desc:     "不支持的媒体类型",
		Solution: "",
	},
	40009: {
		Desc:     "媒体文件长度不合法",
		Solution: "",
	},
	65400: {
		Desc:     "API不可用,即没有开通/升级到新版客服功能",
		Solution: "",
	},
	65401: {
		Desc:     "无效客服账号",
		Solution: "",
	},
	65402: {
		Desc:     "客服账号尚未绑定微信号,不能投入使用",
		Solution: "",
	},
	65403: {
		Desc:     "客服昵称不合法",
		Solution: "",
	},
	65404: {
		Desc:     "客服账号不合法",
		Solution: "",
	},
	65405: {
		Desc:     "账号数目已达到上限,不能继续添加",
		Solution: "",
	},
	65406: {
		Desc:     "已经存在的客服账号",
		Solution: "",
	},
	65407: {
		Desc:     "邀请对象已经是该小程序客服",
		Solution: "",
	},
	65408: {
		Desc:     "本小程序已经有一个邀请给该微信",
		Solution: "",
	},
	65409: {
		Desc:     "无效的微信号",
		Solution: "",
	},
	65410: {
		Desc:     "邀请对象绑定小程序客服数达到上限",
		Solution: "",
	},
	65411: {
		Desc:     "该账号已经有一个等待确认的邀请,不能重复邀请",
		Solution: "",
	},
	65412: {
		Desc:     "该账号已经绑定微信号,不能进行邀请",
		Solution: "",
	},
	65413: {
		Desc:     "不存在对应用户的会话信息",
		Solution: "",
	},
	65414: {
		Desc:     "客户正在被其他客服接待",
		Solution: "",
	},
}

// GetCgiBinCustomserviceGetkflist 获取所有客服账号 (GET /cgi-bin/customservice/getkflist)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-message/api_getkflist.html
// GetCgiBinCustomserviceGetkflistRequest carries the documented parameters of one API call.
type GetCgiBinCustomserviceGetkflistRequest struct {
	// 客服子商户的business_id,对于普通账号(小程序、公众号、服务号)客服不需要填business_id
	BusinessID string `query:"business_id,omitempty"`
}

// GetCgiBinCustomserviceGetkflistResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type GetCgiBinCustomserviceGetkflistResponse struct {
	// 客服列表
	KfList []*GetCgiBinCustomserviceGetkflistResponseKfListObject `json:"kf_list,omitempty"`
}

// GetCgiBinCustomserviceGetkflistResponseKfListObject is a documented nested object.
type GetCgiBinCustomserviceGetkflistResponseKfListObject struct {
	// 完整客服账号,格式为:账号前缀@公众号微信号
	KfAccount string `json:"kf_account,omitempty"`
	// 客服昵称
	KfNick string `json:"kf_nick,omitempty"`
	// 客服编号
	KfID string `json:"kf_id,omitempty"`
	// 客服头像
	KfHeadimgurl string `json:"kf_headimgurl,omitempty"`
	// 如果客服账号已绑定了客服人员微信号, 则此处显示微信号
	KfWx string `json:"kf_wx,omitempty"`
	// 如果客服账号尚未绑定微信号,但是已经发起了一个绑定邀请, 则此处显示绑定邀请的微信号
	InviteWx string `json:"invite_wx,omitempty"`
	// 如果客服账号尚未绑定微信号,但是已经发起过一个绑定邀请, 邀请的过期时间,为unix 时间戳
	InviteExpireTime string `json:"invite_expire_time,omitempty"`
	// 邀请的状态,有等待确认"waiting",被拒绝"rejected", 过期"expired"
	InviteStatus string `json:"invite_status,omitempty"`
	// 客服openid
	KfOpenID string `json:"kf_openid,omitempty"`
}

func (c *Client) GetCgiBinCustomserviceGetkflist(ctx context.Context, req *GetCgiBinCustomserviceGetkflistRequest) (*GetCgiBinCustomserviceGetkflistResponse, error) {
	return core.Call[GetCgiBinCustomserviceGetkflistResponse](c.EndpointClient, ctx, "GET", "/cgi-bin/customservice/getkflist", req, getCgiBinCustomserviceGetkflistErrCodes, true, core.SignNone)
}

var getCgiBinCustomserviceGetonlinekflistErrCodes = map[int]core.ErrDoc{
	0: {
		Desc:     "成功",
		Solution: "",
	},
	40003: {
		Desc:     "非法的openid",
		Solution: "",
	},
	40005: {
		Desc:     "不支持的媒体类型",
		Solution: "",
	},
	40009: {
		Desc:     "媒体文件长度不合法",
		Solution: "",
	},
	65400: {
		Desc:     "API不可用,即没有开通/升级到新版客服功能",
		Solution: "",
	},
	65401: {
		Desc:     "无效客服账号",
		Solution: "",
	},
	65402: {
		Desc:     "客服账号尚未绑定微信号,不能投入使用",
		Solution: "",
	},
	65403: {
		Desc:     "客服昵称不合法",
		Solution: "",
	},
	65404: {
		Desc:     "客服账号不合法",
		Solution: "",
	},
	65405: {
		Desc:     "账号数目已达到上限,不能继续添加",
		Solution: "",
	},
	65406: {
		Desc:     "已经存在的客服账号",
		Solution: "",
	},
	65407: {
		Desc:     "邀请对象已经是该小程序客服",
		Solution: "",
	},
	65408: {
		Desc:     "本小程序已经有一个邀请给该微信",
		Solution: "",
	},
	65409: {
		Desc:     "无效的微信号",
		Solution: "",
	},
	65410: {
		Desc:     "邀请对象绑定小程序客服数达到上限",
		Solution: "",
	},
	65411: {
		Desc:     "该账号已经有一个等待确认的邀请,不能重复邀请",
		Solution: "",
	},
	65412: {
		Desc:     "该账号已经绑定微信号,不能进行邀请",
		Solution: "",
	},
	65413: {
		Desc:     "不存在对应用户的会话信息",
		Solution: "",
	},
	65414: {
		Desc:     "客户正在被其他客服接待",
		Solution: "",
	},
}

// GetCgiBinCustomserviceGetonlinekflist 获取在线客服列表 (GET /cgi-bin/customservice/getonlinekflist)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-message/api_getonlinekflist.html
// GetCgiBinCustomserviceGetonlinekflistRequest carries the documented parameters of one API call.
type GetCgiBinCustomserviceGetonlinekflistRequest struct {
	// 客服子商户的business_id,对于普通小程序客服不需要填business_id
	BusinessID string `query:"business_id,omitempty"`
}

// GetCgiBinCustomserviceGetonlinekflistResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type GetCgiBinCustomserviceGetonlinekflistResponse struct {
	// 在线客服列表
	KfOnlineList []*GetCgiBinCustomserviceGetonlinekflistResponseKfOnlineListObject `json:"kf_online_list,omitempty"`
}

// GetCgiBinCustomserviceGetonlinekflistResponseKfOnlineListObject is a documented nested object.
type GetCgiBinCustomserviceGetonlinekflistResponseKfOnlineListObject struct {
	// 完整客服账号,格式为:账号前缀@公众号微信号
	KfAccount string `json:"kf_account,omitempty"`
	// 客服在线状态,目前为:0-不在线,1-web 在线
	Status int64 `json:"status,omitzero"`
	// 客服编号
	KfID int64 `json:"kf_id,omitzero"`
	// 客服当前正在接待的会话数
	AcceptedCase int64 `json:"accepted_case,omitzero"`
	// 客服openid
	KfOpenID string `json:"kf_openid,omitempty"`
}

func (c *Client) GetCgiBinCustomserviceGetonlinekflist(ctx context.Context, req *GetCgiBinCustomserviceGetonlinekflistRequest) (*GetCgiBinCustomserviceGetonlinekflistResponse, error) {
	return core.Call[GetCgiBinCustomserviceGetonlinekflistResponse](c.EndpointClient, ctx, "GET", "/cgi-bin/customservice/getonlinekflist", req, getCgiBinCustomserviceGetonlinekflistErrCodes, true, core.SignNone)
}

var getCgiBinMediaGetErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40007: {
		Desc:     "invalid media_id",
		Solution: "无效的媒体ID",
	},
}

// GetCgiBinMediaGet 获取临时素材 (GET /cgi-bin/media/get)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-message/api_getmedia.html
// GetCgiBinMediaGetRequest carries the documented parameters of one API call.
type GetCgiBinMediaGetRequest struct {
	// 媒体文件ID
	MediaID string `query:"media_id"`
}

func (c *Client) GetCgiBinMediaGet(ctx context.Context, req *GetCgiBinMediaGetRequest) ([]byte, error) {
	return core.CallBinary(c.EndpointClient, ctx, "GET", "/cgi-bin/media/get", req, getCgiBinMediaGetErrCodes, true, core.SignNone)
}

var postCgiBinMediaUploadErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40004: {
		Desc:     "invalid media type",
		Solution: "不合法的媒体文件类型",
	},
}

// PostCgiBinMediaUpload 新增临时素材 (POST /cgi-bin/media/upload)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-message/api_uploadtempmedia.html
// PostCgiBinMediaUploadRequest carries the documented parameters of one API call.
type PostCgiBinMediaUploadRequest struct {
	// 媒体文件类型,分别有图片(image)、语音(voice)、视频(video)和缩略图(thumb)
	Type string `query:"type"`
}

// PostCgiBinMediaUploadResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinMediaUploadResponse struct {
	// 媒体文件类型
	Type string `json:"type,omitempty"`
	// 媒体文件标识
	MediaID string `json:"media_id,omitempty"`
	// 上传时间戳
	CreatedAt int64 `json:"created_at,omitzero"`
}

func (c *Client) PostCgiBinMediaUpload(ctx context.Context, req *PostCgiBinMediaUploadRequest, file *core.Upload) (*PostCgiBinMediaUploadResponse, error) {
	data, err := core.CallUpload(c.EndpointClient, ctx, "/cgi-bin/media/upload", req, file, postCgiBinMediaUploadErrCodes, true)
	return core.Decode[PostCgiBinMediaUploadResponse](ctx, "POST", "/cgi-bin/media/upload", data, err)
}

var postCgiBinMessageCustomBusinessTypingErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40200: {
		Desc:     "invalid account type",
		Solution: "账号类型不符合要求",
	},
	45072: {
		Desc:     "invalid command",
		Solution: "command字段取值不对",
	},
	45080: {
		Desc:     "need sending message to user orrecving message from user in the last 30 seconds before typing",
		Solution: "下发输入状态,需要之前30秒内跟用户有过消息交互",
	},
	45081: {
		Desc:     "you are already typing",
		Solution: "已经在输入状态,不可重复下发",
	},
}

// PostCgiBinMessageCustomBusinessTyping 客服输入状态 (POST /cgi-bin/message/custom/business/typing)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-message/api_typing.html
// PostCgiBinMessageCustomBusinessTypingRequest carries the documented parameters of one API call.
type PostCgiBinMessageCustomBusinessTypingRequest struct {
	// 用户的 OpenID
	Touser string `json:"touser"`
	// 命令。Typing表示对用户下发"正在输入"状态 ;CancelTyping表示取消对用户的"正在输入"状态
	Command string `json:"command"`
	// 子商户 ID,普通账号无需填写
	Businessid string `json:"businessid,omitempty"`
}

// PostCgiBinMessageCustomBusinessTypingResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinMessageCustomBusinessTypingResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostCgiBinMessageCustomBusinessTyping(ctx context.Context, req *PostCgiBinMessageCustomBusinessTypingRequest) (*PostCgiBinMessageCustomBusinessTypingResponse, error) {
	return core.Call[PostCgiBinMessageCustomBusinessTypingResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/message/custom/business/typing", req, postCgiBinMessageCustomBusinessTypingErrCodes, true, core.SignNone)
}

var postCgiBinMessageCustomSendErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40013: {
		Desc:     "invalid appid",
		Solution: "不合法的 AppID ,请开发者检查 AppID 的正确性,避免异常字符,注意大小写",
	},
	70000: {
		Desc:     "为保护未成年人权益,该条消息发送失败",
		Solution: "",
	},
}

// PostCgiBinMessageCustomSend 发送客服消息 (POST /cgi-bin/message/custom/send)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-message/api_sendcustommessage.html
// PostCgiBinMessageCustomSendRequest carries the documented parameters of one API call.
type PostCgiBinMessageCustomSendRequest struct {
	// 用户的 OpenID
	Touser string `json:"touser"`
	// 消息类型。text表示文本消息;image表示图片消息;link表示图文链接;miniprogrampage表示小程序卡片。
	Msgtype string `json:"msgtype"`
	// 文本消息,msgtype="text" 时必填
	Text *PostCgiBinMessageCustomSendRequestTextObject `json:"text,omitempty"`
	// 图片消息,msgtype="image" 时必填
	Image *PostCgiBinMessageCustomSendRequestImageObject `json:"image,omitempty"`
	// 语音消息,msgtype="voice" 时必填
	Voice *PostCgiBinMessageCustomSendRequestVoiceObject `json:"voice,omitempty"`
	// 视频消息,msgtype="video" 时必填
	Video *PostCgiBinMessageCustomSendRequestVideoObject `json:"video,omitempty"`
	// 音乐消息,msgtype="music" 时必填
	Music *PostCgiBinMessageCustomSendRequestMusicObject `json:"music,omitempty"`
	// 图文消息(点击跳转到外链),msgtype="news" 时必填
	News *PostCgiBinMessageCustomSendRequestNewsObject `json:"news,omitempty"`
	// 图文消息(点击跳转到图文消息页面),msgtype="mpnews" 时必填,图文消息条数限制在1条以内,注意,如果图文数超过1,则将会返回错误码45008。(草稿灰度完成后,此类型不再支持)
	Mpnews *PostCgiBinMessageCustomSendRequestMpnewsObject `json:"mpnews,omitempty"`
	// 图文消息(点击跳转到图文消息页面),msgtype="mpnewsarticle" 时必填,使用通过 "发布" 系列接口得到的 article_id
	Mpnewsarticle *PostCgiBinMessageCustomSendRequestMpnewsarticleObject `json:"mpnewsarticle,omitempty"`
	// 菜单消息,msgtype="msgmenu" 时必填
	Msgmenu *PostCgiBinMessageCustomSendRequestMsgmenuObject `json:"msgmenu,omitempty"`
	// 卡券信息,msgtype="wxcard"时必填
	Wxcard *PostCgiBinMessageCustomSendRequestWxcardObject `json:"wxcard,omitempty"`
	// 小程序消息,msgtype="miniprogrampage"时必填
	Miniprogrampage *PostCgiBinMessageCustomSendRequestMiniprogrampageObject `json:"miniprogrampage,omitempty"`
	// 以某个客服账号来发消息
	Customservice *PostCgiBinMessageCustomSendRequestCustomserviceObject `json:"customservice,omitempty"`
	// ai 消息上下文
	Aimsgcontext *PostCgiBinMessageCustomSendRequestAimsgcontextObject `json:"aimsgcontext,omitempty"`
	// 子商户ID,普通账号无需传
	Businessid string `json:"businessid,omitempty"`
}

// PostCgiBinMessageCustomSendRequestTextObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestTextObject struct {
	// 文本内容,支持插入跳小程序的文字链, 例如「文本内容 点击跳小程序 」 说明: 1.data-miniprogram-appid 项,填写小程序appid,则表示该链接跳小程序; 2.data-miniprogram-path项,填写小程序路径,路径与app.json中保持一致,可带参数; 3.对于不支持data-miniprogram-appid 项的客户端版本,如果有herf项,则仍然保持跳href中的网页链接; 4.data-miniprogram-appid对应的小程序必须与公众号有绑定关系。
	Content string `json:"content"`
}

// PostCgiBinMessageCustomSendRequestImageObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestImageObject struct {
	// 媒体ID,通过素材上传接口获得。
	MediaID string `json:"media_id"`
}

// PostCgiBinMessageCustomSendRequestVoiceObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestVoiceObject struct {
	// 媒体ID,通过素材上传接口获得。
	MediaID string `json:"media_id"`
}

// PostCgiBinMessageCustomSendRequestVideoObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestVideoObject struct {
	// 媒体ID,通过素材上传接口获得。
	MediaID string `json:"media_id"`
	// 缩略图媒体ID,通过素材上传接口获得。
	ThumbMediaID string `json:"thumb_media_id"`
	// 视频标题
	Title string `json:"title,omitempty"`
	// 视频描述
	Description string `json:"description,omitempty"`
}

// PostCgiBinMessageCustomSendRequestMusicObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestMusicObject struct {
	// 音乐标题
	Title string `json:"title"`
	// 音乐描述
	Description string `json:"description"`
	// 音乐链接
	Musicurl string `json:"musicurl"`
	// 高质量音乐链接
	Hqmusicurl string `json:"hqmusicurl,omitempty"`
	// 缩略图媒体ID
	ThumbMediaID string `json:"thumb_media_id"`
}

// PostCgiBinMessageCustomSendRequestNewsObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestNewsObject struct {
	// 图文消息条数限制在1条以内
	Articles []*PostCgiBinMessageCustomSendRequestArticlesObject `json:"articles"`
}

// PostCgiBinMessageCustomSendRequestArticlesObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestArticlesObject struct {
	// 消息标题
	Title string `json:"title"`
	// 消息描述
	Description string `json:"description"`
	// 封面图片url
	Picurl string `json:"picurl"`
	// 跳转url
	URL string `json:"url"`
}

// PostCgiBinMessageCustomSendRequestMpnewsObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestMpnewsObject struct {
	// 素材ID,通过素材上传接口获得。
	MediaID string `json:"media_id"`
}

// PostCgiBinMessageCustomSendRequestMpnewsarticleObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestMpnewsarticleObject struct {
	// 发布文章ID
	ArticleID string `json:"article_id"`
}

// PostCgiBinMessageCustomSendRequestMsgmenuObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestMsgmenuObject struct {
	// 菜单描述
	HeadContent string `json:"head_content,omitempty"`
	// 菜单内容
	List []*PostCgiBinMessageCustomSendRequestListObject `json:"list"`
	// 菜单结尾
	TailContent string `json:"tail_content,omitempty"`
}

// PostCgiBinMessageCustomSendRequestListObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestListObject struct {
	// 菜单值
	ID string `json:"id"`
	// 菜单项
	Content string `json:"content"`
}

// PostCgiBinMessageCustomSendRequestWxcardObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestWxcardObject struct {
	// 卡券ID
	CardID string `json:"card_id"`
}

// PostCgiBinMessageCustomSendRequestMiniprogrampageObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestMiniprogrampageObject struct {
	// 小程序卡片标题
	Title string `json:"title"`
	// 小程序APPID
	AppID string `json:"appid"`
	// 小程序的页面路径,跟app.json对齐,支持参数,比如pages/index/index?foo=bar
	Pagepath string `json:"pagepath"`
	// 小程序消息卡片的封面, image 类型的 media_id,通过素材上传图片文件获得,建议大小为 520*416
	ThumbMediaID string `json:"thumb_media_id"`
}

// PostCgiBinMessageCustomSendRequestCustomserviceObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestCustomserviceObject struct {
	// 客服账号
	KfAccount string `json:"kf_account"`
}

// PostCgiBinMessageCustomSendRequestAimsgcontextObject is a documented nested object.
type PostCgiBinMessageCustomSendRequestAimsgcontextObject struct {
	// 消息下方增加灰色 wording "内容由第三方AI生成" 0 不增加 1 增加
	IsAiMsg int64 `json:"is_ai_msg,omitzero"`
}

// PostCgiBinMessageCustomSendResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinMessageCustomSendResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误描述
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostCgiBinMessageCustomSend(ctx context.Context, req *PostCgiBinMessageCustomSendRequest) (*PostCgiBinMessageCustomSendResponse, error) {
	return core.Call[PostCgiBinMessageCustomSendResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/message/custom/send", req, postCgiBinMessageCustomSendErrCodes, true, core.SignNone)
}

var postCustomserviceKfaccountAddErrCodes = map[int]core.ErrDoc{
	0: {
		Desc:     "ok或者in a normal state",
		Solution: "ok是指从不正常变成正常 in a normal state是指本来就正常",
	},
	40003: {
		Desc:     "非法的openid",
		Solution: "",
	},
	40005: {
		Desc:     "不支持的媒体类型",
		Solution: "",
	},
	40009: {
		Desc:     "媒体文件长度不合法",
		Solution: "",
	},
	65400: {
		Desc:     "please enable new custom service or wait for a while if you have enabled",
		Solution: "API不可用,即没有开通/升级到新客服功能",
	},
	65401: {
		Desc:     "无效客服账号",
		Solution: "",
	},
	65402: {
		Desc:     "客服账号尚未绑定微信号,不能投入使用",
		Solution: "",
	},
	65403: {
		Desc:     "illegal nickname",
		Solution: "客服昵称不合法",
	},
	65404: {
		Desc:     "illegal custom service account",
		Solution: "客服账号不合法",
	},
	65405: {
		Desc:     "custom service account number reach limit",
		Solution: "账号数目已达到上限,不能继续添加",
	},
	65406: {
		Desc:     "custom service account exists",
		Solution: "已经存在的客服账号",
	},
	65407: {
		Desc:     "邀请对象已经是该小程序客服",
		Solution: "",
	},
	65408: {
		Desc:     "本小程序已经有一个邀请给该微信",
		Solution: "",
	},
	65409: {
		Desc:     "无效的微信号",
		Solution: "",
	},
	65410: {
		Desc:     "邀请对象绑定小程序客服数达到上限",
		Solution: "",
	},
	65411: {
		Desc:     "该账号已经有一个等待确认的邀请,不能重复邀请",
		Solution: "",
	},
	65412: {
		Desc:     "该账号已经绑定微信号,不能进行邀请",
		Solution: "",
	},
	65413: {
		Desc:     "不存在对应用户的会话信息",
		Solution: "",
	},
	65414: {
		Desc:     "客户正在被其他客服接待",
		Solution: "",
	},
}

// PostCustomserviceKfaccountAdd 添加客服账号 (POST /customservice/kfaccount/add)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-message/api_addkfaccount.html
// PostCustomserviceKfaccountAddRequest carries the documented parameters of one API call.
type PostCustomserviceKfaccountAddRequest struct {
	// 完整客服账号,格式为:账号前缀@公众号微信号,账号前缀最多10个字符,必须是英文、数字字符或者下划线,后缀为公众号微信号,长度不超过30个字符
	KfAccount string `json:"kf_account"`
	// 客服昵称,最长16个字
	Nickname string `json:"nickname"`
	// 客服子商户的business_id,对于普通账号客服不需要填business_id
	BusinessID string `json:"business_id,omitempty"`
}

// PostCustomserviceKfaccountAddResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCustomserviceKfaccountAddResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误描述
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostCustomserviceKfaccountAdd(ctx context.Context, req *PostCustomserviceKfaccountAddRequest) (*PostCustomserviceKfaccountAddResponse, error) {
	return core.Call[PostCustomserviceKfaccountAddResponse](c.EndpointClient, ctx, "POST", "/customservice/kfaccount/add", req, postCustomserviceKfaccountAddErrCodes, true, core.SignNone)
}

var getCustomserviceKfaccountCanceladminErrCodes = map[int]core.ErrDoc{
	0: {
		Desc:     "成功",
		Solution: "",
	},
	40003: {
		Desc:     "非法的openid",
		Solution: "",
	},
	40005: {
		Desc:     "不支持的媒体类型",
		Solution: "",
	},
	40009: {
		Desc:     "媒体文件长度不合法",
		Solution: "",
	},
	65400: {
		Desc:     "API不可用,即没有开通/升级到新版客服功能",
		Solution: "",
	},
	65401: {
		Desc:     "无效客服账号",
		Solution: "",
	},
	65402: {
		Desc:     "客服账号尚未绑定微信号,不能投入使用",
		Solution: "",
	},
	65403: {
		Desc:     "客服昵称不合法",
		Solution: "",
	},
	65404: {
		Desc:     "客服账号不合法",
		Solution: "",
	},
	65405: {
		Desc:     "账号数目已达到上限,不能继续添加",
		Solution: "",
	},
	65406: {
		Desc:     "已经存在的客服账号",
		Solution: "",
	},
	65407: {
		Desc:     "邀请对象已经是该小程序客服",
		Solution: "",
	},
	65408: {
		Desc:     "本小程序已经有一个邀请给该微信",
		Solution: "",
	},
	65409: {
		Desc:     "无效的微信号",
		Solution: "",
	},
	65410: {
		Desc:     "邀请对象绑定小程序客服数达到上限",
		Solution: "",
	},
	65411: {
		Desc:     "该账号已经有一个等待确认的邀请,不能重复邀请",
		Solution: "",
	},
	65412: {
		Desc:     "该账号已经绑定微信号,不能进行邀请",
		Solution: "",
	},
	65413: {
		Desc:     "不存在对应用户的会话信息",
		Solution: "",
	},
	65414: {
		Desc:     "客户正在被其他客服接待",
		Solution: "",
	},
}

// GetCustomserviceKfaccountCanceladmin 取消客服管理员 (GET /customservice/kfaccount/canceladmin)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-message/api_cancelkfadmin.html
// GetCustomserviceKfaccountCanceladminRequest carries the documented parameters of one API call.
type GetCustomserviceKfaccountCanceladminRequest struct {
	// 账号openid
	KfOpenID string `query:"kf_openid"`
	// 客服子商户的business_id,对于普通账号客服不需要填business_id
	BusinessID string `query:"business_id,omitempty"`
}

// GetCustomserviceKfaccountCanceladminResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type GetCustomserviceKfaccountCanceladminResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误描述
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) GetCustomserviceKfaccountCanceladmin(ctx context.Context, req *GetCustomserviceKfaccountCanceladminRequest) (*GetCustomserviceKfaccountCanceladminResponse, error) {
	return core.Call[GetCustomserviceKfaccountCanceladminResponse](c.EndpointClient, ctx, "GET", "/customservice/kfaccount/canceladmin", req, getCustomserviceKfaccountCanceladminErrCodes, true, core.SignNone)
}

var postCustomserviceKfaccountDelErrCodes = map[int]core.ErrDoc{
	0: {
		Desc:     "ok或者in a normal state",
		Solution: "ok是指从不正常变成正常 in a normal state是指本来就正常",
	},
	40003: {
		Desc:     "非法的openid",
		Solution: "",
	},
	40005: {
		Desc:     "不支持的媒体类型",
		Solution: "",
	},
	40009: {
		Desc:     "媒体文件长度不合法",
		Solution: "",
	},
	65400: {
		Desc:     "please enable new custom service or wait for a while if you have enabled",
		Solution: "API不可用,即没有开通/升级到新版客服功能",
	},
	65401: {
		Desc:     "invalid custom service account",
		Solution: "无效客服账号",
	},
	65402: {
		Desc:     "客服账号尚未绑定微信号,不能投入使用",
		Solution: "",
	},
	65403: {
		Desc:     "客服昵称不合法",
		Solution: "",
	},
	65404: {
		Desc:     "客服账号不合法",
		Solution: "",
	},
	65405: {
		Desc:     "账号数目已达到上限,不能继续添加",
		Solution: "",
	},
	65406: {
		Desc:     "已经存在的客服账号",
		Solution: "",
	},
	65407: {
		Desc:     "邀请对象已经是该小程序客服",
		Solution: "",
	},
	65408: {
		Desc:     "本小程序已经有一个邀请给该微信",
		Solution: "",
	},
	65409: {
		Desc:     "无效的微信号",
		Solution: "",
	},
	65410: {
		Desc:     "邀请对象绑定小程序客服数达到上限",
		Solution: "",
	},
	65411: {
		Desc:     "该账号已经有一个等待确认的邀请,不能重复邀请",
		Solution: "",
	},
	65412: {
		Desc:     "该账号已经绑定微信号,不能进行邀请",
		Solution: "",
	},
	65413: {
		Desc:     "不存在对应用户的会话信息",
		Solution: "",
	},
	65414: {
		Desc:     "客户正在被其他客服接待",
		Solution: "",
	},
}

// PostCustomserviceKfaccountDel 删除客服账号 (POST /customservice/kfaccount/del)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-message/api_delkfaccount.html
// PostCustomserviceKfaccountDelRequest carries the documented parameters of one API call.
type PostCustomserviceKfaccountDelRequest struct {
	// 完整客服帐号,格式为:帐号前缀@公众号微信号
	KfAccount string `json:"kf_account"`
	// 客服子商户的business_id,对于普通账号客服不需要填business_id
	BusinessID string `json:"business_id,omitempty"`
}

// PostCustomserviceKfaccountDelResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCustomserviceKfaccountDelResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostCustomserviceKfaccountDel(ctx context.Context, req *PostCustomserviceKfaccountDelRequest) (*PostCustomserviceKfaccountDelResponse, error) {
	return core.Call[PostCustomserviceKfaccountDelResponse](c.EndpointClient, ctx, "POST", "/customservice/kfaccount/del", req, postCustomserviceKfaccountDelErrCodes, true, core.SignNone)
}

var getCustomserviceKfaccountSetadminErrCodes = map[int]core.ErrDoc{
	0: {
		Desc:     "成功",
		Solution: "",
	},
	40003: {
		Desc:     "非法的openid",
		Solution: "",
	},
	40005: {
		Desc:     "不支持的媒体类型",
		Solution: "",
	},
	40009: {
		Desc:     "媒体文件长度不合法",
		Solution: "",
	},
	65400: {
		Desc:     "API不可用,即没有开通/升级到新版客服功能",
		Solution: "",
	},
	65401: {
		Desc:     "无效客服账号",
		Solution: "",
	},
	65402: {
		Desc:     "客服账号尚未绑定微信号,不能投入使用",
		Solution: "",
	},
	65403: {
		Desc:     "客服昵称不合法",
		Solution: "",
	},
	65404: {
		Desc:     "客服账号不合法",
		Solution: "",
	},
	65405: {
		Desc:     "账号数目已达到上限,不能继续添加",
		Solution: "",
	},
	65406: {
		Desc:     "已经存在的客服账号",
		Solution: "",
	},
	65407: {
		Desc:     "邀请对象已经是该小程序客服",
		Solution: "",
	},
	65408: {
		Desc:     "本小程序已经有一个邀请给该微信",
		Solution: "",
	},
	65409: {
		Desc:     "无效的微信号",
		Solution: "",
	},
	65410: {
		Desc:     "邀请对象绑定小程序客服数达到上限",
		Solution: "",
	},
	65411: {
		Desc:     "该账号已经有一个等待确认的邀请,不能重复邀请",
		Solution: "",
	},
	65412: {
		Desc:     "该账号已经绑定微信号,不能进行邀请",
		Solution: "",
	},
	65413: {
		Desc:     "不存在对应用户的会话信息",
		Solution: "",
	},
	65414: {
		Desc:     "客户正在被其他客服接待",
		Solution: "",
	},
}

// GetCustomserviceKfaccountSetadmin 设置客服管理员 (GET /customservice/kfaccount/setadmin)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/kf-mgnt/kf-message/api_setkfadmin.html
// GetCustomserviceKfaccountSetadminRequest carries the documented parameters of one API call.
type GetCustomserviceKfaccountSetadminRequest struct {
	// 账号openid
	KfOpenID string `query:"kf_openid"`
	// 客服子商户的business_id,对于普通账号客服不需要填business_id
	BusinessID string `query:"business_id,omitempty"`
}

// GetCustomserviceKfaccountSetadminResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type GetCustomserviceKfaccountSetadminResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误描述
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) GetCustomserviceKfaccountSetadmin(ctx context.Context, req *GetCustomserviceKfaccountSetadminRequest) (*GetCustomserviceKfaccountSetadminResponse, error) {
	return core.Call[GetCustomserviceKfaccountSetadminResponse](c.EndpointClient, ctx, "GET", "/customservice/kfaccount/setadmin", req, getCustomserviceKfaccountSetadminErrCodes, true, core.SignNone)
}
