// Code generated by docsync from the official WeChat documentation. DO NOT EDIT.
// The API surface (names, request/response shapes) is derived deterministically
// from the endpoints; regenerate with "make docs-sync". If this file changes
// under you, the upstream documentation changed.

package miniprogram

import (
	"context"
	"github.com/go-sphere/weixin-api/core"
)

var postCgiBinMessageWxopenEmployeerelationmsgSendErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	40256: {
		Desc:     "invalid employee relation",
		Solution: "向非绑定用工关系的用户推送消息",
	},
	40257: {
		Desc:     "decode touser error",
		Solution: "解析接收用户openid错误",
	},
	43104: {
		Desc:     "this app does not have poermission",
		Solution: "app无权限推送模版消息",
	},
	50001: {
		Desc:     "user unauthorized",
		Solution: "用户未订阅模版",
	},
}

// PostCgiBinMessageWxopenEmployeerelationmsgSend 推送用工消息 (POST /cgi-bin/message/wxopen/employeerelationmsg/send)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/laboruse/api_sendemployeerelationmsg.html
// PostCgiBinMessageWxopenEmployeerelationmsgSendRequest carries the documented parameters of one API call.
type PostCgiBinMessageWxopenEmployeerelationmsgSendRequest struct {
	// 消息模版id
	TemplateID string `json:"template_id"`
	// 跳转路径
	Page string `json:"page"`
	// 被推送用户openid
	Touser string `json:"touser"`
	// 消息内容
	Data string `json:"data"`
}

// PostCgiBinMessageWxopenEmployeerelationmsgSendResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostCgiBinMessageWxopenEmployeerelationmsgSendResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostCgiBinMessageWxopenEmployeerelationmsgSend(ctx context.Context, req *PostCgiBinMessageWxopenEmployeerelationmsgSendRequest) (*PostCgiBinMessageWxopenEmployeerelationmsgSendResponse, error) {
	return core.Call[PostCgiBinMessageWxopenEmployeerelationmsgSendResponse](c.EndpointClient, ctx, "POST", "/cgi-bin/message/wxopen/employeerelationmsg/send", req, postCgiBinMessageWxopenEmployeerelationmsgSendErrCodes, true, core.SignNone)
}

var postWxaBusinessUnbinduserb2CauthinfoErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40003: {
		Desc:     "invalid openid",
		Solution: "不合法的 OpenID ,请开发者确认 OpenID 的有效性",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
}

// PostWxaBusinessUnbinduserb2Cauthinfo 解绑用工关系 (POST /wxa/business/unbinduserb2cauthinfo)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/laboruse/api_unbinduserb2cauthinfo.html
// PostWxaBusinessUnbinduserb2CauthinfoRequest carries the documented parameters of one API call.
type PostWxaBusinessUnbinduserb2CauthinfoRequest struct {
	// 被解绑用户的openid列表
	OpenIDList []string `json:"openid_list"`
}

// PostWxaBusinessUnbinduserb2CauthinfoResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBusinessUnbinduserb2CauthinfoResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaBusinessUnbinduserb2Cauthinfo(ctx context.Context, req *PostWxaBusinessUnbinduserb2CauthinfoRequest) (*PostWxaBusinessUnbinduserb2CauthinfoResponse, error) {
	return core.Call[PostWxaBusinessUnbinduserb2CauthinfoResponse](c.EndpointClient, ctx, "POST", "/wxa/business/unbinduserb2cauthinfo", req, postWxaBusinessUnbinduserb2CauthinfoErrCodes, true, core.SignNone)
}
