// Code generated by docsync from the official WeChat documentation. DO NOT EDIT.
// The API surface (names, request/response shapes) is derived deterministically
// from the endpoints; regenerate with "make docs-sync". If this file changes
// under you, the upstream documentation changed.

package miniprogram

import (
	"context"
	"github.com/go-sphere/weixin-api/core"
)

var postWxaBookAddbookauthErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookAddbookauth 新增账号-小说授权 (POST /wxa/book/addbookauth)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/auth/api_addbookauth.html
// PostWxaBookAddbookauthRequest carries the documented parameters of one API call.
type PostWxaBookAddbookauthRequest struct {
	// books
	Books []*PostWxaBookAddbookauthRequestBooksObject `json:"books"`
}

// PostWxaBookAddbookauthRequestBooksObject is a documented nested object.
type PostWxaBookAddbookauthRequestBooksObject struct {
	// 作品id
	BookID string `json:"book_id"`
	// 被授权账号appid
	GranteeAppID string `json:"grantee_appid"`
	// 授权到期时间unix时间戳,单位秒,按CST时区 可支持设置的最大值: 2147483646
	ExpireTime int64 `json:"expire_time"`
}

// PostWxaBookAddbookauthResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookAddbookauthResponse struct {
	// 错误码。 因为新增授权可以一次增加多条授权关系,所以返回数据里 errcode 会有内外两个字段,外层 errcode 表示本次调用整体成功/失败,内层 errcode 表示每条授权关系是成功/失败。 具体可以看返回数据的示例
	Errcode int64 `json:"errcode,omitzero"`
	// results
	Results []*PostWxaBookAddbookauthResponseResultsObject `json:"results,omitempty"`
}

// PostWxaBookAddbookauthResponseResultsObject is a documented nested object.
type PostWxaBookAddbookauthResponseResultsObject struct {
	// 内层errcode,表示每条授权关系是成功/失败
	Errcode int64 `json:"errcode,omitzero"`
}

func (c *Client) PostWxaBookAddbookauth(ctx context.Context, req *PostWxaBookAddbookauthRequest) (*PostWxaBookAddbookauthResponse, error) {
	return core.Call[PostWxaBookAddbookauthResponse](c.EndpointClient, ctx, "POST", "/wxa/book/addbookauth", req, postWxaBookAddbookauthErrCodes, true, core.SignNone)
}

// PostWxaBookAddbookauthbyappid 新增账号-账号授权 (POST /wxa/book/addbookauthbyappid)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/auth/api_addbookauthbyappid.html
// PostWxaBookAddbookauthbyappidRequest carries the documented parameters of one API call.
type PostWxaBookAddbookauthbyappidRequest struct {
	// 被授权账号列表。上限一次 20 条
	Infos []*PostWxaBookAddbookauthbyappidRequestInfosObject `json:"infos"`
}

// PostWxaBookAddbookauthbyappidRequestInfosObject is a documented nested object.
type PostWxaBookAddbookauthbyappidRequestInfosObject struct {
	// 被授权账号appid
	GranteeAppID string `json:"grantee_appid"`
	// 授权到期时间,unix时间戳,单位秒,按CST时区
	ExpireTime int64 `json:"expire_time"`
}

// PostWxaBookAddbookauthbyappidResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookAddbookauthbyappidResponse struct {
	// 错误码。 因为新增授权可以一次增加多条授权关系,所以返回数据里 `errcode` 会有内外两个字段,外层 `errcode` 表示本次调用整体成功/失败,内层 `errcode` 表示每条授权关系是成功/失败。 具体可以看返回数据的示例
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 授权结果列表
	Results []string `json:"results,omitempty"`
}

func (c *Client) PostWxaBookAddbookauthbyappid(ctx context.Context, req *PostWxaBookAddbookauthbyappidRequest) (*PostWxaBookAddbookauthbyappidResponse, error) {
	return core.Call[PostWxaBookAddbookauthbyappidResponse](c.EndpointClient, ctx, "POST", "/wxa/book/addbookauthbyappid", req, nil, true, core.SignNone)
}

var postWxaBookAuditbookErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookAuditbook 作品提审 (POST /wxa/book/auditbook)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_auditbook.html
// PostWxaBookAuditbookRequest carries the documented parameters of one API call.
type PostWxaBookAuditbookRequest struct {
	// 作品id
	BookID string `json:"book_id"`
}

// PostWxaBookAuditbookResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookAuditbookResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaBookAuditbook(ctx context.Context, req *PostWxaBookAuditbookRequest) (*PostWxaBookAuditbookResponse, error) {
	return core.Call[PostWxaBookAuditbookResponse](c.EndpointClient, ctx, "POST", "/wxa/book/auditbook", req, postWxaBookAuditbookErrCodes, true, core.SignNone)
}

var postWxaBookBatchcreatechapterErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookBatchcreatechapter 批量上传章节 (POST /wxa/book/batchcreatechapter)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_batchcreatechapter.html
// PostWxaBookBatchcreatechapterRequest carries the documented parameters of one API call.
type PostWxaBookBatchcreatechapterRequest struct {
	// 作品id
	BookID string `json:"book_id"`
	// 章节信息,单次最多上传 10 章。
	ChapterList []*PostWxaBookBatchcreatechapterRequestChapterListObject `json:"chapter_list"`
}

// PostWxaBookBatchcreatechapterRequestChapterListObject is a documented nested object.
type PostWxaBookBatchcreatechapterRequestChapterListObject struct {
	// 章节标题。长度限制 1-80 字。
	ChapterTitle string `json:"chapter_title"`
	// 章节内容。长度限制 1-20000 字。
	Content string `json:"content"`
	// 提供方章节主键,可用于去重。长度限制 0-255 字节。
	OriginalID string `json:"original_id,omitempty"`
	// 章节相对顺序,可非连续递增,默认值:0。详见注意事项。
	Seq int64 `json:"seq,omitzero"`
	// 自定义信息。长度限制 0-128 字节
	CustomInfo string `json:"custom_info,omitempty"`
}

// PostWxaBookBatchcreatechapterResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookBatchcreatechapterResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 章节id。非定长,不超过 64 字节。
	ChapterID []string `json:"chapter_id,omitempty"`
	// 冲突的章节主键列表
	ConflictOriginalIDList []string `json:"conflict_original_id_list,omitempty"`
}

func (c *Client) PostWxaBookBatchcreatechapter(ctx context.Context, req *PostWxaBookBatchcreatechapterRequest) (*PostWxaBookBatchcreatechapterResponse, error) {
	return core.Call[PostWxaBookBatchcreatechapterResponse](c.EndpointClient, ctx, "POST", "/wxa/book/batchcreatechapter", req, postWxaBookBatchcreatechapterErrCodes, true, core.SignNone)
}

var postWxaBookCreatebookErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookCreatebook 创建作品 (POST /wxa/book/createbook)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_createbook.html
// PostWxaBookCreatebookRequest carries the documented parameters of one API call.
type PostWxaBookCreatebookRequest struct {
	// 作品名,示例值:"斗破苍穹"。长度限制1-30字。
	Title string `json:"title"`
	// 作品简介。长度限制1-500字。
	Intro string `json:"intro"`
	// 封面图 media_id,通过 新增临时素材接口 上传得到
	CoverMediaID string `json:"cover_media_id"`
	// 作者名。长度限制1-100字。
	Author string `json:"author"`
	// 一级类型id。可选类型见 小说作品类型
	FirstCategoryID int64 `json:"first_category_id"`
	// 二级类型id
	SecondCategoryID int64 `json:"second_category_id"`
	// 三级类型id
	ThirdCategoryID int64 `json:"third_category_id"`
	// 完结状态,1:连载中,2:已完结
	CompleteStatus int64 `json:"complete_status"`
	// 提供方作品主键,可用于去重。长度限制0-255字节。
	OriginalID string `json:"original_id,omitempty"`
	// 章节排序方式,0:追加,1:seq 递增。默认值:0。
	ChapterOrderMethod int64 `json:"chapter_order_method,omitzero"`
	// 自定义信息。长度限制0-128字节。
	CustomInfo string `json:"custom_info,omitempty"`
	// 题材关键词。最多传入3个关键词,每个关键词长度限制1-4字。
	KeywordList []string `json:"keyword_list,omitempty"`
	// 精彩片段。需为本书内容,长度限制400-1000字。
	AwesomeParagraph string `json:"awesome_paragraph,omitempty"`
}

// PostWxaBookCreatebookResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookCreatebookResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 作品id。非定长,不超过 64 字节。
	BookID string `json:"book_id,omitempty"`
}

func (c *Client) PostWxaBookCreatebook(ctx context.Context, req *PostWxaBookCreatebookRequest) (*PostWxaBookCreatebookResponse, error) {
	return core.Call[PostWxaBookCreatebookResponse](c.EndpointClient, ctx, "POST", "/wxa/book/createbook", req, postWxaBookCreatebookErrCodes, true, core.SignNone)
}

var postWxaBookCreatechapterErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookCreatechapter 上传章节 (POST /wxa/book/createchapter)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_createchapter.html
// PostWxaBookCreatechapterRequest carries the documented parameters of one API call.
type PostWxaBookCreatechapterRequest struct {
	// 作品id
	BookID string `json:"book_id"`
	// 章节信息
	Chapter *PostWxaBookCreatechapterRequestChapterObject `json:"chapter"`
}

// PostWxaBookCreatechapterRequestChapterObject is a documented nested object.
type PostWxaBookCreatechapterRequestChapterObject struct {
	// 章节标题。长度限制 1-80 字。
	ChapterTitle string `json:"chapter_title"`
	// 章节内容。长度限制 1-20000 字。
	Content string `json:"content"`
	// 提供方章节主键,可用于去重。长度限制 0-255 字节。
	OriginalID string `json:"original_id,omitempty"`
	// 章节相对顺序,可非连续递增,默认值:0。详见注意事项。
	Seq int64 `json:"seq,omitzero"`
	// 自定义信息。长度限制 0-128 字节
	CustomInfo string `json:"custom_info,omitempty"`
}

// PostWxaBookCreatechapterResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookCreatechapterResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 章节id。非定长,不超过 64 字节。
	ChapterID string `json:"chapter_id,omitempty"`
}

func (c *Client) PostWxaBookCreatechapter(ctx context.Context, req *PostWxaBookCreatechapterRequest) (*PostWxaBookCreatechapterResponse, error) {
	return core.Call[PostWxaBookCreatechapterResponse](c.EndpointClient, ctx, "POST", "/wxa/book/createchapter", req, postWxaBookCreatechapterErrCodes, true, core.SignNone)
}

var postWxaBookDelbookauthErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookDelbookauth 删除指定的授权关系 (POST /wxa/book/delbookauth)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/auth/api_delbookauth.html
// PostWxaBookDelbookauthRequest carries the documented parameters of one API call.
type PostWxaBookDelbookauthRequest struct {
	// 作品id
	BookID string `json:"book_id"`
	// 被授权账号appid
	GranteeAppID string `json:"grantee_appid"`
}

// PostWxaBookDelbookauthResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookDelbookauthResponse struct {
	// 错误码。
	Errcode int64 `json:"errcode,omitzero"`
}

func (c *Client) PostWxaBookDelbookauth(ctx context.Context, req *PostWxaBookDelbookauthRequest) (*PostWxaBookDelbookauthResponse, error) {
	return core.Call[PostWxaBookDelbookauthResponse](c.EndpointClient, ctx, "POST", "/wxa/book/delbookauth", req, postWxaBookDelbookauthErrCodes, true, core.SignNone)
}

// PostWxaBookDelbookauthbyappid 删除指定的账号授权关系 (POST /wxa/book/delbookauthbyappid)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/auth/api_delbookauthbyappid.html
// PostWxaBookDelbookauthbyappidRequest carries the documented parameters of one API call.
type PostWxaBookDelbookauthbyappidRequest struct {
	// 被授权账号appid
	GranteeAppID string `json:"grantee_appid"`
}

// PostWxaBookDelbookauthbyappidResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookDelbookauthbyappidResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaBookDelbookauthbyappid(ctx context.Context, req *PostWxaBookDelbookauthbyappidRequest) (*PostWxaBookDelbookauthbyappidResponse, error) {
	return core.Call[PostWxaBookDelbookauthbyappidResponse](c.EndpointClient, ctx, "POST", "/wxa/book/delbookauthbyappid", req, nil, true, core.SignNone)
}

var postWxaBookDeletebookErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookDeletebook 删除作品 (POST /wxa/book/deletebook)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_deletebook.html
// PostWxaBookDeletebookRequest carries the documented parameters of one API call.
type PostWxaBookDeletebookRequest struct {
	// 作品id
	BookID string `json:"book_id"`
}

// PostWxaBookDeletebookResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookDeletebookResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaBookDeletebook(ctx context.Context, req *PostWxaBookDeletebookRequest) (*PostWxaBookDeletebookResponse, error) {
	return core.Call[PostWxaBookDeletebookResponse](c.EndpointClient, ctx, "POST", "/wxa/book/deletebook", req, postWxaBookDeletebookErrCodes, true, core.SignNone)
}

var postWxaBookDeletechapterErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookDeletechapter 删除章节 (POST /wxa/book/deletechapter)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_deletechapter.html
// PostWxaBookDeletechapterRequest carries the documented parameters of one API call.
type PostWxaBookDeletechapterRequest struct {
	// 作品id
	BookID string `json:"book_id"`
	// 章节id
	ChapterID string `json:"chapter_id"`
}

// PostWxaBookDeletechapterResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookDeletechapterResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaBookDeletechapter(ctx context.Context, req *PostWxaBookDeletechapterRequest) (*PostWxaBookDeletechapterResponse, error) {
	return core.Call[PostWxaBookDeletechapterResponse](c.EndpointClient, ctx, "POST", "/wxa/book/deletechapter", req, postWxaBookDeletechapterErrCodes, true, core.SignNone)
}

var postWxaBookGetbookErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookGetbook 获取作品信息 (POST /wxa/book/getbook)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_getbook.html
// PostWxaBookGetbookRequest carries the documented parameters of one API call.
type PostWxaBookGetbookRequest struct {
	// 作品id,与提供方作品主键二选一,优先使用该字段
	BookID string `json:"book_id,omitempty"`
	// true:编辑版信息,false:发布版信息。默认值:false
	NeedEditedData bool `json:"need_edited_data,omitzero"`
	// 提供方作品主键,与作品id二选一
	OriginalID string `json:"original_id,omitempty"`
}

// PostWxaBookGetbookResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookGetbookResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 作品信息
	Book []*PostWxaBookGetbookResponseBookObject `json:"book,omitempty"`
}

// PostWxaBookGetbookResponseBookObject is a documented nested object.
type PostWxaBookGetbookResponseBookObject struct {
	// 作品id
	BookID string `json:"book_id,omitempty"`
	// 作品名
	Title string `json:"title,omitempty"`
	// 作品简介
	Intro string `json:"intro,omitempty"`
	// 封面图url
	CoverURL string `json:"cover_url,omitempty"`
	// 作者名
	Author string `json:"author,omitempty"`
	// 一级类型id
	FirstCategoryID int64 `json:"first_category_id,omitzero"`
	// 一级类型名
	FirstCategoryName string `json:"first_category_name,omitempty"`
	// 二级类型id
	SecondCategoryID int64 `json:"second_category_id,omitzero"`
	// 二级类型名
	SecondCategoryName string `json:"second_category_name,omitempty"`
	// 三级类型id
	ThirdCategoryID int64 `json:"third_category_id,omitzero"`
	// 三级类型名
	ThirdCategoryName string `json:"third_category_name,omitempty"`
	// 完结状态,1:连载中,2:已完结
	CompleteStatus int64 `json:"complete_status,omitzero"`
	// 上传场景,1:本地上传,2:API上传
	UploadScene int64 `json:"upload_scene,omitzero"`
	// 章节数
	ChapterCnt int64 `json:"chapter_cnt,omitzero"`
	// 分卷数
	VolumeCnt int64 `json:"volume_cnt,omitzero"`
	// 分卷信息
	VolumeList []map[string]any `json:"volume_list,omitempty"`
	// 作品总字数
	TotalWordCnt int64 `json:"total_word_cnt,omitzero"`
	// 审核信息。未发起审核不返回该字段。
	AuditInfo map[string]any `json:"audit_info,omitempty"`
	// 创建时间戳
	CreateTime int64 `json:"create_time,omitzero"`
	// 提供方作品主键
	OriginalID string `json:"original_id,omitempty"`
	// 章节排序方式,0:追加,1:seq 递增
	ChapterOrderMethod int64 `json:"chapter_order_method,omitzero"`
	// 自定义信息
	CustomInfo string `json:"custom_info,omitempty"`
	// 管控状态,0:正常,1:下架
	BanStatus int64 `json:"ban_status,omitzero"`
}

func (c *Client) PostWxaBookGetbook(ctx context.Context, req *PostWxaBookGetbookRequest) (*PostWxaBookGetbookResponse, error) {
	return core.Call[PostWxaBookGetbookResponse](c.EndpointClient, ctx, "POST", "/wxa/book/getbook", req, postWxaBookGetbookErrCodes, true, core.SignNone)
}

var postWxaBookGetchapterErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookGetchapter 获取章节信息 (POST /wxa/book/getchapter)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_getchapter.html
// PostWxaBookGetchapterRequest carries the documented parameters of one API call.
type PostWxaBookGetchapterRequest struct {
	// 作品id
	BookID string `json:"book_id,omitempty"`
	// 章节id
	ChapterID string `json:"chapter_id,omitempty"`
	// true:编辑版信息,false:发布版信息。默认值:false
	NeedEditedData bool `json:"need_edited_data,omitzero"`
}

// PostWxaBookGetchapterResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookGetchapterResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 章节信息
	Chapter *PostWxaBookGetchapterResponseChapterObject `json:"chapter,omitempty"`
}

// PostWxaBookGetchapterResponseChapterObject is a documented nested object.
type PostWxaBookGetchapterResponseChapterObject struct {
	// 章节id
	ChapterID string `json:"chapter_id,omitempty"`
	// 章节标题
	ChapterTitle string `json:"chapter_title,omitempty"`
	// 字数
	WordCnt int64 `json:"word_cnt,omitzero"`
	// 创建时间戳
	CreateTime int64 `json:"create_time,omitzero"`
	// 审核信息
	AuditInfo *PostWxaBookGetchapterResponseAuditInfoObject `json:"audit_info,omitempty"`
	// 所属分卷下标,-1 表示不属于任何分卷
	VolumeIndex int64 `json:"volume_index,omitzero"`
	// 提供方章节主键
	OriginalID string `json:"original_id,omitempty"`
	// 章节相对顺序
	Seq int64 `json:"seq,omitzero"`
	// 自定义信息
	CustomInfo string `json:"custom_info,omitempty"`
	// 管控状态,0:正常,1:下架
	BanStatus int64 `json:"ban_status,omitzero"`
}

// PostWxaBookGetchapterResponseAuditInfoObject is a documented nested object.
type PostWxaBookGetchapterResponseAuditInfoObject struct {
	// 0:未提审,1:审核中,2:审核不通过,3:审核通过
	AuditStatus int64 `json:"audit_status,omitzero"`
	// 提审时间戳
	CreateTime int64 `json:"create_time,omitzero"`
	// 审核时间戳
	AuditTime int64 `json:"audit_time,omitzero"`
	// 审核原因
	Reason string `json:"reason,omitempty"`
	// 修改建议。审核不通过时才会有该字段
	Suggestion string `json:"suggestion,omitempty"`
}

func (c *Client) PostWxaBookGetchapter(ctx context.Context, req *PostWxaBookGetchapterRequest) (*PostWxaBookGetchapterResponse, error) {
	return core.Call[PostWxaBookGetchapterResponse](c.EndpointClient, ctx, "POST", "/wxa/book/getchapter", req, postWxaBookGetchapterErrCodes, true, core.SignNone)
}

var postWxaBookListbookErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookListbook 获取作品列表 (POST /wxa/book/listbook)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_listbook.html
// PostWxaBookListbookRequest carries the documented parameters of one API call.
type PostWxaBookListbookRequest struct {
	// 分页拉取的最大返回结果数。取值范围 1-100,默认值:100
	Limit int64 `json:"limit,omitzero"`
	// 分页拉取的起始偏移量,默认值:0。offset 和 last_id 二选一,优先使用 last_id。
	Offset int64 `json:"offset,omitzero"`
	// 分页 id。首次调用填 0,后续调用填上次返回参数里的 last_id。offset 和 last_id 二选一,优先使用 last_id。
	LastID int64 `json:"last_id,omitzero"`
	// true:编辑版信息,false:发布版信息。默认值:false
	NeedEditedData bool `json:"need_edited_data,omitzero"`
}

// PostWxaBookListbookResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookListbookResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 作品信息列表
	BookList []*PostWxaBookListbookResponseBookListObject `json:"book_list,omitempty"`
	// 作品总数
	TotalCnt int64 `json:"total_cnt,omitzero"`
	// 分页 id。仅当请求参数有设置 last_id 且作品信息列表不为空时才有该字段
	LastID int64 `json:"last_id,omitzero"`
}

// PostWxaBookListbookResponseBookListObject is a documented nested object.
type PostWxaBookListbookResponseBookListObject struct {
	// 作品id
	BookID string `json:"book_id,omitempty"`
	// 作品名
	Title int64 `json:"title,omitzero"`
	// 作品简介
	Intro string `json:"intro,omitempty"`
	// 封面图url
	CoverURL string `json:"cover_url,omitempty"`
	// 作者名
	Author string `json:"author,omitempty"`
	// 一级类型id
	FirstCategoryID int64 `json:"first_category_id,omitzero"`
	// 二级类型id
	SecondCategoryID int64 `json:"second_category_id,omitzero"`
	// 三级类型id
	ThirdCategoryID int64 `json:"third_category_id,omitzero"`
	// 完结状态,1:连载中,2:已完结
	CompleteStatus int64 `json:"complete_status,omitzero"`
	// 上传场景,1:本地上传,2:API上传
	UploadScene int64 `json:"upload_scene,omitzero"`
	// 章节数量
	ChapterCnt int64 `json:"chapter_cnt,omitzero"`
	// 分卷数量
	VolumeCnt int64 `json:"volume_cnt,omitzero"`
	// 作品总字数
	TotalWordCnt int64 `json:"total_word_cnt,omitzero"`
	// 审核信息。未发起审核不返回该字段。
	AuditInfo map[string]any `json:"audit_info,omitempty"`
	// 创建时间戳
	CreateTime int64 `json:"create_time,omitzero"`
	// 提供方作品主键
	OriginalID string `json:"original_id,omitempty"`
	// 章节排序方式,0:追加,1:seq 递增
	ChapterOrderMethod int64 `json:"chapter_order_method,omitzero"`
	// 自定义信息
	CustomInfo string `json:"custom_info,omitempty"`
	// 管控状态,0:正常,1:下架
	BanStatus int64 `json:"ban_status,omitzero"`
}

func (c *Client) PostWxaBookListbook(ctx context.Context, req *PostWxaBookListbookRequest) (*PostWxaBookListbookResponse, error) {
	return core.Call[PostWxaBookListbookResponse](c.EndpointClient, ctx, "POST", "/wxa/book/listbook", req, postWxaBookListbookErrCodes, true, core.SignNone)
}

var postWxaBookListchapterErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookListchapter 获取章节列表 (POST /wxa/book/listchapter)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_listchapter.html
// PostWxaBookListchapterRequest carries the documented parameters of one API call.
type PostWxaBookListchapterRequest struct {
	// 作品id
	BookID string `json:"book_id"`
	// true:编辑版信息,false:发布版信息。默认值:false
	NeedEditedData bool `json:"need_edited_data,omitzero"`
	// 分页拉取的最大返回结果数。默认值:10;最大值:100
	Limit int64 `json:"limit,omitzero"`
	// 分页拉取的起始偏移量,默认值:0
	Offset int64 `json:"offset,omitzero"`
	// 分卷下标,若设置则只返回指定卷的章节列表
	VolumeIndex int64 `json:"volume_index,omitzero"`
}

// PostWxaBookListchapterResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookListchapterResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 章节信息列表
	ChapterList []*PostWxaBookListchapterResponseChapterListObject `json:"chapter_list,omitempty"`
	// 章节总数
	TotalCnt int64 `json:"total_cnt,omitzero"`
}

// PostWxaBookListchapterResponseChapterListObject is a documented nested object.
type PostWxaBookListchapterResponseChapterListObject struct {
	// 章节id
	ChapterID string `json:"chapter_id,omitempty"`
	// 章节标题
	ChapterTitle string `json:"chapter_title,omitempty"`
	// 字数
	WordCnt int64 `json:"word_cnt,omitzero"`
	// 创建时间戳
	CreateTime int64 `json:"create_time,omitzero"`
	// 审核信息
	AuditInfo map[string]any `json:"audit_info,omitempty"`
	// 所属分卷下标,-1 表示不属于任何分卷
	VolumeIndex int64 `json:"volume_index,omitzero"`
	// 提供方章节主键
	OriginalID string `json:"original_id,omitempty"`
	// 章节相对顺序
	Seq int64 `json:"seq,omitzero"`
	// 自定义信息
	CustomInfo string `json:"custom_info,omitempty"`
	// 管控状态,0:正常,1:下架
	BanStatus int64 `json:"ban_status,omitzero"`
}

func (c *Client) PostWxaBookListchapter(ctx context.Context, req *PostWxaBookListchapterRequest) (*PostWxaBookListchapterResponse, error) {
	return core.Call[PostWxaBookListchapterResponse](c.EndpointClient, ctx, "POST", "/wxa/book/listchapter", req, postWxaBookListchapterErrCodes, true, core.SignNone)
}

var postWxaBookQuerybookauthErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookQuerybookauth 查看主授权关系列表-查看被授权关系列表 (POST /wxa/book/querybookauth)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/auth/api_querybookauth.html
// PostWxaBookQuerybookauthRequest carries the documented parameters of one API call.
type PostWxaBookQuerybookauthRequest struct {
	// 填 0 或者不设置: 查授权列表, 填 1: 查被授权列表(查看被授权关系列表时必填)
	Type int64 `json:"type,omitzero"`
	// 结果数据偏移位置 从 0 开始,用于翻页
	Offset int64 `json:"offset"`
	// 获取记录的数量, 上限一次 30 条,用于翻页
	Count int64 `json:"count"`
	// 填 true,返回总数,填 false 不返回(查看被授权关系列表时无需填写)
	IsSum bool `json:"is_sum,omitzero"`
	// 过滤出等于该 book_id 的授权结果(查看被授权关系列表时无需填写)
	BookID string `json:"book_id,omitempty"`
}

// PostWxaBookQuerybookauthResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookQuerybookauthResponse struct {
	// 错误码。
	Errcode int64 `json:"errcode,omitzero"`
	// results
	Results []*PostWxaBookQuerybookauthResponseResultsObject `json:"results,omitempty"`
}

// PostWxaBookQuerybookauthResponseResultsObject is a documented nested object.
type PostWxaBookQuerybookauthResponseResultsObject struct {
	// 作品id
	BookID string `json:"book_id,omitempty"`
	// 主授权账号appid
	GrantorAppID string `json:"grantor_appid,omitempty"`
	// 被授权账号appid
	GranteeAppID string `json:"grantee_appid,omitempty"`
	// 授权到期时间,unix时间戳,单位秒,按CST时区
	ExpireTime int64 `json:"expire_time,omitzero"`
	// 总数,is_sum = true 返回((查看被授权关系列表时不返回)
	Sum int64 `json:"sum,omitzero"`
}

func (c *Client) PostWxaBookQuerybookauth(ctx context.Context, req *PostWxaBookQuerybookauthRequest) (*PostWxaBookQuerybookauthResponse, error) {
	return core.Call[PostWxaBookQuerybookauthResponse](c.EndpointClient, ctx, "POST", "/wxa/book/querybookauth", req, postWxaBookQuerybookauthErrCodes, true, core.SignNone)
}

// PostWxaBookQuerybookauthv2 查看账号主授权关系列表 (POST /wxa/book/querybookauthv2)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/auth/api_querybookauthv2.html
// PostWxaBookQuerybookauthv2Request carries the documented parameters of one API call.
type PostWxaBookQuerybookauthv2Request struct {
	// 填 0 或者不设置: 查授权列表, 填 1: 查被授权列表
	Type int64 `json:"type,omitzero"`
	// 获取记录的数量, 上限一次 100 条,用于分页
	Count int64 `json:"count"`
	// 分页游标。不填或填空字符串,标识从第一页开始查询。后一页查询填充上一页响应的next_cursor字段值
	Cursor string `json:"cursor,omitempty"`
	// 用于查询指定授权方授权给当前账户的小说列表,当查询指定授权方所授权的小说列表时需要传
	GrantorAppID string `json:"grantor_appid,omitempty"`
	// 用于查询指定小说的授权信息,上限一次 30 条。查询指定小说的授权信息场景下需要传递此参数。优先级高于 grantor_appid,当 book_ids 不为空时,grantor_appid 参数无效。
	BookIds []string `json:"book_ids,omitempty"`
}

// PostWxaBookQuerybookauthv2Response mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookQuerybookauthv2Response struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 被授权方列表, 结果按授权过期时间从早到晚排序
	AppIDResults []*PostWxaBookQuerybookauthv2ResponseAppIDResultsObject `json:"appid_results,omitempty"`
	// 下一页游标
	NextCursor string `json:"next_cursor,omitempty"`
}

// PostWxaBookQuerybookauthv2ResponseAppIDResultsObject is a documented nested object.
type PostWxaBookQuerybookauthv2ResponseAppIDResultsObject struct {
	// 主授权账号appid
	GrantorAppID string `json:"grantor_appid,omitempty"`
	// 被授权账号appid
	GranteeAppID string `json:"grantee_appid,omitempty"`
	// 授权到期时间,unix时间戳,单位秒,按CST时区
	ExpireTime int64 `json:"expire_time,omitzero"`
	// 作品id,查询指定授权方授权给当前账户的小说列表时会返回
	BookID string `json:"book_id,omitempty"`
}

func (c *Client) PostWxaBookQuerybookauthv2(ctx context.Context, req *PostWxaBookQuerybookauthv2Request) (*PostWxaBookQuerybookauthv2Response, error) {
	return core.Call[PostWxaBookQuerybookauthv2Response](c.EndpointClient, ctx, "POST", "/wxa/book/querybookauthv2", req, nil, true, core.SignNone)
}

var postWxaBookReorderchapterErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookReorderchapter 调整章节顺序 (POST /wxa/book/reorderchapter)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_reorderchapter.html
// PostWxaBookReorderchapterRequest carries the documented parameters of one API call.
type PostWxaBookReorderchapterRequest struct {
	// 作品id
	BookID string `json:"book_id"`
	// 章节id
	ChapterID string `json:"chapter_id"`
	// 目标章节id
	TargetChapterID string `json:"target_chapter_id"`
	// 排序操作,1:交换,2:插入到目标章节之前,3:插入到目标章节之后
	Operation int64 `json:"operation"`
}

// PostWxaBookReorderchapterResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookReorderchapterResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaBookReorderchapter(ctx context.Context, req *PostWxaBookReorderchapterRequest) (*PostWxaBookReorderchapterResponse, error) {
	return core.Call[PostWxaBookReorderchapterResponse](c.EndpointClient, ctx, "POST", "/wxa/book/reorderchapter", req, postWxaBookReorderchapterErrCodes, true, core.SignNone)
}

var postWxaBookReplacechapterErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookReplacechapter 替换章节 (POST /wxa/book/replacechapter)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_replacechapter.html
// PostWxaBookReplacechapterRequest carries the documented parameters of one API call.
type PostWxaBookReplacechapterRequest struct {
	// 作品id
	BookID string `json:"book_id"`
	// 章节id
	ChapterID string `json:"chapter_id"`
	// 新章节标题。长度限制 1-80 字。
	NewChapterTitle string `json:"new_chapter_title"`
	// 新章节内容。长度限制 1-20000 字。
	NewContent string `json:"new_content"`
}

// PostWxaBookReplacechapterResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookReplacechapterResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 替换后新章节id
	NewChapterID string `json:"new_chapter_id,omitempty"`
}

func (c *Client) PostWxaBookReplacechapter(ctx context.Context, req *PostWxaBookReplacechapterRequest) (*PostWxaBookReplacechapterResponse, error) {
	return core.Call[PostWxaBookReplacechapterResponse](c.EndpointClient, ctx, "POST", "/wxa/book/replacechapter", req, postWxaBookReplacechapterErrCodes, true, core.SignNone)
}

var postWxaBookUpdatebookErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookUpdatebook 编辑作品 (POST /wxa/book/updatebook)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_updatebook.html
// PostWxaBookUpdatebookRequest carries the documented parameters of one API call.
type PostWxaBookUpdatebookRequest struct {
	// 作品id
	BookID string `json:"book_id"`
	// 作品名。长度限制1-30字。
	Title string `json:"title,omitempty"`
	// 作品简介。长度限制1-500字。
	Intro string `json:"intro,omitempty"`
	// 封面图 media_id,通过 新增临时素材上传得到。
	CoverMediaID string `json:"cover_media_id,omitempty"`
	// 作者名。长度限制1-100字。
	Author string `json:"author,omitempty"`
	// 一级类型id。可选类型见 小说作品类型
	FirstCategoryID int64 `json:"first_category_id,omitzero"`
	// 二级类型id
	SecondCategoryID int64 `json:"second_category_id,omitzero"`
	// 三级类型id
	ThirdCategoryID int64 `json:"third_category_id,omitzero"`
	// 完结状态,1:连载中,2:已完结
	CompleteStatus int64 `json:"complete_status,omitzero"`
	// 按照预期顺序传入章节id
	ChapterIDList []string `json:"chapter_id_list,omitempty"`
	// 是否需要分卷
	NeedVolume bool `json:"need_volume,omitzero"`
	// 分卷信息
	VolumeList []*PostWxaBookUpdatebookRequestVolumeListObject `json:"volume_list,omitempty"`
	// 章节排序方式,0:追加,1:seq 递增
	ChapterOrderMethod int64 `json:"chapter_order_method,omitzero"`
	// 自定义信息。长度限制0-128字节。
	CustomInfo string `json:"custom_info,omitempty"`
	// 是否更新题材关键词
	UpdateKeyword bool `json:"update_keyword,omitzero"`
	// 题材关键词。最多传入3个关键词,每个关键词长度限制1-4字。
	KeywordList []string `json:"keyword_list,omitempty"`
	// 精彩片段。需为本书内容,长度限制400-1000字。
	AwesomeParagraph string `json:"awesome_paragraph,omitempty"`
}

// PostWxaBookUpdatebookRequestVolumeListObject is a documented nested object.
type PostWxaBookUpdatebookRequestVolumeListObject struct {
	// 分卷名。长度限制1-100字。
	VolumeTitle string `json:"volume_title"`
	// 分卷起始章节下标,取值范围 [0, 章节总数)
	StartIndex int64 `json:"start_index"`
	// 分卷截止章节下标,取值范围 [起始章节下标, 章节总数)
	EndIndex int64 `json:"end_index"`
}

// PostWxaBookUpdatebookResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookUpdatebookResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaBookUpdatebook(ctx context.Context, req *PostWxaBookUpdatebookRequest) (*PostWxaBookUpdatebookResponse, error) {
	return core.Call[PostWxaBookUpdatebookResponse](c.EndpointClient, ctx, "POST", "/wxa/book/updatebook", req, postWxaBookUpdatebookErrCodes, true, core.SignNone)
}

var postWxaBookUpdatechapterseqErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBookUpdatechapterseq 调整章节相对顺序 (POST /wxa/book/updatechapterseq)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/business/api_updatechapterseq.html
// PostWxaBookUpdatechapterseqRequest carries the documented parameters of one API call.
type PostWxaBookUpdatechapterseqRequest struct {
	// 作品id
	BookID string `json:"book_id"`
	// 章节 seq 列表
	ChapterSeqList []*PostWxaBookUpdatechapterseqRequestChapterSeqListObject `json:"chapter_seq_list"`
}

// PostWxaBookUpdatechapterseqRequestChapterSeqListObject is a documented nested object.
type PostWxaBookUpdatechapterseqRequestChapterSeqListObject struct {
	// 章节id
	ChapterID string `json:"chapter_id"`
	// 章节相对顺序,可非连续递增
	Seq int64 `json:"seq"`
}

// PostWxaBookUpdatechapterseqResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBookUpdatechapterseqResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaBookUpdatechapterseq(ctx context.Context, req *PostWxaBookUpdatechapterseqRequest) (*PostWxaBookUpdatechapterseqResponse, error) {
	return core.Call[PostWxaBookUpdatechapterseqResponse](c.EndpointClient, ctx, "POST", "/wxa/book/updatechapterseq", req, postWxaBookUpdatechapterseqErrCodes, true, core.SignNone)
}

var postWxaBusinessNovelreaderGetpreviewsettingErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBusinessNovelreaderGetpreviewsetting 预览设置获取 (POST /wxa/business/novelreader/getpreviewsetting)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/preview/api_getpreviewsetting.html
// PostWxaBusinessNovelreaderGetpreviewsettingRequest carries the documented parameters of one API call.
type PostWxaBusinessNovelreaderGetpreviewsettingRequest struct {
	// 作品id
	BookID string `json:"book_id"`
}

// PostWxaBusinessNovelreaderGetpreviewsettingResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBusinessNovelreaderGetpreviewsettingResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// setting
	Setting *PostWxaBusinessNovelreaderGetpreviewsettingResponseSettingObject `json:"setting,omitempty"`
}

// PostWxaBusinessNovelreaderGetpreviewsettingResponseSettingObject is a documented nested object.
type PostWxaBusinessNovelreaderGetpreviewsettingResponseSettingObject struct {
	// 作品id
	BookID string `json:"book_id,omitempty"`
	// 默认预览字数
	DefaultWords int64 `json:"default_words,omitzero"`
	// chapter_setting
	ChapterSetting []*PostWxaBusinessNovelreaderGetpreviewsettingResponseChapterSettingObject `json:"chapter_setting,omitempty"`
}

// PostWxaBusinessNovelreaderGetpreviewsettingResponseChapterSettingObject is a documented nested object.
type PostWxaBusinessNovelreaderGetpreviewsettingResponseChapterSettingObject struct {
	// 章节索引,从 0 开始,未设置的章节将使用 default_words 作为预览字数
	ChapterIndex int64 `json:"chapter_index,omitzero"`
	// 章节字数
	Words int64 `json:"words,omitzero"`
}

func (c *Client) PostWxaBusinessNovelreaderGetpreviewsetting(ctx context.Context, req *PostWxaBusinessNovelreaderGetpreviewsettingRequest) (*PostWxaBusinessNovelreaderGetpreviewsettingResponse, error) {
	return core.Call[PostWxaBusinessNovelreaderGetpreviewsettingResponse](c.EndpointClient, ctx, "POST", "/wxa/business/novelreader/getpreviewsetting", req, postWxaBusinessNovelreaderGetpreviewsettingErrCodes, true, core.SignNone)
}

var postWxaBusinessNovelreaderSetpreviewsettingErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBusinessNovelreaderSetpreviewsetting 预览设置修改 (POST /wxa/business/novelreader/setpreviewsetting)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/preview/api_setpreviewsetting.html
// PostWxaBusinessNovelreaderSetpreviewsettingRequest carries the documented parameters of one API call.
type PostWxaBusinessNovelreaderSetpreviewsettingRequest struct {
	// 作品id
	BookID string `json:"book_id"`
	// 默认预览字数
	DefaultWords int64 `json:"default_words"`
	// 章节索引,从 0 开始,未设置的章节将使用 default_words 作为预览字数
	ChapterIndex int64 `json:"chapter_index,omitzero"`
	// 章节字数
	Words int64 `json:"words,omitzero"`
}

// PostWxaBusinessNovelreaderSetpreviewsettingResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBusinessNovelreaderSetpreviewsettingResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
}

func (c *Client) PostWxaBusinessNovelreaderSetpreviewsetting(ctx context.Context, req *PostWxaBusinessNovelreaderSetpreviewsettingRequest) (*PostWxaBusinessNovelreaderSetpreviewsettingResponse, error) {
	return core.Call[PostWxaBusinessNovelreaderSetpreviewsettingResponse](c.EndpointClient, ctx, "POST", "/wxa/business/novelreader/setpreviewsetting", req, postWxaBusinessNovelreaderSetpreviewsettingErrCodes, true, core.SignNone)
}

var postWxaBusinessNovelreaderSetrecmdnovelErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统失败",
		Solution: "",
	},
	0: {
		Desc:     "成功",
		Solution: "",
	},
	10140001: {
		Desc:     "无效参数",
		Solution: "",
	},
	10140002: {
		Desc:     "请使用 utf-8 编码",
		Solution: "",
	},
	10140003: {
		Desc:     "无效的作品名",
		Solution: "",
	},
	10140004: {
		Desc:     "无效的作品简介",
		Solution: "",
	},
	10140005: {
		Desc:     "无效的封面图",
		Solution: "",
	},
	10140006: {
		Desc:     "无效的作者",
		Solution: "",
	},
	10140007: {
		Desc:     "无效的作品类型",
		Solution: "",
	},
	10140008: {
		Desc:     "无效的完结状态",
		Solution: "",
	},
	10140009: {
		Desc:     "无效的上传场景",
		Solution: "",
	},
	10140010: {
		Desc:     "无效的章节下标列表,请检查是否有重复或未覆盖所有章节",
		Solution: "",
	},
	10140011: {
		Desc:     "无效的章节ID列表,请检查是否有重复、不属于该作品的章节ID或未覆盖所有章节",
		Solution: "",
	},
	10140012: {
		Desc:     "无效的分卷列表,请检查分卷标题是否规范,区间是否存在交集或未覆盖所有章节",
		Solution: "",
	},
	10140013: {
		Desc:     "缺少章节信息",
		Solution: "",
	},
	10140014: {
		Desc:     "章节信息过多",
		Solution: "",
	},
	10140015: {
		Desc:     "缺少作品ID",
		Solution: "",
	},
	10140016: {
		Desc:     "作品ID过多",
		Solution: "",
	},
	10140017: {
		Desc:     "无效的分页最大结果数",
		Solution: "",
	},
	10140018: {
		Desc:     "无效的章节标题",
		Solution: "",
	},
	10140019: {
		Desc:     "无效的章节内容",
		Solution: "",
	},
	10140020: {
		Desc:     "无效的排序操作",
		Solution: "",
	},
	10140021: {
		Desc:     "无效的章节排序方式",
		Solution: "",
	},
	10140022: {
		Desc:     "缺少章节seq",
		Solution: "",
	},
	10140023: {
		Desc:     "请求参数中存在重复的提供方主键",
		Solution: "",
	},
	10140024: {
		Desc:     "无效的提供方主键",
		Solution: "",
	},
	10140025: {
		Desc:     "无效的优先级",
		Solution: "",
	},
	10140026: {
		Desc:     "无效的自定义信息",
		Solution: "",
	},
	10141001: {
		Desc:     "找不到对应信息",
		Solution: "",
	},
	10141002: {
		Desc:     "不允许操作",
		Solution: "",
	},
	10141003: {
		Desc:     "作品正在审核中",
		Solution: "",
	},
	10141004: {
		Desc:     "添加审核信息失败",
		Solution: "",
	},
	10141005: {
		Desc:     "太多检查不通过项",
		Solution: "",
	},
	10141006: {
		Desc:     "作品未审核通过,无法发布",
		Solution: "",
	},
	10141007: {
		Desc:     "作品缺少章节",
		Solution: "",
	},
	10141008: {
		Desc:     "作品分卷信息需要更新",
		Solution: "",
	},
	10141009: {
		Desc:     "提供方主键冲突",
		Solution: "",
	},
	10141010: {
		Desc:     "该接口与当前作品的章节排序方式不兼容,如需调用请先修改章节排序方式",
		Solution: "",
	},
	10145001: {
		Desc:     "操作结果为空",
		Solution: "",
	},
	10145002: {
		Desc:     "调用系统失败",
		Solution: "",
	},
	10145003: {
		Desc:     "缺少入参",
		Solution: "",
	},
	10145004: {
		Desc:     "授权作品ID无效",
		Solution: "",
	},
	10145005: {
		Desc:     "授权者不是小说类目",
		Solution: "",
	},
	10145006: {
		Desc:     "被授权者不是小说类目",
		Solution: "",
	},
	10145007: {
		Desc:     "过期的时间信息/或者授权的时间异常",
		Solution: "",
	},
	10145008: {
		Desc:     "一次提交授权的作品太多或者太少(count = 0 or count > 20)",
		Solution: "",
	},
	10145009: {
		Desc:     "一次查询授权列表拉取的count太多(count > 100)",
		Solution: "",
	},
	10145010: {
		Desc:     "添加的授权记录有部分失败",
		Solution: "",
	},
	10145011: {
		Desc:     "appid无效",
		Solution: "",
	},
	10145012: {
		Desc:     "授权者和被授权者不能相同",
		Solution: "",
	},
}

// PostWxaBusinessNovelreaderSetrecmdnovel 读后推荐 (POST /wxa/business/novelreader/setrecmdnovel)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/novel/other/api_novelreadersetrecmdnovel.html
// PostWxaBusinessNovelreaderSetrecmdnovelRequest carries the documented parameters of one API call.
type PostWxaBusinessNovelreaderSetrecmdnovelRequest struct {
	// 推荐小说的类型:1-android(付费小说) 2-ios(全文免费小说)
	RecmdType int64 `json:"recmd_type"`
	// 推荐小说的 book_id 数组
	BookIDList []string `json:"book_id_list"`
}

// PostWxaBusinessNovelreaderSetrecmdnovelResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBusinessNovelreaderSetrecmdnovelResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaBusinessNovelreaderSetrecmdnovel(ctx context.Context, req *PostWxaBusinessNovelreaderSetrecmdnovelRequest) (*PostWxaBusinessNovelreaderSetrecmdnovelResponse, error) {
	return core.Call[PostWxaBusinessNovelreaderSetrecmdnovelResponse](c.EndpointClient, ctx, "POST", "/wxa/business/novelreader/setrecmdnovel", req, postWxaBusinessNovelreaderSetrecmdnovelErrCodes, true, core.SignNone)
}
