// Code generated by docsync from the official WeChat documentation. DO NOT EDIT.
// The API surface (names, request/response shapes) is derived deterministically
// from the endpoints; regenerate with "make docs-sync". If this file changes
// under you, the upstream documentation changed.

package miniprogram

import (
	"context"
	"github.com/go-sphere/weixin-api/core"
)

var postWxaSecFamousbrandApplyErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统错误",
		Solution: "",
	},
	10210001: {
		Desc:     "参数错误",
		Solution: "",
	},
	10210002: {
		Desc:     "状态错误",
		Solution: "",
	},
	10210003: {
		Desc:     "图片解析失败",
		Solution: "",
	},
	43002: {
		Desc:     "HTTP请求必须使用POST方法",
		Solution: "",
	},
	44002: {
		Desc:     "POST内容为空",
		Solution: "",
	},
	47001: {
		Desc:     "输入格式错误",
		Solution: "",
	},
}

// PostWxaSecFamousbrandApply 品牌申请 (POST /wxa/sec/famousbrand/apply)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/order_shipping/api_famousbrandapply.html
// PostWxaSecFamousbrandApplyRequest carries the documented parameters of one API call.
type PostWxaSecFamousbrandApplyRequest struct {
	// 申请品牌信息
	Application *PostWxaSecFamousbrandApplyRequestApplicationObject `json:"Application"`
}

// PostWxaSecFamousbrandApplyRequestApplicationObject is a documented nested object.
type PostWxaSecFamousbrandApplyRequestApplicationObject struct {
	// 品牌申请类型枚举值
	ApplyFor int64 `json:"apply_for"`
	// 申请品牌信息,当申请类型为知名品牌时必填
	AuditInfo *PostWxaSecFamousbrandApplyRequestAuditInfoObject `json:"audit_info,omitempty"`
}

// PostWxaSecFamousbrandApplyRequestAuditInfoObject is a documented nested object.
type PostWxaSecFamousbrandApplyRequestAuditInfoObject struct {
	// 品牌名称
	BrandName string `json:"brand_name"`
	// 品牌类型
	BrandType int64 `json:"brand_type"`
	// 当品牌类型是电商平台旗舰店为必填,表示该品牌是哪个电商平台的旗舰店
	FlagshipInWhichEcPlatform string `json:"flagship_in_which_ec_platform,omitempty"`
	// 当品牌类型是电商平台旗舰店为必填,表示该品牌为官方旗舰店的佐证材料,使用 新增临时素材 上传图片
	EcPlatformProofList []string `json:"ec_platform_proof_list,omitempty"`
	// 其他补充说明材料,使用 新增临时素材 上传图片
	OtherMaterialList []string `json:"other_material_list,omitempty"`
	// 当品牌类型是有关部门认定的驰名商标时为必填,表示该品牌是有关部门认定的驰名商标、著名商标的佐证材料,使用 新增临时素材 上传图片
	AuthorityCertifiedProofList []string `json:"authority_certified_proof_list,omitempty"`
}

// PostWxaSecFamousbrandApplyResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaSecFamousbrandApplyResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误原因
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaSecFamousbrandApply(ctx context.Context, req *PostWxaSecFamousbrandApplyRequest) (*PostWxaSecFamousbrandApplyResponse, error) {
	return core.Call[PostWxaSecFamousbrandApplyResponse](c.EndpointClient, ctx, "POST", "/wxa/sec/famousbrand/apply", req, postWxaSecFamousbrandApplyErrCodes, true, core.SignNone)
}

var postWxaSecFamousbrandGetStatusErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "系统错误",
		Solution: "",
	},
	10210001: {
		Desc:     "参数错误",
		Solution: "",
	},
	10210002: {
		Desc:     "状态错误",
		Solution: "",
	},
	10210003: {
		Desc:     "图片解析失败",
		Solution: "",
	},
	41001: {
		Desc:     "access_token missing",
		Solution: "",
	},
	42001: {
		Desc:     "access_token expired",
		Solution: "",
	},
	43002: {
		Desc:     "HTTP请求必须使用POST方法",
		Solution: "",
	},
	44002: {
		Desc:     "POST内容为空",
		Solution: "",
	},
	47001: {
		Desc:     "输入格式错误",
		Solution: "",
	},
	61004: {
		Desc:     "access clientip is not registered, not in ip-white-list",
		Solution: "",
	},
}

// PostWxaSecFamousbrandGetStatus 小程序品牌申请状态查询 (POST /wxa/sec/famousbrand/get_status)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/order_shipping/api_getfamousbrandapplystatus.html
// PostWxaSecFamousbrandGetStatusRequest carries the documented parameters of one API call.
type PostWxaSecFamousbrandGetStatusRequest struct{}

// PostWxaSecFamousbrandGetStatusResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaSecFamousbrandGetStatusResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误原因
	Errmsg string `json:"errmsg,omitempty"`
	// 品牌申请进度
	Progress *PostWxaSecFamousbrandGetStatusResponseProgressObject `json:"progress,omitempty"`
	// 申请品牌信息
	Application *PostWxaSecFamousbrandGetStatusResponseApplicationObject `json:"application,omitempty"`
}

// PostWxaSecFamousbrandGetStatusResponseProgressObject is a documented nested object.
type PostWxaSecFamousbrandGetStatusResponseProgressObject struct {
	// 品牌申请状态
	Status int64 `json:"status,omitzero"`
}

// PostWxaSecFamousbrandGetStatusResponseApplicationObject is a documented nested object.
type PostWxaSecFamousbrandGetStatusResponseApplicationObject struct {
	// 申请类型
	ApplyFor int64 `json:"apply_for,omitzero"`
	// 申请品牌信息
	AuditInfo *PostWxaSecFamousbrandGetStatusResponseAuditInfoObject `json:"audit_info,omitempty"`
	// 品牌申请状态
	Status int64 `json:"status,omitzero"`
}

// PostWxaSecFamousbrandGetStatusResponseAuditInfoObject is a documented nested object.
type PostWxaSecFamousbrandGetStatusResponseAuditInfoObject struct {
	// 审核原因,只有在审核驳回时才有值
	AuditReason string `json:"audit_reason,omitempty"`
}

func (c *Client) PostWxaSecFamousbrandGetStatus(ctx context.Context, req *PostWxaSecFamousbrandGetStatusRequest) (*PostWxaSecFamousbrandGetStatusResponse, error) {
	return core.Call[PostWxaSecFamousbrandGetStatusResponse](c.EndpointClient, ctx, "POST", "/wxa/sec/famousbrand/get_status", req, postWxaSecFamousbrandGetStatusErrCodes, true, core.SignNone)
}

var postWxaSecOrderGetOrderErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060001: {
		Desc:     "支付单不存在。请检查微信支付单号形式下 transaction_id 字段或商户侧单号形式下 mchid、out_trade_no 字段是否有误",
		Solution: "",
	},
	10060002: {
		Desc:     "支付单已完成发货,无法继续发货。请检查支付单发货情况",
		Solution: "",
	},
	10060003: {
		Desc:     "支付单已使用重新发货机会。支付单处于已发货状态时调用该API视为重新发货,仅可重新发货一次,请检查支付单发货情况",
		Solution: "",
	},
	10060004: {
		Desc:     "支付单处于不可发货的状态。请检查支付单状态",
		Solution: "",
	},
	10060005: {
		Desc:     "物流类型有误。按照文档中物流类型枚举填写该字段",
		Solution: "",
	},
	10060006: {
		Desc:     "非快递发货时不允许分拆发货。非快递发货时不允许分拆发货,请检查请求参数",
		Solution: "",
	},
	10060007: {
		Desc:     "分拆发货模式下必须填写 is_all_delivered 字段。请检查请求参数中的 is_all_delivered 字段",
		Solution: "",
	},
	10060008: {
		Desc:     "商品描述 item_desc 字段不能为空。用于发货信息录入场景时商品描述字段不能为空",
		Solution: "",
	},
	10060009: {
		Desc:     "商品描述 item_desc 字段太长。请检查商品描述字段",
		Solution: "",
	},
	10060012: {
		Desc:     "系统错误。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060014: {
		Desc:     "参数错误。根据错误原因描述修改参数",
		Solution: "",
	},
	10060019: {
		Desc:     "系统错误。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060020: {
		Desc:     "该笔支付单在没有任何商品描述的情况下不允许完成发货。请补充商品描述 item_desc",
		Solution: "",
	},
	10060023: {
		Desc:     "发货信息未更新。支付单信息不变",
		Solution: "",
	},
	10060024: {
		Desc:     "物流信息列表太长。支付单物流信息列表长度不可大于 15",
		Solution: "",
	},
	10060025: {
		Desc:     "物流公司编码太长。请检查物流公司编码是否有误",
		Solution: "",
	},
	10060026: {
		Desc:     "物流单号太长.。请检查物流单号是否有误",
		Solution: "",
	},
	10060031: {
		Desc:     "该笔支付单不属于 openid 所指定的用户。请检查支付单号或 openid 是否有误",
		Solution: "",
	},
	268485194: {
		Desc:     "订单单号类型非法。按照文档中订单单号类型枚举填写该字段",
		Solution: "",
	},
	268485195: {
		Desc:     "微信支付单号形式下 transaction_id 字段不能为空。微信支付单号形式下 transaction_id 字段必须设置",
		Solution: "",
	},
	268485196: {
		Desc:     "商户侧单号形式下 mchid 字段不能为空。商户侧单号形式下 mchid 字段必须设置",
		Solution: "",
	},
	268485197: {
		Desc:     "商户侧单号形式下 out_trade_no 字段不能为空。商户侧单号形式下 out_trade_no 字段必须设置",
		Solution: "",
	},
	268485216: {
		Desc:     "上传时间非法,请按照 RFC 3339 格式填写。上传时间必须满足 RFC 3339 格式,如 2022-12-15T13:29:35.120+08:00",
		Solution: "",
	},
	268485224: {
		Desc:     "发货模式非法。按照文档中发货模式枚举设置该字段",
		Solution: "",
	},
	268485226: {
		Desc:     "物流单号不能为空。物流快递发货时物流单号必须填写",
		Solution: "",
	},
	268485227: {
		Desc:     "物流公司编码不能为空。物流快递发货时物流公司编码必须填写",
		Solution: "",
	},
	268485228: {
		Desc:     "统一发货模式下,物流信息列表长度必须为 1。统一发货模式下,物流信息列表长度必须为 1",
		Solution: "",
	},
}

// PostWxaSecOrderGetOrder 查询订单发货状态 (POST /wxa/sec/order/get_order)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/order_shipping/api_getorder.html
// PostWxaSecOrderGetOrderRequest carries the documented parameters of one API call.
type PostWxaSecOrderGetOrderRequest struct {
	// 原支付交易对应的微信订单号。
	TransactionID string `json:"transaction_id,omitempty"`
	// 支付下单商户的商户号,由微信支付生成并下发。
	MerchantID string `json:"merchant_id,omitempty"`
	// 二级商户号。
	SubMerchantID string `json:"sub_merchant_id,omitempty"`
	// 商户系统内部订单号,只能是数字、大小写字母`_-*`且在同一个商户号下唯一。
	MerchantTradeNo string `json:"merchant_trade_no,omitempty"`
}

// PostWxaSecOrderGetOrderResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaSecOrderGetOrderResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 支付单信息。
	Order *PostWxaSecOrderGetOrderResponseOrderObject `json:"order,omitempty"`
}

// PostWxaSecOrderGetOrderResponseOrderObject is a documented nested object.
type PostWxaSecOrderGetOrderResponseOrderObject struct {
	// 原支付交易对应的微信订单号。
	TransactionID string `json:"transaction_id,omitempty"`
	// 支付下单商户的商户号,由微信支付生成并下发。
	MerchantID string `json:"merchant_id,omitempty"`
	// 二级商户号。
	SubMerchantID string `json:"sub_merchant_id,omitempty"`
	// 商户系统内部订单号,只能是数字、大小写字母`_-*`且在同一个商户号下唯一。
	MerchantTradeNo string `json:"merchant_trade_no,omitempty"`
	// 以分号连接的该支付单的所有商品描述,当超过120字时自动截断并以 "..." 结尾。
	Description string `json:"description,omitempty"`
	// 支付单实际支付金额,整型,单位:分钱。
	PaidAmount int64 `json:"paid_amount,omitzero"`
	// 支付者openid。
	OpenID string `json:"openid,omitempty"`
	// 交易创建时间,时间戳形式。
	TradeCreateTime int64 `json:"trade_create_time,omitzero"`
	// 支付时间,时间戳形式。
	PayTime int64 `json:"pay_time,omitzero"`
	// 订单状态枚举:(1) 待发货;(2) 已发货;(3) 确认收货;(4) 交易完成;(5) 已退款;(6) 资金待结算。
	OrderState int64 `json:"order_state,omitzero"`
	// 是否处在交易纠纷中。
	InComplaint bool `json:"in_complaint,omitzero"`
	// 发货信息。
	Shipping *PostWxaSecOrderGetOrderResponseShippingObject `json:"shipping,omitempty"`
}

// PostWxaSecOrderGetOrderResponseShippingObject is a documented nested object.
type PostWxaSecOrderGetOrderResponseShippingObject struct {
	// 发货模式,发货模式枚举值:1、UNIFIED_DELIVERY(统一发货)2、SPLIT_DELIVERY(分拆发货) 示例值: UNIFIED_DELIVERY
	DeliveryMode int64 `json:"delivery_mode,omitzero"`
	// 物流模式,发货方式枚举值:1、实体物流配送采用快递公司进行实体物流配送形式 2、同城配送 3、虚拟商品,虚拟商品,例如话费充值,点卡等,无实体配送形式 4、用户自提
	LogisticsType int64 `json:"logistics_type,omitzero"`
	// 是否已完成全部发货。
	FinishShipping bool `json:"finish_shipping,omitzero"`
	// 在小程序后台发货信息录入页录入的商品描述。
	GoodsDesc string `json:"goods_desc,omitempty"`
	// 已完成全部发货的次数,未完成时为 0,完成时为 1,重新发货并完成后为 2。
	FinishShippingCount int64 `json:"finish_shipping_count,omitzero"`
	// 物流信息列表,发货物流单列表,支持统一发货(单个物流单)和分拆发货(多个物流单)两种模式。
	ShippingList []*PostWxaSecOrderGetOrderResponseShippingListObject `json:"shipping_list,omitempty"`
}

// PostWxaSecOrderGetOrderResponseShippingListObject is a documented nested object.
type PostWxaSecOrderGetOrderResponseShippingListObject struct {
	// 物流单号,示例值: "323244567777"。
	TrackingNo string `json:"tracking_no,omitempty"`
	// 同城配送公司名或物流公司编码,快递公司ID,参见「获取运力 id 列表get_delivery_list」 示例值: "DHL"。
	ExpressCompany string `json:"express_company,omitempty"`
	// 使用上传物流信息 API 录入的该物流信息的商品描述。
	GoodsDesc string `json:"goods_desc,omitempty"`
	// 该物流信息的上传时间,时间戳形式。
	UploadTime int64 `json:"upload_time,omitzero"`
	// 联系方式。
	Contact map[string]any `json:"contact,omitempty"`
}

func (c *Client) PostWxaSecOrderGetOrder(ctx context.Context, req *PostWxaSecOrderGetOrderRequest) (*PostWxaSecOrderGetOrderResponse, error) {
	return core.Call[PostWxaSecOrderGetOrderResponse](c.EndpointClient, ctx, "POST", "/wxa/sec/order/get_order", req, postWxaSecOrderGetOrderErrCodes, true, core.SignNone)
}

var postWxaSecOrderGetOrderListErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060001: {
		Desc:     "支付单不存在。请检查微信支付单号形式下 transaction_id 字段或商户侧单号形式下 mchid、out_trade_no 字段是否有误",
		Solution: "",
	},
	10060002: {
		Desc:     "支付单已完成发货,无法继续发货。请检查支付单发货情况",
		Solution: "",
	},
	10060003: {
		Desc:     "支付单已使用重新发货机会。支付单处于已发货状态时调用该API视为重新发货,仅可重新发货一次,请检查支付单发货情况",
		Solution: "",
	},
	10060004: {
		Desc:     "支付单处于不可发货的状态。请检查支付单状态",
		Solution: "",
	},
	10060005: {
		Desc:     "物流类型有误。按照文档中物流类型枚举填写该字段",
		Solution: "",
	},
	10060006: {
		Desc:     "非快递发货时不允许分拆发货。非快递发货时不允许分拆发货,请检查请求参数",
		Solution: "",
	},
	10060007: {
		Desc:     "分拆发货模式下必须填写 is_all_delivered 字段。请检查请求参数中的 is_all_delivered 字段",
		Solution: "",
	},
	10060008: {
		Desc:     "商品描述 item_desc 字段不能为空。用于发货信息录入场景时商品描述字段不能为空",
		Solution: "",
	},
	10060009: {
		Desc:     "商品描述 item_desc 字段太长。请检查商品描述字段",
		Solution: "",
	},
	10060011: {
		Desc:     "last_index不合法。请检查last_index字段是否有误。",
		Solution: "",
	},
	10060012: {
		Desc:     "系统错误。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060014: {
		Desc:     "参数错误。根据错误原因描述修改参数",
		Solution: "",
	},
	10060019: {
		Desc:     "系统错误。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060020: {
		Desc:     "该笔支付单在没有任何商品描述的情况下不允许完成发货。请补充商品描述 item_desc",
		Solution: "",
	},
	10060023: {
		Desc:     "发货信息未更新。支付单信息不变",
		Solution: "",
	},
	10060024: {
		Desc:     "物流信息列表太长。支付单物流信息列表长度不可大于 15",
		Solution: "",
	},
	10060025: {
		Desc:     "物流公司编码太长。请检查物流公司编码是否有误",
		Solution: "",
	},
	10060026: {
		Desc:     "物流单号太长.。请检查物流单号是否有误",
		Solution: "",
	},
	10060031: {
		Desc:     "该笔支付单不属于 openid 所指定的用户。请检查支付单号或 openid 是否有误",
		Solution: "",
	},
	268485194: {
		Desc:     "订单单号类型非法。按照文档中订单单号类型枚举填写该字段",
		Solution: "",
	},
	268485195: {
		Desc:     "微信支付单号形式下 transaction_id 字段不能为空。微信支付单号形式下 transaction_id 字段必须设置",
		Solution: "",
	},
	268485196: {
		Desc:     "商户侧单号形式下 mchid 字段不能为空。商户侧单号形式下 mchid 字段必须设置",
		Solution: "",
	},
	268485197: {
		Desc:     "商户侧单号形式下 out_trade_no 字段不能为空。商户侧单号形式下 out_trade_no 字段必须设置",
		Solution: "",
	},
	268485216: {
		Desc:     "上传时间非法,请按照 RFC 3339 格式填写。上传时间必须满足 RFC 3339 格式,如 2022-12-15T13:29:35.120+08:00",
		Solution: "",
	},
	268485224: {
		Desc:     "发货模式非法。按照文档中发货模式枚举设置该字段",
		Solution: "",
	},
	268485226: {
		Desc:     "物流单号不能为空。物流快递发货时物流单号必须填写",
		Solution: "",
	},
	268485227: {
		Desc:     "物流公司编码不能为空。物流快递发货时物流公司编码必须填写",
		Solution: "",
	},
	268485228: {
		Desc:     "统一发货模式下,物流信息列表长度必须为 1。统一发货模式下,物流信息列表长度必须为 1",
		Solution: "",
	},
}

// PostWxaSecOrderGetOrderList 查询订单列表 (POST /wxa/sec/order/get_order_list)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/order_shipping/api_getorderlist.html
// PostWxaSecOrderGetOrderListRequest carries the documented parameters of one API call.
type PostWxaSecOrderGetOrderListRequest struct {
	// 支付时间所属范围。
	PayTimeRange *PostWxaSecOrderGetOrderListRequestPayTimeRangeObject `json:"pay_time_range,omitempty"`
	// 订单状态枚举:(1) 待发货;(2) 已发货;(3) 确认收货;(4) 交易完成;(5) 已退款;(6) 资金待结算。
	OrderState int64 `json:"order_state,omitzero"`
	// 支付者openid。
	OpenID string `json:"openid,omitempty"`
	// 翻页时使用,获取第一页时不用传入,如果查询结果中 has_more 字段为 true,则传入该次查询结果中返回的 last_index 字段可获取下一页。
	LastIndex string `json:"last_index,omitempty"`
	// 翻页时使用,返回列表的长度,默认为100。 返回参数
	PageSize int64 `json:"page_size,omitzero"`
}

// PostWxaSecOrderGetOrderListRequestPayTimeRangeObject is a documented nested object.
type PostWxaSecOrderGetOrderListRequestPayTimeRangeObject struct {
	// 起始时间,时间戳形式,不填则视为从0开始。
	BeginTime int64 `json:"begin_time,omitzero"`
}

// PostWxaSecOrderGetOrderListResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaSecOrderGetOrderListResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 翻页时使用。
	LastIndex string `json:"last_index,omitempty"`
	// 是否还有更多支付单。
	HasMore bool `json:"has_more,omitzero"`
	// 支付单信息列表。
	OrderList *PostWxaSecOrderGetOrderListResponseOrderListObject `json:"order_list,omitempty"`
}

// PostWxaSecOrderGetOrderListResponseOrderListObject is a documented nested object.
type PostWxaSecOrderGetOrderListResponseOrderListObject struct {
	// 原支付交易对应的微信订单号。
	TransactionID string `json:"transaction_id,omitempty"`
	// 支付下单商户的商户号,由微信支付生成并下发。
	MerchantID string `json:"merchant_id,omitempty"`
	// 二级商户号。
	SubMerchantID string `json:"sub_merchant_id,omitempty"`
	// 商户系统内部订单号,只能是数字、大小写字母`_-*`且在同一个商户号下唯一。
	MerchantTradeNo string `json:"merchant_trade_no,omitempty"`
	// 以分号连接的该支付单的所有商品描述,当超过120字时自动截断并以 "..." 结尾。
	Description string `json:"description,omitempty"`
	// 支付单实际支付金额,整型,单位:分钱。
	PaidAmount int64 `json:"paid_amount,omitzero"`
	// 支付者openid。
	OpenID string `json:"openid,omitempty"`
	// 交易创建时间,时间戳形式。
	TradeCreateTime int64 `json:"trade_create_time,omitzero"`
	// 支付时间,时间戳形式。
	PayTime int64 `json:"pay_time,omitzero"`
	// 订单状态枚举:(1) 待发货;(2) 已发货;(3) 确认收货;(4) 交易完成;(5) 已退款;(6) 资金待结算。
	OrderState int64 `json:"order_state,omitzero"`
	// 是否处在交易纠纷中。
	InComplaint bool `json:"in_complaint,omitzero"`
	// 发货信息。
	Shipping *PostWxaSecOrderGetOrderListResponseShippingObject `json:"shipping,omitempty"`
}

// PostWxaSecOrderGetOrderListResponseShippingObject is a documented nested object.
type PostWxaSecOrderGetOrderListResponseShippingObject struct {
	// 发货模式,发货模式枚举值:1、UNIFIED_DELIVERY(统一发货)2、SPLIT_DELIVERY(分拆发货) 示例值: UNIFIED_DELIVERY
	DeliveryMode int64 `json:"delivery_mode,omitzero"`
	// 物流模式,发货方式枚举值:1、实体物流配送采用快递公司进行实体物流配送形式 2、同城配送 3、虚拟商品,虚拟商品,例如话费充值,点卡等,无实体配送形式 4、用户自提
	LogisticsType int64 `json:"logistics_type,omitzero"`
	// 是否已完成全部发货。
	FinishShipping bool `json:"finish_shipping,omitzero"`
	// 在小程序后台发货信息录入页录入的商品描述。
	GoodsDesc string `json:"goods_desc,omitempty"`
	// 已完成全部发货的次数,未完成时为 0,完成时为 1,重新发货并完成后为 2。
	FinishShippingCount int64 `json:"finish_shipping_count,omitzero"`
	// 物流信息列表,发货物流单列表,支持统一发货(单个物流单)和分拆发货(多个物流单)两种模式。
	ShippingList []*PostWxaSecOrderGetOrderListResponseShippingListObject `json:"shipping_list,omitempty"`
}

// PostWxaSecOrderGetOrderListResponseShippingListObject is a documented nested object.
type PostWxaSecOrderGetOrderListResponseShippingListObject struct {
	// 物流单号,示例值: "323244567777"。
	TrackingNo string `json:"tracking_no,omitempty"`
	// 同城配送公司名或物流公司编码,快递公司ID,参见 获取运力 id 列表get_delivery_list 示例值: "DHL"。
	ExpressCompany string `json:"express_company,omitempty"`
	// 使用上传物流信息 API 录入的该物流信息的商品描述。
	GoodsDesc string `json:"goods_desc,omitempty"`
	// 该物流信息的上传时间,时间戳形式。
	UploadTime int64 `json:"upload_time,omitzero"`
	// 联系方式。
	Contact map[string]any `json:"contact,omitempty"`
}

func (c *Client) PostWxaSecOrderGetOrderList(ctx context.Context, req *PostWxaSecOrderGetOrderListRequest) (*PostWxaSecOrderGetOrderListResponse, error) {
	return core.Call[PostWxaSecOrderGetOrderListResponse](c.EndpointClient, ctx, "POST", "/wxa/sec/order/get_order_list", req, postWxaSecOrderGetOrderListErrCodes, true, core.SignNone)
}

var postWxaSecOrderIsTradeManagedErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	40013: {
		Desc:     "appid非法。请检查appid是否有误",
		Solution: "",
	},
	40097: {
		Desc:     "请求参数非法。请检查appid是否已填写",
		Solution: "",
	},
	44990: {
		Desc:     "达到频控上限。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	61003: {
		Desc:     "服务商未被授权。请检查小程序是否已授权18或142权限集。",
		Solution: "",
	},
	61004: {
		Desc:     "客户端ip未授权。请检查调用端ip是否在服务商ip白名单中。",
		Solution: "",
	},
	61011: {
		Desc:     "服务商不合法。请检查access_token是否有误",
		Solution: "",
	},
}

// PostWxaSecOrderIsTradeManaged 查询小程序是否已开通发货信息管理服务 (POST /wxa/sec/order/is_trade_managed)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/order_shipping/api_istrademanaged.html
// PostWxaSecOrderIsTradeManagedRequest carries the documented parameters of one API call.
type PostWxaSecOrderIsTradeManagedRequest struct {
	// 待查询小程序的 appid,非服务商调用时仅能查询本账号
	AppID string `json:"appid"`
}

// PostWxaSecOrderIsTradeManagedResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaSecOrderIsTradeManagedResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 是否已开通小程序发货信息管理服务
	IsTradeManaged bool `json:"is_trade_managed,omitzero"`
}

func (c *Client) PostWxaSecOrderIsTradeManaged(ctx context.Context, req *PostWxaSecOrderIsTradeManagedRequest) (*PostWxaSecOrderIsTradeManagedResponse, error) {
	return core.Call[PostWxaSecOrderIsTradeManagedResponse](c.EndpointClient, ctx, "POST", "/wxa/sec/order/is_trade_managed", req, postWxaSecOrderIsTradeManagedErrCodes, true, core.SignNone)
}

var postWxaSecOrderIsTradeManagementConfirmationCompletedErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	40013: {
		Desc:     "appid非法。请检查appid是否有误",
		Solution: "",
	},
	40097: {
		Desc:     "请求参数非法。请检查appid是否已填写",
		Solution: "",
	},
	44990: {
		Desc:     "达到频控上限。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	61003: {
		Desc:     "服务商未被授权。请检查小程序是否已授权18或142权限集。",
		Solution: "",
	},
	61004: {
		Desc:     "客户端ip未授权。请检查调用端ip是否在服务商ip白名单中。",
		Solution: "",
	},
	61011: {
		Desc:     "服务商不合法。请检查access_token是否有误",
		Solution: "",
	},
}

// PostWxaSecOrderIsTradeManagementConfirmationCompleted 查询小程序是否已完成交易结算管理确认 (POST /wxa/sec/order/is_trade_management_confirmation_completed)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/order_shipping/api_istrademanagementconfirmationcompleted.html
// PostWxaSecOrderIsTradeManagementConfirmationCompletedRequest carries the documented parameters of one API call.
type PostWxaSecOrderIsTradeManagementConfirmationCompletedRequest struct {
	// 待查询小程序的 appid,非服务商调用时仅能查询本账号
	AppID string `json:"appid"`
}

// PostWxaSecOrderIsTradeManagementConfirmationCompletedResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaSecOrderIsTradeManagementConfirmationCompletedResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 是否已完成交易结算管理确认
	Completed bool `json:"completed,omitzero"`
}

func (c *Client) PostWxaSecOrderIsTradeManagementConfirmationCompleted(ctx context.Context, req *PostWxaSecOrderIsTradeManagementConfirmationCompletedRequest) (*PostWxaSecOrderIsTradeManagementConfirmationCompletedResponse, error) {
	return core.Call[PostWxaSecOrderIsTradeManagementConfirmationCompletedResponse](c.EndpointClient, ctx, "POST", "/wxa/sec/order/is_trade_management_confirmation_completed", req, postWxaSecOrderIsTradeManagementConfirmationCompletedErrCodes, true, core.SignNone)
}

var postWxaSecOrderNotifyConfirmReceiveErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060001: {
		Desc:     "支付单不存在。请检查微信支付单号形式下 transaction_id 字段或商户侧单号形式下 mchid、out_trade_no 字段是否有误",
		Solution: "",
	},
	10060002: {
		Desc:     "支付单已完成发货,无法继续发货。请检查支付单发货情况",
		Solution: "",
	},
	10060003: {
		Desc:     "支付单已使用重新发货机会。支付单处于已发货状态时调用该API视为重新发货,仅可重新发货一次,请检查支付单发货情况",
		Solution: "",
	},
	10060004: {
		Desc:     "支付单处于不可发货的状态。请检查支付单状态",
		Solution: "",
	},
	10060005: {
		Desc:     "物流类型有误。按照文档中物流类型枚举填写该字段",
		Solution: "",
	},
	10060006: {
		Desc:     "非快递发货时不允许分拆发货。非快递发货时不允许分拆发货,请检查请求参数",
		Solution: "",
	},
	10060007: {
		Desc:     "分拆发货模式下必须填写 is_all_delivered 字段。请检查请求参数中的 is_all_delivered 字段",
		Solution: "",
	},
	10060008: {
		Desc:     "商品描述 item_desc 字段不能为空。用于发货信息录入场景时商品描述字段不能为空",
		Solution: "",
	},
	10060009: {
		Desc:     "商品描述 item_desc 字段太长。请检查商品描述字段",
		Solution: "",
	},
	10060012: {
		Desc:     "系统错误。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060014: {
		Desc:     "参数错误。根据错误原因描述修改参数",
		Solution: "",
	},
	10060019: {
		Desc:     "系统错误。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060020: {
		Desc:     "该笔支付单在没有任何商品描述的情况下不允许完成发货。请补充商品描述 item_desc",
		Solution: "",
	},
	10060023: {
		Desc:     "发货信息未更新。支付单信息不变",
		Solution: "",
	},
	10060024: {
		Desc:     "物流信息列表太长。支付单物流信息列表长度不可大于 15",
		Solution: "",
	},
	10060025: {
		Desc:     "物流公司编码太长。请检查物流公司编码是否有误",
		Solution: "",
	},
	10060026: {
		Desc:     "物流单号太长.。请检查物流单号是否有误",
		Solution: "",
	},
	10060028: {
		Desc:     "支付单不是已发货状态。请检查支付单状态",
		Solution: "",
	},
	10060029: {
		Desc:     "签收时间非法。请检查签收时间是否在发货时间之后",
		Solution: "",
	},
	10060030: {
		Desc:     "支付单已使用提醒收货机会。不可再提醒收货",
		Solution: "",
	},
	10060031: {
		Desc:     "该笔支付单不属于 openid 所指定的用户。请检查支付单号或 openid 是否有误",
		Solution: "",
	},
	10060032: {
		Desc:     "只有物流快递发货时允许提醒用户确认收货。请检查支付单物流类型",
		Solution: "",
	},
	268485194: {
		Desc:     "订单单号类型非法。按照文档中订单单号类型枚举填写该字段",
		Solution: "",
	},
	268485195: {
		Desc:     "微信支付单号形式下 transaction_id 字段不能为空。微信支付单号形式下 transaction_id 字段必须设置",
		Solution: "",
	},
	268485196: {
		Desc:     "商户侧单号形式下 mchid 字段不能为空。商户侧单号形式下 mchid 字段必须设置",
		Solution: "",
	},
	268485197: {
		Desc:     "商户侧单号形式下 out_trade_no 字段不能为空。商户侧单号形式下 out_trade_no 字段必须设置",
		Solution: "",
	},
	268485216: {
		Desc:     "上传时间非法,请按照 RFC 3339 格式填写。上传时间必须满足 RFC 3339 格式,如 2022-12-15T13:29:35.120+08:00",
		Solution: "",
	},
	268485224: {
		Desc:     "发货模式非法。按照文档中发货模式枚举设置该字段",
		Solution: "",
	},
	268485226: {
		Desc:     "物流单号不能为空。物流快递发货时物流单号必须填写",
		Solution: "",
	},
	268485227: {
		Desc:     "物流公司编码不能为空。物流快递发货时物流公司编码必须填写",
		Solution: "",
	},
	268485228: {
		Desc:     "统一发货模式下,物流信息列表长度必须为 1。统一发货模式下,物流信息列表长度必须为 1",
		Solution: "",
	},
}

// PostWxaSecOrderNotifyConfirmReceive 确认收货提醒 (POST /wxa/sec/order/notify_confirm_receive)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/order_shipping/api_notifyconfirmreceive.html
// PostWxaSecOrderNotifyConfirmReceiveRequest carries the documented parameters of one API call.
type PostWxaSecOrderNotifyConfirmReceiveRequest struct {
	// 原支付交易对应的微信订单号。
	TransactionID string `json:"transaction_id,omitempty"`
	// 支付下单商户的商户号,由微信支付生成并下发。
	MerchantID string `json:"merchant_id,omitempty"`
	// 二级商户号。
	SubMerchantID string `json:"sub_merchant_id,omitempty"`
	// 商户系统内部订单号,只能是数字、大小写字母`_-*`且在同一个商户号下唯一。
	MerchantTradeNo string `json:"merchant_trade_no,omitempty"`
	// 快递签收时间,时间戳形式。
	ReceivedTime int64 `json:"received_time"`
}

// PostWxaSecOrderNotifyConfirmReceiveResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaSecOrderNotifyConfirmReceiveResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaSecOrderNotifyConfirmReceive(ctx context.Context, req *PostWxaSecOrderNotifyConfirmReceiveRequest) (*PostWxaSecOrderNotifyConfirmReceiveResponse, error) {
	return core.Call[PostWxaSecOrderNotifyConfirmReceiveResponse](c.EndpointClient, ctx, "POST", "/wxa/sec/order/notify_confirm_receive", req, postWxaSecOrderNotifyConfirmReceiveErrCodes, true, core.SignNone)
}

var postWxaSecOrderOpspecialorderErrCodes = map[int]core.ErrDoc{
	268546000: {
		Desc:     "type非法。请检查type",
		Solution: "",
	},
	268546001: {
		Desc:     "delay_to非法。请检查delay_to参数",
		Solution: "",
	},
	268546002: {
		Desc:     "账户不存在这个待发货单号。请检查单号是否有误",
		Solution: "",
	},
}

// PostWxaSecOrderOpspecialorder 特殊发货报备 (POST /wxa/sec/order/opspecialorder)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/order_shipping/api_opspecialorder.html
// PostWxaSecOrderOpspecialorderRequest carries the documented parameters of one API call.
type PostWxaSecOrderOpspecialorderRequest struct {
	// 需要特殊发货报备的订单号,可传入微信支付单号或商户单号
	OrderID string `json:"order_id"`
	// 特殊发货报备类型,1为预售商品订单,2为测试订单
	Type int64 `json:"type"`
	// 预计发货时间的unix时间戳,type为1时必填,type为2可省略
	DelayTo int64 `json:"delay_to,omitzero"`
}

// PostWxaSecOrderOpspecialorderResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaSecOrderOpspecialorderResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaSecOrderOpspecialorder(ctx context.Context, req *PostWxaSecOrderOpspecialorderRequest) (*PostWxaSecOrderOpspecialorderResponse, error) {
	return core.Call[PostWxaSecOrderOpspecialorderResponse](c.EndpointClient, ctx, "POST", "/wxa/sec/order/opspecialorder", req, postWxaSecOrderOpspecialorderErrCodes, true, core.SignNone)
}

var postWxaSecOrderSetMsgJumpPathErrCodes = map[int]core.ErrDoc{-1: {
	Desc:     "system error。系统繁忙,此时请开发者稍候再试",
	Solution: "",
}}

// PostWxaSecOrderSetMsgJumpPath 消息跳转路径设置 (POST /wxa/sec/order/set_msg_jump_path)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/order_shipping/api_setmsgjumppath.html
// PostWxaSecOrderSetMsgJumpPathRequest carries the documented parameters of one API call.
type PostWxaSecOrderSetMsgJumpPathRequest struct {
	// 商户自定义跳转路径。
	Path string `json:"path"`
}

// PostWxaSecOrderSetMsgJumpPathResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaSecOrderSetMsgJumpPathResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaSecOrderSetMsgJumpPath(ctx context.Context, req *PostWxaSecOrderSetMsgJumpPathRequest) (*PostWxaSecOrderSetMsgJumpPathResponse, error) {
	return core.Call[PostWxaSecOrderSetMsgJumpPathResponse](c.EndpointClient, ctx, "POST", "/wxa/sec/order/set_msg_jump_path", req, postWxaSecOrderSetMsgJumpPathErrCodes, true, core.SignNone)
}

var postWxaSecOrderSetwxatradetypecgiErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统错误",
	},
	0: {
		Desc:     "ok",
		Solution: "成功",
	},
	268486048: {
		Desc:     "",
		Solution: "重复申请,一个账号只能申请一次",
	},
}

// PostWxaSecOrderSetwxatradetypecgi 小程序交易类型变更申请 (POST /wxa/sec/order/setwxatradetypecgi)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/order_shipping/api_setwxatradetypecgi.html
// PostWxaSecOrderSetwxatradetypecgiRequest carries the documented parameters of one API call.
type PostWxaSecOrderSetwxatradetypecgiRequest struct {
	// 申请变更后的目标交易类型
	TradeType int64 `json:"trade_type"`
	// 申请材料列表,最多10个,其中视频最多3个
	MaterialList []*PostWxaSecOrderSetwxatradetypecgiRequestMaterialListObject `json:"material_list"`
	// 申请理由
	Reason string `json:"reason"`
}

// PostWxaSecOrderSetwxatradetypecgiRequestMaterialListObject is a documented nested object.
type PostWxaSecOrderSetwxatradetypecgiRequestMaterialListObject struct {
	// 材料类型:1-图片,2-视频
	Type int64 `json:"type"`
	// 通过 新增临时素材 接口上传后获取的 media_id
	MediaID string `json:"media_id"`
}

// PostWxaSecOrderSetwxatradetypecgiResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaSecOrderSetwxatradetypecgiResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaSecOrderSetwxatradetypecgi(ctx context.Context, req *PostWxaSecOrderSetwxatradetypecgiRequest) (*PostWxaSecOrderSetwxatradetypecgiResponse, error) {
	return core.Call[PostWxaSecOrderSetwxatradetypecgiResponse](c.EndpointClient, ctx, "POST", "/wxa/sec/order/setwxatradetypecgi", req, postWxaSecOrderSetwxatradetypecgiErrCodes, true, core.SignNone)
}

var postWxaSecOrderUploadCombinedShippingInfoErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060001: {
		Desc:     "支付单不存在。请检查微信支付单号形式下 transaction_id 字段或商户侧单号形式下 mchid、out_trade_no 字段是否有误",
		Solution: "",
	},
	10060002: {
		Desc:     "支付单已完成发货,无法继续发货。请检查支付单发货情况",
		Solution: "",
	},
	10060003: {
		Desc:     "支付单已使用重新发货机会。支付单处于已发货状态时调用该API视为重新发货,仅可重新发货一次,请检查支付单发货情况",
		Solution: "",
	},
	10060004: {
		Desc:     "支付单处于不可发货的状态。请检查支付单状态",
		Solution: "",
	},
	10060005: {
		Desc:     "物流类型有误。按照文档中物流类型枚举填写该字段",
		Solution: "",
	},
	10060006: {
		Desc:     "非快递发货时不允许分拆发货。非快递发货时不允许分拆发货,请检查请求参数",
		Solution: "",
	},
	10060007: {
		Desc:     "分拆发货模式下必须填写 is_all_delivered 字段。请检查请求参数中的 is_all_delivered 字段",
		Solution: "",
	},
	10060008: {
		Desc:     "商品描述 item_desc 字段不能为空。用于发货信息录入场景时商品描述字段不能为空",
		Solution: "",
	},
	10060009: {
		Desc:     "商品描述 item_desc 字段太长。请检查商品描述字段",
		Solution: "",
	},
	10060012: {
		Desc:     "系统错误。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060014: {
		Desc:     "参数错误。根据错误原因描述修改参数",
		Solution: "",
	},
	10060019: {
		Desc:     "系统错误。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060020: {
		Desc:     "该笔支付单在没有任何商品描述的情况下不允许完成发货。请补充商品描述 item_desc",
		Solution: "",
	},
	10060023: {
		Desc:     "发货信息未更新。支付单信息不变",
		Solution: "",
	},
	10060024: {
		Desc:     "物流信息列表太长。支付单物流信息列表长度不可大于 15",
		Solution: "",
	},
	10060025: {
		Desc:     "物流公司编码太长。请检查物流公司编码是否有误",
		Solution: "",
	},
	10060026: {
		Desc:     "物流单号太长.。请检查物流单号是否有误",
		Solution: "",
	},
	10060031: {
		Desc:     "该笔支付单不属于 openid 所指定的用户。请检查支付单号或 openid 是否有误",
		Solution: "",
	},
	268485194: {
		Desc:     "订单单号类型非法。按照文档中订单单号类型枚举填写该字段",
		Solution: "",
	},
	268485195: {
		Desc:     "微信支付单号形式下 transaction_id 字段不能为空。微信支付单号形式下 transaction_id 字段必须设置",
		Solution: "",
	},
	268485196: {
		Desc:     "商户侧单号形式下 mchid 字段不能为空。商户侧单号形式下 mchid 字段必须设置",
		Solution: "",
	},
	268485197: {
		Desc:     "商户侧单号形式下 out_trade_no 字段不能为空。商户侧单号形式下 out_trade_no 字段必须设置",
		Solution: "",
	},
	268485216: {
		Desc:     "上传时间非法,请按照 RFC 3339 格式填写。上传时间必须满足 RFC 3339 格式,如 2022-12-15T13:29:35.120+08:00",
		Solution: "",
	},
	268485224: {
		Desc:     "发货模式非法。按照文档中发货模式枚举设置该字段",
		Solution: "",
	},
	268485226: {
		Desc:     "物流单号不能为空。物流快递发货时物流单号必须填写",
		Solution: "",
	},
	268485227: {
		Desc:     "物流公司编码不能为空。物流快递发货时物流公司编码必须填写",
		Solution: "",
	},
	268485228: {
		Desc:     "统一发货模式下,物流信息列表长度必须为 1。统一发货模式下,物流信息列表长度必须为 1",
		Solution: "",
	},
}

// PostWxaSecOrderUploadCombinedShippingInfo 发货信息合单录入 (POST /wxa/sec/order/upload_combined_shipping_info)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/order_shipping/api_uploadcombinedshippinginfo.html
// PostWxaSecOrderUploadCombinedShippingInfoRequest carries the documented parameters of one API call.
type PostWxaSecOrderUploadCombinedShippingInfoRequest struct {
	// 合单订单,需要上传物流详情的合单订单,根据订单类型二选一
	OrderKey *PostWxaSecOrderUploadCombinedShippingInfoRequestOrderKeyObject `json:"order_key"`
	// 子单物流详情
	SubOrders []*PostWxaSecOrderUploadCombinedShippingInfoRequestSubOrdersObject `json:"sub_orders,omitempty"`
	// 上传时间,用于标识请求的先后顺序 示例值: `2022-12-15T13:29:35.120+08:00`
	UploadTime string `json:"upload_time"`
	// 支付者,支付者信息
	Payer *PostWxaSecOrderUploadCombinedShippingInfoRequestPayerObject `json:"payer"`
}

// PostWxaSecOrderUploadCombinedShippingInfoRequestOrderKeyObject is a documented nested object.
type PostWxaSecOrderUploadCombinedShippingInfoRequestOrderKeyObject struct {
	// 订单单号类型,用于确认需要上传详情的订单。枚举值1,使用下单商户号和商户侧单号;枚举值2,使用微信支付单号。
	OrderNumberType int64 `json:"order_number_type"`
	// 原支付交易对应的微信订单号
	TransactionID string `json:"transaction_id,omitempty"`
	// 支付下单商户的商户号,由微信支付生成并下发。
	Mchid string `json:"mchid,omitempty"`
	// 商户系统内部订单号,只能是数字、大小写字母`_-*`且在同一个商户号下唯一
	OutTradeNo string `json:"out_trade_no,omitempty"`
}

// PostWxaSecOrderUploadCombinedShippingInfoRequestSubOrdersObject is a documented nested object.
type PostWxaSecOrderUploadCombinedShippingInfoRequestSubOrdersObject struct {
	// 需要上传物流详情的子单订单,订单类型与合单订单保持一致
	OrderKey map[string]any `json:"order_key"`
	// 物流模式,发货方式枚举值:1、实体物流配送采用快递公司进行实体物流配送形式 2、同城配送 3、虚拟商品,虚拟商品,例如话费充值,点卡等,无实体配送形式 4、用户自提
	LogisticsType int64 `json:"logistics_type"`
	// 发货模式,发货模式枚举值:1、UNIFIED_DELIVERY(统一发货)2、SPLIT_DELIVERY(分拆发货) 示例值: UNIFIED_DELIVERY
	DeliveryMode int64 `json:"delivery_mode"`
	// 分拆发货模式时必填,用于标识分拆发货模式下是否已全部发货完成,只有全部发货完成的情况下才会向用户推送发货完成通知。示例值: true/false
	IsAllDelivered bool `json:"is_all_delivered,omitzero"`
	// 子单物流信息列表 多重性: [1, 15]
	ShippingList []map[string]any `json:"shipping_list,omitempty"`
}

// PostWxaSecOrderUploadCombinedShippingInfoRequestPayerObject is a documented nested object.
type PostWxaSecOrderUploadCombinedShippingInfoRequestPayerObject struct {
	// 用户标识,用户在小程序appid下的唯一标识。 下单前需获取到用户的Openid 示例值: oUpF8uMuAJO_M2pxb1Q9zNjWeS6o 字符字节限制: [1, 128]
	OpenID string `json:"openid"`
}

// PostWxaSecOrderUploadCombinedShippingInfoResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaSecOrderUploadCombinedShippingInfoResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaSecOrderUploadCombinedShippingInfo(ctx context.Context, req *PostWxaSecOrderUploadCombinedShippingInfoRequest) (*PostWxaSecOrderUploadCombinedShippingInfoResponse, error) {
	return core.Call[PostWxaSecOrderUploadCombinedShippingInfoResponse](c.EndpointClient, ctx, "POST", "/wxa/sec/order/upload_combined_shipping_info", req, postWxaSecOrderUploadCombinedShippingInfoErrCodes, true, core.SignNone)
}

var postWxaSecOrderUploadShippingInfoErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060001: {
		Desc:     "支付单不存在。请检查微信支付单号形式下 transaction_id 字段或商户侧单号形式下 mchid、out_trade_no 字段是否有误",
		Solution: "",
	},
	10060002: {
		Desc:     "支付单已完成发货,无法继续发货。请检查支付单发货情况",
		Solution: "",
	},
	10060003: {
		Desc:     "支付单已使用重新发货机会。支付单处于已发货状态时调用该API视为重新发货,仅可重新发货一次,请检查支付单发货情况",
		Solution: "",
	},
	10060004: {
		Desc:     "支付单处于不可发货的状态。请检查支付单状态",
		Solution: "",
	},
	10060005: {
		Desc:     "物流类型有误。按照文档中物流类型枚举填写该字段",
		Solution: "",
	},
	10060006: {
		Desc:     "非快递发货时不允许分拆发货。非快递发货时不允许分拆发货,请检查请求参数",
		Solution: "",
	},
	10060007: {
		Desc:     "分拆发货模式下必须填写 is_all_delivered 字段。请检查请求参数中的 is_all_delivered 字段",
		Solution: "",
	},
	10060008: {
		Desc:     "商品描述 item_desc 字段不能为空。用于发货信息录入场景时商品描述字段不能为空",
		Solution: "",
	},
	10060009: {
		Desc:     "商品描述 item_desc 字段太长。请检查商品描述字段",
		Solution: "",
	},
	10060012: {
		Desc:     "系统错误。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060014: {
		Desc:     "参数错误。根据错误原因描述修改参数",
		Solution: "",
	},
	10060019: {
		Desc:     "系统错误。系统繁忙,此时请开发者稍候再试",
		Solution: "",
	},
	10060020: {
		Desc:     "该笔支付单在没有任何商品描述的情况下不允许完成发货。请补充商品描述 item_desc",
		Solution: "",
	},
	10060023: {
		Desc:     "发货信息未更新。支付单信息不变",
		Solution: "",
	},
	10060024: {
		Desc:     "物流信息列表太长。支付单物流信息列表长度不可大于 15",
		Solution: "",
	},
	10060025: {
		Desc:     "物流公司编码太长。请检查物流公司编码是否有误",
		Solution: "",
	},
	10060026: {
		Desc:     "物流单号太长.。请检查物流单号是否有误",
		Solution: "",
	},
	10060031: {
		Desc:     "该笔支付单不属于 openid 所指定的用户。请检查支付单号或 openid 是否有误",
		Solution: "",
	},
	268485194: {
		Desc:     "订单单号类型非法。按照文档中订单单号类型枚举填写该字段",
		Solution: "",
	},
	268485195: {
		Desc:     "微信支付单号形式下 transaction_id 字段不能为空。微信支付单号形式下 transaction_id 字段必须设置",
		Solution: "",
	},
	268485196: {
		Desc:     "商户侧单号形式下 mchid 字段不能为空。商户侧单号形式下 mchid 字段必须设置",
		Solution: "",
	},
	268485197: {
		Desc:     "商户侧单号形式下 out_trade_no 字段不能为空。商户侧单号形式下 out_trade_no 字段必须设置",
		Solution: "",
	},
	268485216: {
		Desc:     "上传时间非法,请按照 RFC 3339 格式填写。上传时间必须满足 RFC 3339 格式,如 2022-12-15T13:29:35.120+08:00",
		Solution: "",
	},
	268485224: {
		Desc:     "发货模式非法。按照文档中发货模式枚举设置该字段",
		Solution: "",
	},
	268485226: {
		Desc:     "物流单号不能为空。物流快递发货时物流单号必须填写",
		Solution: "",
	},
	268485227: {
		Desc:     "物流公司编码不能为空。物流快递发货时物流公司编码必须填写",
		Solution: "",
	},
	268485228: {
		Desc:     "统一发货模式下,物流信息列表长度必须为 1。统一发货模式下,物流信息列表长度必须为 1",
		Solution: "",
	},
}

// PostWxaSecOrderUploadShippingInfo 发货信息录入 (POST /wxa/sec/order/upload_shipping_info)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/order_shipping/api_uploadshippinginfo.html
// PostWxaSecOrderUploadShippingInfoRequest carries the documented parameters of one API call.
type PostWxaSecOrderUploadShippingInfoRequest struct {
	// 订单,需要上传物流信息的订单
	OrderKey *PostWxaSecOrderUploadShippingInfoRequestOrderKeyObject `json:"order_key"`
	// 物流模式,发货方式枚举值:1、实体物流配送采用快递公司进行实体物流配送形式 2、同城配送 3、虚拟商品,虚拟商品,例如话费充值,点卡等,无实体配送形式 4、用户自提
	LogisticsType int64 `json:"logistics_type"`
	// 发货模式,发货模式枚举值:1、UNIFIED_DELIVERY(统一发货)2、SPLIT_DELIVERY(分拆发货)
	DeliveryMode int64 `json:"delivery_mode"`
	// 分拆发货模式时必填,用于标识分拆发货模式下是否已全部发货完成,只有全部发货完成的情况下才会向用户推送发货完成通知。示例值: true/false
	IsAllDelivered bool `json:"is_all_delivered,omitzero"`
	// 物流信息列表,发货物流单列表,支持统一发货(单个物流单)和分拆发货(多个物流单)两种模式,多重性: [1, 15]
	ShippingList []*PostWxaSecOrderUploadShippingInfoRequestShippingListObject `json:"shipping_list"`
	// 上传时间,用于标识请求的先后顺序 示例值: `2022-12-15T13:29:35.120+08:00`
	UploadTime string `json:"upload_time"`
	// 支付者,支付者信息
	Payer *PostWxaSecOrderUploadShippingInfoRequestPayerObject `json:"payer"`
}

// PostWxaSecOrderUploadShippingInfoRequestOrderKeyObject is a documented nested object.
type PostWxaSecOrderUploadShippingInfoRequestOrderKeyObject struct {
	// 订单单号类型,用于确认需要上传详情的订单。枚举值1,使用下单商户号和商户侧单号;枚举值2,使用微信支付单号。
	OrderNumberType int64 `json:"order_number_type"`
	// 原支付交易对应的微信订单号
	TransactionID string `json:"transaction_id,omitempty"`
	// 支付下单商户的商户号,由微信支付生成并下发。
	Mchid string `json:"mchid,omitempty"`
	// 商户系统内部订单号,只能是数字、大小写字母`_-*`且在同一个商户号下唯一
	OutTradeNo string `json:"out_trade_no,omitempty"`
}

// PostWxaSecOrderUploadShippingInfoRequestShippingListObject is a documented nested object.
type PostWxaSecOrderUploadShippingInfoRequestShippingListObject struct {
	// 物流单号,物流快递发货时必填,示例值: 323244567777 字符字节限制: [1, 128]
	TrackingNo string `json:"tracking_no,omitempty"`
	// 物流公司编码,快递公司ID,参见 获取运力 id 列表get_delivery_list ,物流快递发货时必填, 示例值: DHL 字符字节限制: [1, 128]
	ExpressCompany string `json:"express_company,omitempty"`
	// 商品信息,例如:微信红包抱枕*1个,限120个字以内
	ItemDesc string `json:"item_desc"`
	// 联系方式,当发货的物流公司为顺丰时,联系方式为必填,收件人或寄件人联系方式二选一
	Contact map[string]any `json:"contact,omitempty"`
}

// PostWxaSecOrderUploadShippingInfoRequestPayerObject is a documented nested object.
type PostWxaSecOrderUploadShippingInfoRequestPayerObject struct {
	// 用户标识,用户在小程序appid下的唯一标识。 下单前需获取到用户的Openid 示例值: oUpF8uMuAJO_M2pxb1Q9zNjWeS6o 字符字节限制: [1, 128]
	OpenID string `json:"openid"`
}

// PostWxaSecOrderUploadShippingInfoResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaSecOrderUploadShippingInfoResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) PostWxaSecOrderUploadShippingInfo(ctx context.Context, req *PostWxaSecOrderUploadShippingInfoRequest) (*PostWxaSecOrderUploadShippingInfoResponse, error) {
	return core.Call[PostWxaSecOrderUploadShippingInfoResponse](c.EndpointClient, ctx, "POST", "/wxa/sec/order/upload_shipping_info", req, postWxaSecOrderUploadShippingInfoErrCodes, true, core.SignNone)
}
