// Code generated by docsync from the official WeChat documentation. DO NOT EDIT.
// The API surface (names, request/response shapes) is derived deterministically
// from the endpoints; regenerate with "make docs-sync". If this file changes
// under you, the upstream documentation changed.

package miniprogram

import (
	"context"
	"github.com/go-sphere/weixin-api/core"
)

var postWxaBusinessCheckencryptedmsgErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	1: {
		Desc:     "data not exit",
		Solution: "加密数据不存在,数据生成的时间超过保存的限制(3天)或者 key 不存在,或者数据和appid不匹配",
	},
	40097: {
		Desc:     "invalid args",
		Solution: "参数错误",
	},
	44002: {
		Desc:     "empty post data",
		Solution: "POST 的数据包为空。post请求body参数不能为空。",
	},
	47001: {
		Desc:     "data format error",
		Solution: "解析 JSON/XML 内容错误;post 数据中参数缺失;检查修正后重试。",
	},
}

// PostWxaBusinessCheckencryptedmsg 检查加密信息 (POST /wxa/business/checkencryptedmsg)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/user-info/basic-info/api_checkencrypteddata.html
// PostWxaBusinessCheckencryptedmsgRequest carries the documented parameters of one API call.
type PostWxaBusinessCheckencryptedmsgRequest struct {
	// 加密数据的sha256,通过Hex(Base16)编码后的字符串
	EncryptedMsgHash string `json:"encrypted_msg_hash"`
}

// PostWxaBusinessCheckencryptedmsgResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBusinessCheckencryptedmsgResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误提示信息
	Errmsg string `json:"errmsg,omitempty"`
	// 是否是合法的数据
	Vaild bool `json:"vaild,omitzero"`
	// 加密数据生成的时间戳
	CreateTime int64 `json:"create_time,omitzero"`
}

func (c *Client) PostWxaBusinessCheckencryptedmsg(ctx context.Context, req *PostWxaBusinessCheckencryptedmsgRequest) (*PostWxaBusinessCheckencryptedmsgResponse, error) {
	return core.Call[PostWxaBusinessCheckencryptedmsgResponse](c.EndpointClient, ctx, "POST", "/wxa/business/checkencryptedmsg", req, postWxaBusinessCheckencryptedmsgErrCodes, true, core.SignNone)
}

var getWxaBusinessGetuserencryptkeyErrCodes = map[int]core.ErrDoc{
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	87007: {
		Desc:     "session_key is not existd or expired",
		Solution: "加密key不存在或已过期",
	},
	87008: {
		Desc:     "invalid sig_method",
		Solution: "无效的签名方法",
	},
	87009: {
		Desc:     "invalid signature",
		Solution: "无效的签名",
	},
}

// GetWxaBusinessGetuserencryptkey 获取用户encryptKey (GET /wxa/business/getuserencryptkey)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/user-info/internet/api_getuserencryptkey.html
// GetWxaBusinessGetuserencryptkeyRequest carries the documented parameters of one API call.
type GetWxaBusinessGetuserencryptkeyRequest struct {
	// 用户的openid
	OpenID string `query:"openid"`
	// 用sessionkey作为密钥对空字符串签名得到的结果。session_key可通过 code2Session 接口获得。 伪代码:signature = hmac_sha256(session_key, "")
	Signature string `query:"signature"`
	// 签名方法,只支持 hmac_sha256
	SigMethod string `query:"sig_method"`
}

// GetWxaBusinessGetuserencryptkeyResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type GetWxaBusinessGetuserencryptkeyResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 用户最近三次的加密key列表
	KeyInfoList []*GetWxaBusinessGetuserencryptkeyResponseKeyInfoListObject `json:"key_info_list,omitempty"`
}

// GetWxaBusinessGetuserencryptkeyResponseKeyInfoListObject is a documented nested object.
type GetWxaBusinessGetuserencryptkeyResponseKeyInfoListObject struct {
	// 加密key
	EncryptKey string `json:"encrypt_key,omitempty"`
	// key的版本号
	Version int64 `json:"version,omitzero"`
	// 剩余有效时间
	ExpireIn int64 `json:"expire_in,omitzero"`
	// 加密iv
	Iv string `json:"iv,omitempty"`
	// 创建key的时间戳
	CreateTime int64 `json:"create_time,omitzero"`
}

func (c *Client) GetWxaBusinessGetuserencryptkey(ctx context.Context, req *GetWxaBusinessGetuserencryptkeyRequest) (*GetWxaBusinessGetuserencryptkeyResponse, error) {
	return core.Call[GetWxaBusinessGetuserencryptkeyResponse](c.EndpointClient, ctx, "GET", "/wxa/business/getuserencryptkey", req, getWxaBusinessGetuserencryptkeyErrCodes, true, core.SignNone)
}

var postWxaBusinessGetuserphonenumberErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	40013: {
		Desc:     "invalid appid",
		Solution: "请求appid身份与获取code的小程序appid不匹配",
	},
	40029: {
		Desc:     "code 无效",
		Solution: "js_code无效",
	},
	45011: {
		Desc:     "api minute-quota reach limit mustslower retry next minute",
		Solution: "API 调用太频繁,请稍候再试",
	},
}

// PostWxaBusinessGetuserphonenumber 获取手机号 (POST /wxa/business/getuserphonenumber)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/user-info/phone-number/api_getphonenumber.html
// PostWxaBusinessGetuserphonenumberRequest carries the documented parameters of one API call.
type PostWxaBusinessGetuserphonenumberRequest struct {
	// 手机号获取凭证
	Code string `json:"code"`
	// 用户openid, 填入后会校验openid和code的绑定关系,并在不匹配时报错
	OpenID string `json:"openid,omitempty"`
}

// PostWxaBusinessGetuserphonenumberResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaBusinessGetuserphonenumberResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 用户手机号信息
	PhoneInfo *PostWxaBusinessGetuserphonenumberResponsePhoneInfoObject `json:"phone_info,omitempty"`
}

// PostWxaBusinessGetuserphonenumberResponsePhoneInfoObject is a documented nested object.
type PostWxaBusinessGetuserphonenumberResponsePhoneInfoObject struct {
	// 用户绑定的手机号(国外手机号会有区号)
	PhoneNumber string `json:"phoneNumber,omitempty"`
	// 没有区号的手机号
	PurePhoneNumber string `json:"purePhoneNumber,omitempty"`
	// 区号
	CountryCode string `json:"countryCode,omitempty"`
	// 数据水印
	Watermark *PostWxaBusinessGetuserphonenumberResponseWatermarkObject `json:"watermark,omitempty"`
}

// PostWxaBusinessGetuserphonenumberResponseWatermarkObject is a documented nested object.
type PostWxaBusinessGetuserphonenumberResponseWatermarkObject struct {
	// 用户获取手机号操作的时间戳
	Timestamp int64 `json:"timestamp,omitzero"`
	// 小程序appid
	AppID string `json:"appid,omitempty"`
}

func (c *Client) PostWxaBusinessGetuserphonenumber(ctx context.Context, req *PostWxaBusinessGetuserphonenumberRequest) (*PostWxaBusinessGetuserphonenumberResponse, error) {
	return core.Call[PostWxaBusinessGetuserphonenumberResponse](c.EndpointClient, ctx, "POST", "/wxa/business/getuserphonenumber", req, postWxaBusinessGetuserphonenumberErrCodes, true, core.SignNone)
}

var getWxaGetpaidunionidErrCodes = map[int]core.ErrDoc{
	-1: {
		Desc:     "system error",
		Solution: "系统繁忙,此时请开发者稍候再试",
	},
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	40001: {
		Desc:     "invalid credential access_token isinvalid or not latest",
		Solution: "获取 access_token 时 AppSecret 错误,或者 access_token 无效。请开发者认真比对 AppSecret 的正确性,或查看是否正在为恰当的公众号调用接口",
	},
	40003: {
		Desc:     "invalid openid",
		Solution: "不合法的 OpenID ,请开发者确认 OpenID (该用户)是否已关注公众号,或是否是其他公众号的 OpenID",
	},
	89002: {
		Desc:     "open not exists",
		Solution: "open not exists,该公众号/小程序未绑定微信开放平台帐号。",
	},
	89300: {
		Desc:     "invalid trade",
		Solution: "订单无效",
	},
}

// GetWxaGetpaidunionid 支付后获取Unionid (GET /wxa/getpaidunionid)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/user-info/basic-info/api_getpaidunionid.html
// GetWxaGetpaidunionidRequest carries the documented parameters of one API call.
type GetWxaGetpaidunionidRequest struct {
	// 支付用户唯一标识
	OpenID string `json:"openid"`
	// 微信支付订单号
	TransactionID string `json:"transaction_id,omitempty"`
	// 微信支付分配的 商户号 ,和商户订单号配合使用
	MchID string `json:"mch_id,omitempty"`
	// 微信支付商户订单号 ,和商户号配合使用
	OutTradeNo string `json:"out_trade_no,omitempty"`
}

// GetWxaGetpaidunionidResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type GetWxaGetpaidunionidResponse struct {
	// 用户唯一标识,调用成功后返回
	UnionID string `json:"unionid,omitempty"`
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
}

func (c *Client) GetWxaGetpaidunionid(ctx context.Context, req *GetWxaGetpaidunionidRequest) (*GetWxaGetpaidunionidResponse, error) {
	return core.Call[GetWxaGetpaidunionidResponse](c.EndpointClient, ctx, "GET", "/wxa/getpaidunionid", req, getWxaGetpaidunionidErrCodes, true, core.SignNone)
}

var postWxaGetpluginopenpidErrCodes = map[int]core.ErrDoc{
	0: {
		Desc:     "ok",
		Solution: "ok",
	},
	1000: {
		Desc:     "系统错误",
		Solution: "",
	},
	1001: {
		Desc:     "请求参数非法",
		Solution: "",
	},
	1003: {
		Desc:     "请求频率过快",
		Solution: "",
	},
	1005: {
		Desc:     "插件 appid 与数据不匹配",
		Solution: "",
	},
	1007: {
		Desc:     "openpid数据不存在",
		Solution: "",
	},
	1022: {
		Desc:     "json数据解析错误",
		Solution: "",
	},
	40016: {
		Desc:     "invalid button size",
		Solution: "不合法的按钮个数",
	},
	45009: {
		Desc:     "reach max api daily quota limit",
		Solution: "天级别频率限制,2种解决途径2选1: 1.到小程序mp-开发管理-接口设置-调用额度重置;2.调用限频重置API",
	},
}

// PostWxaGetpluginopenpid 获取插件用户openpid (POST /wxa/getpluginopenpid)
// Doc: https://developers.weixin.qq.com/miniprogram/dev/server/API/user-info/basic-info/api_getpluginopenpid.html
// PostWxaGetpluginopenpidRequest carries the documented parameters of one API call.
type PostWxaGetpluginopenpidRequest struct {
	// 通过 wx.pluginLogin 获得的插件用户标志凭证 code,有效时间为5分钟,一个 code 只能获取一次 openpid。
	Code string `json:"code"`
}

// PostWxaGetpluginopenpidResponse mirrors the documented response payload. Fields the docs do
// not tabulate are not present; extend the struct as needed.
type PostWxaGetpluginopenpidResponse struct {
	// 错误码
	Errcode int64 `json:"errcode,omitzero"`
	// 错误信息
	Errmsg string `json:"errmsg,omitempty"`
	// 插件用户的唯一标识。
	OpenPid string `json:"openpid,omitempty"`
}

func (c *Client) PostWxaGetpluginopenpid(ctx context.Context, req *PostWxaGetpluginopenpidRequest) (*PostWxaGetpluginopenpidResponse, error) {
	return core.Call[PostWxaGetpluginopenpidResponse](c.EndpointClient, ctx, "POST", "/wxa/getpluginopenpid", req, postWxaGetpluginopenpidErrCodes, true, core.SignNone)
}
